"""Script to rebuild random_songs.py with 2000 unique songs. Delete after use."""
import re

with open('random_songs.py', 'r', encoding='utf-8') as f:
    content = f.read()

songs = re.findall(r'ytsearch1:([^"]+)', content)
seen = set()
unique = []
for s in songs:
    key = s.strip().lower()
    if key not in seen:
        seen.add(key)
        unique.append(s.strip())

print(f"Starting unique: {len(unique)}")

# New songs to add - all extremely famous worldwide hits
new_songs = [
    # CLASSIC ROCK EXPANSION
    "AC/DC Highway To Hell",
    "AC/DC Thunderstruck",
    "AC/DC You Shook Me All Night Long",
    "AC/DC T.N.T.",
    "AC/DC For Those About To Rock",
    "Led Zeppelin Black Dog",
    "Led Zeppelin Rock And Roll",
    "Led Zeppelin Whole Lotta Love",
    "Led Zeppelin Going To California",
    "Led Zeppelin When The Levee Breaks",
    "Pink Floyd Money",
    "Pink Floyd Time",
    "Pink Floyd Shine On You Crazy Diamond",
    "Pink Floyd Us And Them",
    "Pink Floyd Brain Damage",
    "The Rolling Stones Gimme Shelter",
    "The Rolling Stones Sympathy For The Devil",
    "The Rolling Stones Angie",
    "The Rolling Stones Wild Horses",
    "The Rolling Stones Miss You",
    "The Rolling Stones Start Me Up",
    "The Beatles Here Comes The Sun",
    "The Beatles Come Together",
    "The Beatles Something",
    "The Beatles Yesterday",
    "The Beatles Let It Be",
    "The Beatles Hey Jude",
    "The Beatles Twist And Shout",
    "The Beatles I Want To Hold Your Hand",
    "The Beatles A Day In The Life",
    "The Beatles Strawberry Fields Forever",
    "Queen We Will Rock You",
    "Queen Bohemian Rhapsody",
    "Queen We Are The Champions",
    "Queen Somebody To Love",
    "Queen Under Pressure ft David Bowie",
    "Queen Radio Ga Ga",
    "Queen I Want To Break Free",
    "Queen Another One Bites The Dust",
    "Queen Killer Queen",
    "Fleetwood Mac Dreams",
    "Fleetwood Mac The Chain",
    "Fleetwood Mac Go Your Own Way",
    "Fleetwood Mac Everywhere",
    "Fleetwood Mac Little Lies",
    "The Eagles Hotel California",
    "The Eagles Take It Easy",
    "The Eagles Desperado",
    "The Eagles Life In The Fast Lane",
    "Dire Straits Sultans Of Swing",
    "Dire Straits Money For Nothing",
    "Dire Straits Brothers In Arms",
    "The Doors Riders On The Storm",
    "The Doors Light My Fire",
    "The Doors People Are Strange",
    "The Doors LA Woman",
    "The Who Baba O Riley",
    "The Who My Generation",
    "Jimi Hendrix Purple Haze",
    "Jimi Hendrix All Along The Watchtower",
    "Jimi Hendrix Voodoo Child",
    "Jimi Hendrix Little Wing",
    "Eric Clapton Layla",
    "Eric Clapton Wonderful Tonight",
    "Eric Clapton Tears In Heaven",
    "Eric Clapton Cocaine",
    "Creedence Clearwater Revival Fortunate Son",
    "Creedence Clearwater Revival Have You Ever Seen The Rain",
    "Creedence Clearwater Revival Bad Moon Rising",
    "Creedence Clearwater Revival Proud Mary",
    "David Bowie Heroes",
    "David Bowie Space Oddity",
    "David Bowie Starman",
    "David Bowie Ziggy Stardust",
    "David Bowie Life On Mars",
    "The Clash London Calling",
    "The Clash Should I Stay Or Should I Go",
    "The Clash Rock The Casbah",
    "Stevie Wonder Superstition",
    "Stevie Wonder I Just Called To Say I Love You",
    "Stevie Wonder Sir Duke",
    "Stevie Wonder Signed Sealed Delivered",
    "Prince Purple Rain",
    "Prince Kiss",
    "Prince When Doves Cry",
    "Prince 1999",
    "Prince Little Red Corvette",
    "Elton John Rocket Man",
    "Elton John Tiny Dancer",
    "Elton John Your Song",
    "Elton John Crocodile Rock",
    "Elton John Bennie And The Jets",
    "Billy Joel Piano Man",
    "Billy Joel Uptown Girl",
    "Billy Joel Vienna",
    "Billy Joel Just The Way You Are",
    "Bob Marley Is This Love",
    "Bob Marley Three Little Birds",
    "Bob Marley Buffalo Soldier",
    "Bob Marley Redemption Song",
    "Bob Marley One Love",
    "Bob Marley No Woman No Cry",
    "Bob Marley Jamming",
    "Bob Marley Could You Be Loved",
    # SOUL / MOTOWN / FUNK
    "Marvin Gaye What Is Going On",
    "Marvin Gaye Sexual Healing",
    "Otis Redding Sitting On The Dock Of The Bay",
    "Al Green Lets Stay Together",
    "Al Green Tired Of Being Alone",
    "Sam Cooke A Change Is Gonna Come",
    "Sam Cooke Cupid",
    "Aretha Franklin Respect",
    "Aretha Franklin I Say A Little Prayer",
    "Aretha Franklin Natural Woman",
    "James Brown I Got You I Feel Good",
    "James Brown Get Up Offa That Thing",
    "Ray Charles Hit The Road Jack",
    "Ray Charles I Got A Woman",
    "Ray Charles Georgia On My Mind",
    "Earth Wind Fire September",
    "Earth Wind Fire Boogie Wonderland",
    "Earth Wind Fire Lets Groove",
    "Kool And The Gang Celebration",
    "Kool And The Gang Get Down On It",
    "Parliament Flashlight",
    "Parliament Give Up The Funk",
    "Sly And The Family Stone Everyday People",
    "Curtis Mayfield Move On Up",
    "Bill Withers Lean On Me",
    "Bill Withers Lovely Day",
    "Bill Withers Just The Two Of Us",
    "The Temptations My Girl",
    "The Temptations Aint Too Proud To Beg",
    "Chaka Khan Aint Nobody",
    "Diana Ross Im Coming Out",
    "Diana Ross Upside Down",
    "Rick James Super Freak",
    # 80s / 90s POP EXPANSION
    "Phil Collins In The Air Tonight",
    "Phil Collins Against All Odds",
    "Phil Collins Easy Lover",
    "Genesis Invisible Touch",
    "Genesis Land Of Confusion",
    "Peter Gabriel Sledgehammer",
    "Peter Gabriel In Your Eyes",
    "Duran Duran Hungry Like The Wolf",
    "Duran Duran Rio",
    "Duran Duran Ordinary World",
    "The Police Every Breath You Take",
    "The Police Roxanne",
    "The Police Message In A Bottle",
    "Sting Fields Of Gold",
    "Sting Englishman In New York",
    "Tears For Fears Everybody Wants To Rule The World",
    "Tears For Fears Shout",
    "Tears For Fears Head Over Heels",
    "Depeche Mode Enjoy The Silence",
    "Depeche Mode Personal Jesus",
    "Depeche Mode Just Cant Get Enough",
    "New Order Blue Monday",
    "New Order Bizarre Love Triangle",
    "The Cure Friday Im In Love",
    "The Cure Just Like Heaven",
    "The Cure Lovesong",
    "The Smiths There Is A Light That Never Goes Out",
    "The Smiths How Soon Is Now",
    "The Smiths This Charming Man",
    "Talking Heads Psycho Killer",
    "Talking Heads Once In A Lifetime",
    "Talking Heads Burning Down The House",
    "Joy Division Love Will Tear Us Apart",
    "Pet Shop Boys West End Girls",
    "Pet Shop Boys Its A Sin",
    "Erasure A Little Respect",
    "OMD Enola Gay",
    "Soft Cell Tainted Love",
    "Culture Club Karma Chameleon",
    "Wham Wake Me Up Before You Go Go",
    "George Michael Careless Whisper",
    "George Michael Faith",
    "George Michael Father Figure",
    "Cyndi Lauper Girls Just Want To Have Fun",
    "Cyndi Lauper Time After Time",
    "Pat Benatar Love Is A Battlefield",
    "Pat Benatar Hit Me With Your Best Shot",
    "Blondie Heart Of Glass",
    "Blondie Call Me",
    "Blondie One Way Or Another",
    "Kate Bush Running Up That Hill",
    "Kate Bush Wuthering Heights",
    "Kate Bush Babooshka",
    "Tina Turner Whats Love Got To Do With It",
    "Tina Turner The Best",
    "Tina Turner Private Dancer",
    "Whitney Houston I Wanna Dance With Somebody",
    "Whitney Houston I Will Always Love You",
    "Whitney Houston Greatest Love Of All",
    "Whitney Houston How Will I Know",
    "Sade Smooth Operator",
    "Sade No Ordinary Love",
    "Sade Your Love Is King",
    "Lionel Richie All Night Long",
    "Lionel Richie Hello",
    "Lionel Richie Dancing On The Ceiling",
    "Hall And Oates Maneater",
    "Hall And Oates Out Of Touch",
    "Dire Straits Walk Of Life",
    "Dire Straits Romeo And Juliet",
    "Simple Minds Dont You Forget About Me",
    "INXS Need You Tonight",
    "INXS Never Tear Us Apart",
    "The Cranberries Zombie",
    "The Cranberries Linger",
    "The Cranberries Dreams",
    # 90s/2000s ROCK & ALT
    "Pearl Jam Black",
    "Pearl Jam Alive",
    "Pearl Jam Jeremy",
    "Pearl Jam Even Flow",
    "Pearl Jam Better Man",
    "Alice In Chains Rooster",
    "Alice In Chains Would",
    "Alice In Chains Man In The Box",
    "Alice In Chains Down In A Hole",
    "Soundgarden Black Hole Sun",
    "Soundgarden Fell On Black Days",
    "Soundgarden Spoonman",
    "Stone Temple Pilots Plush",
    "Stone Temple Pilots Interstate Love Song",
    "Stone Temple Pilots Creep",
    "Blind Melon No Rain",
    "Temple Of The Dog Hunger Strike",
    "Audioslave Like A Stone",
    "Audioslave Show Me How To Live",
    "Audioslave Cochise",
    "Chris Cornell The Promise",
    "System Of A Down Chop Suey",
    "System Of A Down Toxicity",
    "System Of A Down B.Y.O.B.",
    "System Of A Down Aerials",
    "Tool Schism",
    "Tool Lateralus",
    "Tool Sober",
    "Tool 46 And 2",
    "Rage Against The Machine Killing In The Name",
    "Rage Against The Machine Bulls On Parade",
    "Rage Against The Machine Guerrilla Radio",
    "Korn Freak On A Leash",
    "Korn Got The Life",
    "Deftones Change In The House Of Flies",
    "Deftones My Own Summer",
    "Deftones Digital Bath",
    "Incubus Drive",
    "Incubus Wish You Were Here",
    "Incubus Stellar",
    "Three Doors Down Kryptonite",
    "Three Doors Down Here Without You",
    "Three Doors Down When Im Gone",
    "Staind Its Been Awhile",
    "Puddle Of Mudd Blurry",
    "Puddle Of Mudd She Hates Me",
    "Creed My Sacrifice",
    "Creed With Arms Wide Open",
    "Creed Higher",
    "Creed One Last Breath",
    "Nickelback How You Remind Me",
    "Nickelback Photograph",
    "Nickelback Rockstar",
    "Nickelback Someday",
    "Breaking Benjamin The Diary Of Jane",
    "Breaking Benjamin So Cold",
    "Seether Broken ft Amy Lee",
    "Seether Fake It",
    "Shinedown Second Chance",
    "Shinedown Simple Man",
    "Godsmack I Stand Alone",
    "Disturbed Down With The Sickness",
    "Disturbed The Sound Of Silence",
    "Five Finger Death Punch Wrong Side Of Heaven",
    "Avenged Sevenfold Hail To The King",
    "Avenged Sevenfold Nightmare",
    "Avenged Sevenfold Afterlife",
    "Bullet For My Valentine Tears Dont Fall",
    "Bring Me The Horizon Can You Feel My Heart",
    "Bring Me The Horizon Drown",
    "Bring Me The Horizon Throne",
    "My Chemical Romance The Black Parade",
    "My Chemical Romance Helena",
    "My Chemical Romance Im Not Okay",
    # HIP-HOP / RAP EXPANSION
    "Jay-Z Empire State Of Mind ft Alicia Keys",
    "Jay-Z 99 Problems",
    "Jay-Z Hard Knock Life",
    "Jay-Z Run This Town ft Rihanna",
    "Kanye West Gold Digger",
    "Kanye West Stronger",
    "Kanye West Power",
    "Kanye West Heartless",
    "Kanye West Runaway",
    "Kanye West All Of The Lights",
    "Kanye West Flashing Lights",
    "Kanye West Love Lockdown",
    "50 Cent In Da Club",
    "50 Cent Candy Shop",
    "50 Cent 21 Questions",
    "50 Cent Many Men",
    "50 Cent P.I.M.P.",
    "Nas NY State Of Mind",
    "Nas If I Ruled The World",
    "Nas One Mic",
    "DMX Party Up In Here",
    "DMX X Gon Give It To Ya",
    "Ludacris Stand Up",
    "Ludacris Move Get Out The Way",
    "Lil Wayne Lollipop",
    "Lil Wayne A Milli",
    "Lil Wayne 6 Foot 7 Foot",
    "Lil Wayne How To Love",
    "Lil Wayne Mirror ft Bruno Mars",
    "T.I. Whatever You Like",
    "T.I. Live Your Life ft Rihanna",
    "Nelly Hot In Herre",
    "Nelly Dilemma ft Kelly Rowland",
    "Nelly Ride Wit Me",
    "Ja Rule Always On Time ft Ashanti",
    "Busta Rhymes Break Ya Neck",
    "Busta Rhymes Touch It",
    "Missy Elliott Work It",
    "Missy Elliott Get Ur Freak On",
    "Missy Elliott Lose Control",
    "Snoop Dogg Drop It Like Its Hot",
    "Snoop Dogg Gin And Juice",
    "Dr. Dre Still D.R.E. ft Snoop Dogg",
    "Dr. Dre The Next Episode ft Snoop Dogg",
    "Dr. Dre Forgot About Dre",
    "Dr. Dre Nuthin But A G Thang",
    "Ice Cube It Was A Good Day",
    "Tupac California Love",
    "Tupac Changes",
    "Tupac Dear Mama",
    "Tupac Hit Em Up",
    "Tupac All Eyez On Me",
    "Biggie Juicy",
    "Biggie Big Poppa",
    "Biggie Hypnotize",
    "Biggie Mo Money Mo Problems",
    "Outkast Hey Ya",
    "Outkast Ms Jackson",
    "Outkast Roses",
    "Outkast So Fresh So Clean",
    "Outkast B.O.B.",
    # R&B / POP 2000s
    "Usher Yeah ft Lil Jon Ludacris",
    "Usher Burn",
    "Usher Confessions Part II",
    "Usher U Got It Bad",
    "Usher OMG ft will.i.am",
    "Usher My Boo ft Alicia Keys",
    "Destinys Child Say My Name",
    "Destinys Child Jumpin Jumpin",
    "Destinys Child Bootylicious",
    "TLC No Scrubs",
    "TLC Waterfalls",
    "TLC Creep",
    "Aaliyah Try Again",
    "Aaliyah Are You That Somebody",
    "Aaliyah One In A Million",
    "Aaliyah Rock The Boat",
    "R Kelly I Believe I Can Fly",
    "R Kelly Ignition Remix",
    "Nelly Furtado Say It Right",
    "Nelly Furtado Maneater",
    "Nelly Furtado Promiscuous ft Timbaland",
    "Timbaland The Way I Are",
    "Timbaland Apologize ft OneRepublic",
    "Fergie Glamorous",
    "Fergie Big Girls Dont Cry",
    "Sean Kingston Beautiful Girls",
    "Akon Lonely",
    "Akon Smack That ft Eminem",
    "Akon Right Now Na Na Na",
    "T-Pain Buy U A Drank",
    "T-Pain Bartender",
    "Flo Rida Low",
    "Flo Rida Right Round",
    "Flo Rida Good Feeling",
    "Flo Rida Whistle",
    "Chris Brown Run It",
    "Chris Brown With You",
    "Chris Brown Forever",
    "Ne-Yo So Sick",
    "Ne-Yo Miss Independent",
    "Ne-Yo Closer",
    "Mario Let Me Love You",
    "Ciara 1 2 Step ft Missy Elliott",
    "Ciara Goodies ft Petey Pablo",
    "Ciara Promise",
    # EDM / DANCE EXPANSION
    "Calvin Harris Feel So Close",
    "Calvin Harris Sweet Nothing ft Florence Welch",
    "Calvin Harris Acceptable In The 80s",
    "Calvin Harris I Need Your Love ft Ellie Goulding",
    "David Guetta Titanium ft Sia",
    "David Guetta Without You ft Usher",
    "David Guetta Sexy Bitch ft Akon",
    "David Guetta When Love Takes Over ft Kelly Rowland",
    "Deadmau5 Strobe",
    "Deadmau5 Ghosts N Stuff",
    "Deadmau5 I Remember",
    "Skrillex Scary Monsters And Nice Sprites",
    "Skrillex Bangarang",
    "Skrillex Cinema Remix",
    "Zedd Clarity ft Foxes",
    "Zedd Stay ft Alessia Cara",
    "Zedd The Middle ft Maren Morris",
    "Zedd Beautiful Now",
    "Kygo Firestone",
    "Kygo Stole The Show",
    "Kygo It Aint Me ft Selena Gomez",
    "Kygo Higher Love ft Whitney Houston",
    "Martin Garrix Animals",
    "Martin Garrix In The Name Of Love",
    "Martin Garrix Scared To Be Lonely",
    "Marshmello Happier ft Bastille",
    "Marshmello Alone",
    "Marshmello Silence ft Khalid",
    "Tiesto Red Lights",
    "Tiesto Adagio For Strings",
    "Swedish House Mafia Dont You Worry Child",
    "Swedish House Mafia Save The World",
    "Swedish House Mafia Greyhound",
    "Afrojack Take Over Control",
    "DJ Snake Turn Down For What ft Lil Jon",
    "DJ Snake Let Me Love You ft Justin Bieber",
    "DJ Snake Taki Taki ft Selena Gomez",
    "Major Lazer Lean On ft MO DJ Snake",
    "Major Lazer Cold Water ft Justin Bieber",
    "Clean Bandit Rather Be",
    "Clean Bandit Rockabye ft Sean Paul",
    "Clean Bandit Solo ft Demi Lovato",
    "Disclosure Latch ft Sam Smith",
    "Disclosure White Noise",
    "Rudimental Waiting All Night",
    "Rudimental Feel The Love",
    # LATIN EXPANSION
    "Shakira Hips Dont Lie",
    "Shakira Whenever Wherever",
    "Shakira Waka Waka",
    "Shakira She Wolf",
    "Shakira La Tortura ft Alejandro Sanz",
    "Bad Bunny Dakiti ft Jhay Cortez",
    "Bad Bunny Yonaguni",
    "Bad Bunny Callaita",
    "Bad Bunny Vete",
    "Bad Bunny Safaera",
    "J Balvin Mi Gente",
    "J Balvin Ginza",
    "J Balvin Ay Vamos",
    "Maluma Hawai",
    "Maluma Felices Los 4",
    "Maluma Borro Cassette",
    "Ozuna Te Bote Remix",
    "Ozuna Baila Baila Baila",
    "Daddy Yankee Gasolina",
    "Daddy Yankee Despacito ft Luis Fonsi",
    "Daddy Yankee Con Calma",
    "Daddy Yankee Dura",
    "Rauw Alejandro Todo De Ti",
    "Rauw Alejandro Tattoo",
    "Karol G Tusa ft Nicki Minaj",
    "Karol G Bichota",
    "Karol G Provenza",
    "Karol G TQG ft Shakira",
    "Rosalia Malamente",
    "Rosalia Con Altura ft J Balvin",
    "Rosalia Despecha",
    "Nicky Jam El Amante",
    "Nicky Jam X ft J Balvin",
    "Farruko Pepas",
    "Sech Otro Trago ft Darell",
    # K-POP / ASIAN POP EXPANSION
    "BTS Boy With Luv ft Halsey",
    "BTS Fake Love",
    "BTS Spring Day",
    "BTS Blood Sweat Tears",
    "BTS DNA",
    "BTS MIC Drop",
    "BTS ON",
    "BTS Permission To Dance",
    "BTS Butter",
    "BTS Dynamite",
    "BLACKPINK DDU-DU DDU-DU",
    "BLACKPINK Kill This Love",
    "BLACKPINK How You Like That",
    "BLACKPINK Lovesick Girls",
    "BLACKPINK Pink Venom",
    "BLACKPINK Shut Down",
    "TWICE Cheer Up",
    "TWICE TT",
    "TWICE What Is Love",
    "TWICE Fancy",
    "TWICE Feel Special",
    "Stray Kids Gods Menu",
    "Stray Kids Back Door",
    "Stray Kids Thunderous",
    "Stray Kids MANIAC",
    "SEVENTEEN Dont Wanna Cry",
    "SEVENTEEN Very Nice",
    "SEVENTEEN Super",
    "NewJeans Hype Boy",
    "NewJeans Attention",
    "NewJeans Ditto",
    "NewJeans Super Shy",
    "aespa Next Level",
    "aespa Savage",
    "aespa Supernova",
    "IVE LOVE DIVE",
    "IVE After LIKE",
    "IVE Eleven",
    "LE SSERAFIM FEARLESS",
    "LE SSERAFIM ANTIFRAGILE",
    "LE SSERAFIM Perfect Night",
    "ITZY DALLA DALLA",
    "ITZY Wannabe",
    "Red Velvet Psycho",
    "Red Velvet Bad Boy",
    "EXO Love Shot",
    "EXO Monster",
    "EXO Growl",
    "NCT 127 Kick It",
    "Jungkook Seven",
    "Jungkook Standing Next To You",
    "Jimin Like Crazy",
    "Jimin Set Me Free",
    "V Slow Dancing",
    "SUGA Daechwita",
    "PSY Gangnam Style",
    "PSY Gentleman",
    # COUNTRY CROSSOVER
    "Johnny Cash Ring Of Fire",
    "Johnny Cash Folsom Prison Blues",
    "Johnny Cash Hurt",
    "Johnny Cash I Walk The Line",
    "Dolly Parton Jolene",
    "Dolly Parton 9 To 5",
    "Willie Nelson On The Road Again",
    "Willie Nelson Always On My Mind",
    "Kenny Rogers The Gambler",
    "Kenny Rogers Islands In The Stream ft Dolly Parton",
    "John Denver Take Me Home Country Roads",
    "John Denver Rocky Mountain High",
    "Glen Campbell Rhinestone Cowboy",
    "Glen Campbell Wichita Lineman",
    "Garth Brooks Friends In Low Places",
    "Garth Brooks The Dance",
    "Shania Twain Man I Feel Like A Woman",
    "Shania Twain That Dont Impress Me Much",
    "Shania Twain You Are Still The One",
    "Tim McGraw Live Like You Were Dying",
    "Tim McGraw Humble And Kind",
    "Keith Urban Somebody Like You",
    "Carrie Underwood Before He Cheats",
    "Carrie Underwood Jesus Take The Wheel",
    "Luke Bryan Country Girl Shake It For Me",
    "Florida Georgia Line Cruise",
    "Jason Aldean Try That In A Small Town",
    "Kane Brown Heaven",
    "Chris Stapleton Tennessee Whiskey",
    "Chris Stapleton Starting Over",
    # ADDITIONAL ICONIC SONGS (filling to 2000)
    "Bee Gees Stayin Alive",
    "Bee Gees How Deep Is Your Love",
    "Bee Gees Night Fever",
    "Bee Gees More Than A Woman",
    "ABBA Dancing Queen",
    "ABBA Mamma Mia",
    "ABBA Gimme Gimme Gimme",
    "ABBA The Winner Takes It All",
    "ABBA Waterloo",
    "ABBA Fernando",
    "ABBA SOS",
    "ABBA Voulez-Vous",
    "Simon And Garfunkel The Sound Of Silence",
    "Simon And Garfunkel Bridge Over Troubled Water",
    "Simon And Garfunkel Mrs Robinson",
    "The Beach Boys God Only Knows",
    "The Beach Boys Good Vibrations",
    "The Beach Boys Surfin USA",
    "The Beach Boys Kokomo",
    "Commodores Easy",
    "Commodores Brick House",
    "Jackson 5 I Want You Back",
    "Jackson 5 ABC",
    "Jackson 5 I'll Be There",
    "The Supremes You Cant Hurry Love",
    "The Supremes Stop In The Name Of Love",
    "The Supremes Baby Love",
    "Four Tops I Cant Help Myself",
    "The Isley Brothers Shout",
    "The Isley Brothers Its Your Thing",
    "Donna Summer Hot Stuff",
    "Donna Summer I Feel Love",
    "Donna Summer Last Dance",
    "Gloria Gaynor I Will Survive",
    "Village People YMCA",
    "Village People Macho Man",
    "Sister Sledge We Are Family",
    "Chic Le Freak",
    "Chic Good Times",
    "KC And The Sunshine Band Get Down Tonight",
    "KC And The Sunshine Band Thats The Way I Like It",
    "Lipps Inc Funkytown",
    "Nena 99 Luftballons",
    "Eurythmics Sweet Dreams Are Made Of This",
    "Eurythmics Here Comes The Rain Again",
    "The Human League Dont You Want Me",
    "Frankie Goes To Hollywood Relax",
    "A-ha Take On Me",
    "Bonnie Tyler Total Eclipse Of The Heart",
    "Foreigner I Want To Know What Love Is",
    "Foreigner Waiting For A Girl Like You",
    "Survivor Eye Of The Tiger",
    "REO Speedwagon Cant Fight This Feeling",
    "REO Speedwagon Keep On Loving You",
    "Journey Dont Stop Believin",
    "Journey Faithfully",
    "Journey Open Arms",
    "Journey Separate Ways",
    "Boston More Than A Feeling",
    "Boston Peace Of Mind",
    "Styx Come Sail Away",
    "Styx Mr Roboto",
    "Kansas Carry On Wayward Son",
    "Kansas Dust In The Wind",
    "Toto Africa",
    "Toto Rosanna",
    "Toto Hold The Line",
    "Def Leppard Pour Some Sugar On Me",
    "Def Leppard Hysteria",
    "Def Leppard Photograph",
    "Van Halen Jump",
    "Van Halen Panama",
    "Van Halen Hot For Teacher",
    "Van Halen Eruption",
    "Bon Jovi Livin On A Prayer",
    "Bon Jovi Its My Life",
    "Bon Jovi Wanted Dead Or Alive",
    "Bon Jovi You Give Love A Bad Name",
    "Bon Jovi Bed Of Roses",
    "Guns N Roses Welcome To The Jungle",
    "Guns N Roses Sweet Child O Mine",
    "Guns N Roses Paradise City",
    "Guns N Roses November Rain",
    "Guns N Roses Patience",
    "Metallica Enter Sandman",
    "Metallica Nothing Else Matters",
    "Metallica Master Of Puppets",
    "Metallica One",
    "Metallica Fade To Black",
    "Metallica For Whom The Bell Tolls",
    "Metallica The Unforgiven",
    "Iron Maiden The Trooper",
    "Iron Maiden Fear Of The Dark",
    "Iron Maiden Run To The Hills",
    "Iron Maiden Hallowed Be Thy Name",
    "Iron Maiden Aces High",
    "Black Sabbath Paranoid",
    "Black Sabbath Iron Man",
    "Black Sabbath War Pigs",
    "Ozzy Osbourne Crazy Train",
    "Ozzy Osbourne Mr Crowley",
    "Motorhead Ace Of Spades",
    "Judas Priest Breaking The Law",
    "Judas Priest Painkiller",
    "Scorpions Rock You Like A Hurricane",
    "Scorpions Wind Of Change",
    "Scorpions Still Loving You",
    "Deep Purple Smoke On The Water",
    "Deep Purple Highway Star",
    "Deep Purple Child In Time",
    "Whitesnake Here I Go Again",
    "Whitesnake Is This Love",
    "Aerosmith Dream On",
    "Aerosmith Walk This Way",
    "Aerosmith I Dont Want To Miss A Thing",
    "Aerosmith Crazy",
    "Aerosmith Livin On The Edge",
    "ZZ Top La Grange",
    "ZZ Top Sharp Dressed Man",
    "Lynyrd Skynyrd Free Bird",
    "Tom Petty Free Fallin",
    "Tom Petty American Girl",
    "Tom Petty Running Down A Dream",
    "Bruce Springsteen Born To Run",
    "Bruce Springsteen Dancing In The Dark",
    "Bruce Springsteen Born In The USA",
    "Bruce Springsteen Thunder Road",
    "John Mellencamp Jack And Diane",
    "John Mellencamp Small Town",
    "Bryan Adams Summer Of 69",
    "Bryan Adams Everything I Do I Do It For You",
    "Bryan Adams Run To You",
    "Dire Straits Tunnel Of Love",
    "Mark Knopfler Going Home Theme Of The Local Hero",
    # MORE 2010s-2020s HITS
    "Gotye Somebody That I Used To Know",
    "Lorde Royals",
    "Lorde Green Light",
    "Lorde Team",
    "Hozier Take Me To Church",
    "Vance Joy Riptide",
    "Bastille Pompeii",
    "Bastille Happier ft Marshmello",
    "OneRepublic Counting Stars",
    "OneRepublic Apologize",
    "OneRepublic Stop And Stare",
    "OneRepublic Secrets",
    "Imagine Dragons Believer",
    "Imagine Dragons Thunder",
    "Imagine Dragons Whatever It Takes",
    "Imagine Dragons Natural",
    "Imagine Dragons Demons",
    "Imagine Dragons On Top Of The World",
    "Twenty One Pilots Stressed Out",
    "Twenty One Pilots Heathens",
    "Twenty One Pilots Ride",
    "Twenty One Pilots Tear In My Heart",
    "Fall Out Boy Sugar Were Goin Down",
    "Fall Out Boy Thnks fr th Mmrs",
    "Fall Out Boy Centuries",
    "Fall Out Boy My Songs Know What You Did In The Dark",
    "Panic At The Disco I Write Sins Not Tragedies",
    "Panic At The Disco High Hopes",
    "Panic At The Disco Victorious",
    "Paramore Misery Business",
    "Paramore Decode",
    "Paramore Still Into You",
    "Paramore Aint It Fun",
    "Green Day Boulevard Of Broken Dreams",
    "Green Day American Idiot",
    "Green Day 21 Guns",
    "Green Day Basket Case",
    "Green Day Wake Me Up When September Ends",
    "Blink-182 All The Small Things",
    "Blink-182 I Miss You",
    "Blink-182 Whats My Age Again",
    "Blink-182 Dammit",
    "Sum 41 Fat Lip",
    "Sum 41 In Too Deep",
    "Good Charlotte Lifestyles Of The Rich And Famous",
    "The Offspring Self Esteem",
    "The Offspring Pretty Fly For A White Guy",
    "The Offspring Come Out And Play",
    "Jimmy Eat World The Middle",
    "Dashboard Confessional Screaming Infidelities",
    "Taking Back Sunday MakeDamnSure",
    "Weezer Buddy Holly",
    "Weezer Say It Aint So",
    "Weezer Beverly Hills",
    "Weezer Island In The Sun",
    "Red Hot Chili Peppers Under The Bridge",
    "Red Hot Chili Peppers Californication",
    "Red Hot Chili Peppers Can't Stop",
    "Red Hot Chili Peppers Otherside",
    "Red Hot Chili Peppers Scar Tissue",
    "Red Hot Chili Peppers Snow Hey Oh",
    "Red Hot Chili Peppers By The Way",
    "Red Hot Chili Peppers Dani California",
    "Foo Fighters Everlong",
    "Foo Fighters The Pretender",
    "Foo Fighters Learn To Fly",
    "Foo Fighters Best Of You",
    "Foo Fighters My Hero",
    "Foo Fighters Times Like These",
    "Muse Supermassive Black Hole",
    "Muse Hysteria",
    "Muse Starlight",
    "Muse Uprising",
    "Muse Time Is Running Out",
    "Muse Knights Of Cydonia",
    "Muse Madness",
    "Arctic Monkeys Do I Wanna Know",
    "Arctic Monkeys R U Mine",
    "Arctic Monkeys 505",
    "Arctic Monkeys I Bet You Look Good On The Dancefloor",
    "Arctic Monkeys Fluorescent Adolescent",
    "Arctic Monkeys Why'd You Only Call Me When You're High",
    "Oasis Wonderwall",
    "Oasis Dont Look Back In Anger",
    "Oasis Champagne Supernova",
    "Oasis Live Forever",
    "Oasis Stop Crying Your Heart Out",
    "Blur Song 2",
    "Blur Coffee And TV",
    "Blur Parklife",
    "Pulp Common People",
    "Radiohead Creep",
    "Radiohead Karma Police",
    "Radiohead Paranoid Android",
    "Radiohead Everything In Its Right Place",
    "Radiohead Fake Plastic Trees",
    "Radiohead Exit Music For A Film",
    "Coldplay Yellow",
    "Coldplay The Scientist",
    "Coldplay Clocks",
    "Coldplay Fix You",
    "Coldplay Viva La Vida",
    "Coldplay Paradise",
    "Coldplay A Sky Full Of Stars",
    "Coldplay Something Just Like This ft Chainsmokers",
    "Coldplay Adventure Of A Lifetime",
    "U2 One",
    "U2 With Or Without You",
    "U2 Where The Streets Have No Name",
    "U2 Beautiful Day",
    "U2 Sunday Bloody Sunday",
    "U2 I Still Havent Found What Im Looking For",
    "R.E.M. Losing My Religion",
    "R.E.M. Everybody Hurts",
    "R.E.M. Its The End Of The World As We Know It",
    "R.E.M. Man On The Moon",
    "Nirvana Smells Like Teen Spirit",
    "Nirvana Come As You Are",
    "Nirvana Lithium",
    "Nirvana In Bloom",
    "Nirvana Heart-Shaped Box",
    "Nirvana All Apologies",
    "Nine Inch Nails Closer",
    "Nine Inch Nails Head Like A Hole",
    "Nine Inch Nails Hurt",
    "Smashing Pumpkins 1979",
    "Smashing Pumpkins Tonight Tonight",
    "Smashing Pumpkins Bullet With Butterfly Wings",
    "Smashing Pumpkins Today",
    "The White Stripes Seven Nation Army",
    "The White Stripes Icky Thump",
    "The Strokes Last Nite",
    "The Strokes Reptilia",
    "The Strokes Someday",
    "Franz Ferdinand Take Me Out",
    "The Killers Mr Brightside",
    "The Killers Somebody Told Me",
    "The Killers Human",
    "The Killers When You Were Young",
    "Kings Of Leon Sex On Fire",
    "Kings Of Leon Use Somebody",
    "Snow Patrol Chasing Cars",
    "Snow Patrol Run",
    "The Script Hall Of Fame ft will.i.am",
    "The Script Breakeven",
    "James Blunt You Are Beautiful",
    "Gorillaz Feel Good Inc",
    "Gorillaz Clint Eastwood",
    "Gorillaz DARE",
    "Gorillaz On Melancholy Hill",
    # AFROBEATS / WORLD MUSIC
    "Burna Boy Last Last",
    "Burna Boy Ye",
    "Burna Boy On The Low",
    "Burna Boy Anybody",
    "Burna Boy City Boys",
    "Wizkid Essence ft Tems",
    "Wizkid Come Closer ft Drake",
    "Wizkid Ojuelegba",
    "Wizkid Joro",
    "Davido Fall",
    "Davido If",
    "Davido FIA",
    "Rema Calm Down",
    "Rema Soundgasm",
    "CKay Love Nwantiti",
    "Tems Free Mind",
    "Tems Higher",
    "Omah Lay Understand",
    "Asake Joha",
    "Fireboy DML Peru",
    "Tiwa Savage Somebody Son",
    "Tiwa Savage All Over",
    "Yemi Alade Johnny",
    "Mr Eazi Skin Tight",
    "Patoranking Girlie O",
    "Aya Nakamura Djadja",
    "Stromae Alors On Danse",
    "Stromae Papaoutai",
    "Stromae Formidable",
    "Angele Tout Oublier",
]

# Add only truly new songs
added = 0
for s in new_songs:
    key = s.strip().lower()
    if key not in seen:
        seen.add(key)
        unique.append(s.strip())
        added += 1

print(f"Added {added} new unique songs")
print(f"Total unique now: {len(unique)}")
print(f"Need {2000 - len(unique)} more to reach 2000")

# Write the final file
lines = ['"""Lista de 2000 musicas internacionais mais famosas para o comando t!r / t!random."""\n\n']
lines.append('RANDOM_SONGS: list[str] = [\n')
for i, s in enumerate(unique):
    lines.append(f'    "ytsearch1:{s}",\n')
lines.append(']\n')

with open('random_songs.py', 'w', encoding='utf-8') as f:
    f.writelines(lines)

print(f"Wrote random_songs.py with {len(unique)} songs")
