"""Lista de 1000 musicas internacionais mais famosas para o comando t$r / t$random."""

RANDOM_SONGS: list[str] = [
    # ======================================================================
    # === MOST STREAMED / VIRAL (1-55) ===
    # ======================================================================
    "ytsearch1:The Weeknd Blinding Lights",
    "ytsearch1:The Weeknd Starboy",
    "ytsearch1:The Weeknd Save Your Tears",
    "ytsearch1:The Weeknd Die For You",
    "ytsearch1:The Weeknd I Feel It Coming ft Daft Punk",
    "ytsearch1:The Weeknd After Hours",
    "ytsearch1:The Weeknd Can't Feel My Face",
    "ytsearch1:The Weeknd The Hills",
    "ytsearch1:Ed Sheeran Shape Of You",
    "ytsearch1:Ed Sheeran Perfect",
    "ytsearch1:Ed Sheeran Thinking Out Loud",
    "ytsearch1:Ed Sheeran Bad Habits",
    "ytsearch1:Ed Sheeran Photograph",
    "ytsearch1:Ed Sheeran Castle On The Hill",
    "ytsearch1:Lewis Capaldi Someone You Loved",
    "ytsearch1:Lewis Capaldi Before You Go",
    "ytsearch1:Tones And I Dance Monkey",
    "ytsearch1:Post Malone Circles",
    "ytsearch1:Post Malone Sunflower",
    "ytsearch1:Post Malone Rockstar ft 21 Savage",
    "ytsearch1:Post Malone Congratulations",
    "ytsearch1:Post Malone Better Now",
    "ytsearch1:Post Malone I Like You ft Doja Cat",
    "ytsearch1:Dua Lipa Levitating",
    "ytsearch1:Dua Lipa Don't Start Now",
    "ytsearch1:Dua Lipa New Rules",
    "ytsearch1:Dua Lipa Physical",
    "ytsearch1:Dua Lipa Training Season",
    "ytsearch1:Harry Styles As It Was",
    "ytsearch1:Harry Styles Watermelon Sugar",
    "ytsearch1:Harry Styles Sign Of The Times",
    "ytsearch1:Harry Styles Adore You",
    "ytsearch1:Olivia Rodrigo drivers license",
    "ytsearch1:Olivia Rodrigo good 4 u",
    "ytsearch1:Olivia Rodrigo vampire",
    "ytsearch1:Olivia Rodrigo deja vu",
    "ytsearch1:Billie Eilish bad guy",
    "ytsearch1:Billie Eilish Lovely ft Khalid",
    "ytsearch1:Billie Eilish Happier Than Ever",
    "ytsearch1:Billie Eilish Birds Of A Feather",
    "ytsearch1:Billie Eilish Ocean Eyes",
    "ytsearch1:Billie Eilish everything i wanted",
    "ytsearch1:Glass Animals Heat Waves",
    "ytsearch1:Lil Nas X Old Town Road",
    "ytsearch1:Lil Nas X MONTERO",
    "ytsearch1:Lil Nas X Industry Baby ft Jack Harlow",
    "ytsearch1:Miley Cyrus Flowers",
    "ytsearch1:Miley Cyrus Wrecking Ball",
    "ytsearch1:Miley Cyrus Midnight Sky",
    "ytsearch1:Sam Smith Unholy ft Kim Petras",
    "ytsearch1:Sam Smith Stay With Me",
    "ytsearch1:Sam Smith Too Good At Goodbyes",
    "ytsearch1:Lizzo About Damn Time",
    "ytsearch1:Lizzo Truth Hurts",
    "ytsearch1:Lizzo Good As Hell",
    # ======================================================================
    # === ARIANA GRANDE (56-65) ===
    # ======================================================================
    "ytsearch1:Ariana Grande 7 rings",
    "ytsearch1:Ariana Grande thank u next",
    "ytsearch1:Ariana Grande positions",
    "ytsearch1:Ariana Grande no tears left to cry",
    "ytsearch1:Ariana Grande Into You",
    "ytsearch1:Ariana Grande Problem ft Iggy Azalea",
    "ytsearch1:Ariana Grande Break Free ft Zedd",
    "ytsearch1:Ariana Grande Side To Side ft Nicki Minaj",
    "ytsearch1:Ariana Grande One Last Time",
    "ytsearch1:Ariana Grande God Is A Woman",
    # ======================================================================
    # === JUSTIN BIEBER (66-75) ===
    # ======================================================================
    "ytsearch1:Justin Bieber Peaches",
    "ytsearch1:Justin Bieber Stay ft Kid LAROI",
    "ytsearch1:Justin Bieber Sorry",
    "ytsearch1:Justin Bieber Love Yourself",
    "ytsearch1:Justin Bieber What Do You Mean",
    "ytsearch1:Justin Bieber Baby ft Ludacris",
    "ytsearch1:Justin Bieber Boyfriend",
    "ytsearch1:Justin Bieber Ghost",
    "ytsearch1:Justin Bieber Company",
    "ytsearch1:Justin Bieber Intentions ft Quavo",
    # ======================================================================
    # === DOJA CAT / SZA (76-87) ===
    # ======================================================================
    "ytsearch1:Doja Cat Say So",
    "ytsearch1:Doja Cat Kiss Me More ft SZA",
    "ytsearch1:Doja Cat Paint The Town Red",
    "ytsearch1:Doja Cat Woman",
    "ytsearch1:Doja Cat Need To Know",
    "ytsearch1:SZA Kill Bill",
    "ytsearch1:SZA Snooze",
    "ytsearch1:SZA Good Days",
    "ytsearch1:SZA Kiss Me More ft Doja Cat",
    "ytsearch1:SZA Love Galore ft Travis Scott",
    "ytsearch1:SZA The Weekend",
    "ytsearch1:SZA Shirt",
    # ======================================================================
    # === DRAKE (88-100) ===
    # ======================================================================
    "ytsearch1:Drake One Dance",
    "ytsearch1:Drake God's Plan",
    "ytsearch1:Drake Hotline Bling",
    "ytsearch1:Drake In My Feelings",
    "ytsearch1:Drake Nice For What",
    "ytsearch1:Drake Passionfruit",
    "ytsearch1:Drake Started From The Bottom",
    "ytsearch1:Drake Hold On We're Going Home",
    "ytsearch1:Drake Take Care ft Rihanna",
    "ytsearch1:Drake Best I Ever Had",
    "ytsearch1:Drake Headlines",
    "ytsearch1:Drake Laugh Now Cry Later ft Lil Durk",
    "ytsearch1:Drake Toosie Slide",
    # ======================================================================
    # === IMAGINE DRAGONS (101-108) ===
    # ======================================================================
    "ytsearch1:Imagine Dragons Believer",
    "ytsearch1:Imagine Dragons Radioactive",
    "ytsearch1:Imagine Dragons Demons",
    "ytsearch1:Imagine Dragons Thunder",
    "ytsearch1:Imagine Dragons Whatever It Takes",
    "ytsearch1:Imagine Dragons Bones",
    "ytsearch1:Imagine Dragons Natural",
    "ytsearch1:Imagine Dragons Enemy",
    # ======================================================================
    # === BRUNO MARS (109-120) ===
    # ======================================================================
    "ytsearch1:Bruno Mars Uptown Funk",
    "ytsearch1:Bruno Mars 24K Magic",
    "ytsearch1:Bruno Mars That's What I Like",
    "ytsearch1:Bruno Mars Grenade",
    "ytsearch1:Bruno Mars Locked Out Of Heaven",
    "ytsearch1:Bruno Mars When I Was Your Man",
    "ytsearch1:Bruno Mars Just The Way You Are",
    "ytsearch1:Bruno Mars The Lazy Song",
    "ytsearch1:Bruno Mars Treasure",
    "ytsearch1:Bruno Mars Count On Me",
    "ytsearch1:Bruno Mars Versace On The Floor",
    "ytsearch1:Bruno Mars Leave The Door Open ft Silk Sonic",
    # ======================================================================
    # === POP MEGA HITS (121-175) ===
    # ======================================================================
    "ytsearch1:Pharrell Williams Happy",
    "ytsearch1:Luis Fonsi Despacito ft Daddy Yankee",
    "ytsearch1:PSY Gangnam Style",
    "ytsearch1:Shakira Waka Waka",
    "ytsearch1:Shakira Hips Don't Lie",
    "ytsearch1:Shakira Whenever Wherever",
    "ytsearch1:Rihanna Umbrella",
    "ytsearch1:Rihanna We Found Love ft Calvin Harris",
    "ytsearch1:Rihanna Diamonds",
    "ytsearch1:Rihanna Stay",
    "ytsearch1:Rihanna Only Girl In The World",
    "ytsearch1:Rihanna Don't Stop The Music",
    "ytsearch1:Rihanna Disturbia",
    "ytsearch1:Rihanna Work ft Drake",
    "ytsearch1:Lady Gaga Bad Romance",
    "ytsearch1:Lady Gaga Poker Face",
    "ytsearch1:Lady Gaga Shallow ft Bradley Cooper",
    "ytsearch1:Lady Gaga Born This Way",
    "ytsearch1:Lady Gaga Just Dance",
    "ytsearch1:Lady Gaga Alejandro",
    "ytsearch1:Lady Gaga Die With A Smile ft Bruno Mars",
    "ytsearch1:Beyonce Crazy In Love",
    "ytsearch1:Beyonce Single Ladies",
    "ytsearch1:Beyonce Halo",
    "ytsearch1:Beyonce Love On Top",
    "ytsearch1:Beyonce Drunk In Love ft Jay-Z",
    "ytsearch1:Beyonce Irreplaceable",
    "ytsearch1:Beyonce Formation",
    "ytsearch1:Adele Rolling In The Deep",
    "ytsearch1:Adele Someone Like You",
    "ytsearch1:Adele Hello",
    "ytsearch1:Adele Easy On Me",
    "ytsearch1:Adele Set Fire To The Rain",
    "ytsearch1:Adele Skyfall",
    "ytsearch1:Taylor Swift Shake It Off",
    "ytsearch1:Taylor Swift Anti-Hero",
    "ytsearch1:Taylor Swift Blank Space",
    "ytsearch1:Taylor Swift Love Story",
    "ytsearch1:Taylor Swift Cruel Summer",
    "ytsearch1:Taylor Swift Style",
    "ytsearch1:Taylor Swift Wildest Dreams",
    "ytsearch1:Taylor Swift You Belong With Me",
    "ytsearch1:Taylor Swift Bad Blood",
    "ytsearch1:Taylor Swift We Are Never Getting Back Together",
    "ytsearch1:Taylor Swift Delicate",
    "ytsearch1:Katy Perry Roar",
    "ytsearch1:Katy Perry Firework",
    "ytsearch1:Katy Perry Dark Horse",
    "ytsearch1:Katy Perry Teenage Dream",
    "ytsearch1:Katy Perry California Gurls",
    "ytsearch1:Katy Perry Last Friday Night",
    "ytsearch1:Katy Perry Hot N Cold",
    "ytsearch1:Sia Cheap Thrills",
    "ytsearch1:Sia Chandelier",
    "ytsearch1:Sia Elastic Heart",
    # ======================================================================
    # === POP HITS 2010s (176-235) ===
    # ======================================================================
    "ytsearch1:The Chainsmokers Closer ft Halsey",
    "ytsearch1:The Chainsmokers Don't Let Me Down",
    "ytsearch1:The Chainsmokers Roses ft Rozes",
    "ytsearch1:The Chainsmokers Paris",
    "ytsearch1:Maroon 5 Sugar",
    "ytsearch1:Maroon 5 Girls Like You ft Cardi B",
    "ytsearch1:Maroon 5 Payphone",
    "ytsearch1:Maroon 5 Maps",
    "ytsearch1:Maroon 5 Moves Like Jagger",
    "ytsearch1:Maroon 5 She Will Be Loved",
    "ytsearch1:Maroon 5 Memories",
    "ytsearch1:Charlie Puth Attention",
    "ytsearch1:Charlie Puth We Don't Talk Anymore",
    "ytsearch1:Charlie Puth One Call Away",
    "ytsearch1:Shawn Mendes Senorita ft Camila Cabello",
    "ytsearch1:Shawn Mendes Stitches",
    "ytsearch1:Shawn Mendes There's Nothing Holdin Me Back",
    "ytsearch1:Shawn Mendes Treat You Better",
    "ytsearch1:Shawn Mendes In My Blood",
    "ytsearch1:Calvin Harris Summer",
    "ytsearch1:Calvin Harris This Is What You Came For ft Rihanna",
    "ytsearch1:Calvin Harris Feel So Close",
    "ytsearch1:Calvin Harris How Deep Is Your Love",
    "ytsearch1:David Guetta Titanium ft Sia",
    "ytsearch1:David Guetta Without You ft Usher",
    "ytsearch1:David Guetta Hey Mama ft Nicki Minaj",
    "ytsearch1:Clean Bandit Rockabye",
    "ytsearch1:Clean Bandit Rather Be",
    "ytsearch1:Clean Bandit Solo ft Demi Lovato",
    "ytsearch1:OneRepublic Counting Stars",
    "ytsearch1:OneRepublic Apologize",
    "ytsearch1:OneRepublic Secrets",
    "ytsearch1:Fun We Are Young",
    "ytsearch1:Gotye Somebody That I Used To Know",
    "ytsearch1:Meghan Trainor All About That Bass",
    "ytsearch1:John Legend All Of Me",
    "ytsearch1:Ellie Goulding Love Me Like You Do",
    "ytsearch1:Ellie Goulding Burn",
    "ytsearch1:Ellie Goulding Lights",
    "ytsearch1:Jason Derulo Talk Dirty",
    "ytsearch1:Jason Derulo Whatcha Say",
    "ytsearch1:Jason Derulo Savage Love",
    "ytsearch1:Pitbull Timber ft Kesha",
    "ytsearch1:Pitbull Give Me Everything ft Ne-Yo",
    "ytsearch1:Wiz Khalifa See You Again ft Charlie Puth",
    "ytsearch1:Carly Rae Jepsen Call Me Maybe",
    "ytsearch1:Demi Lovato Sorry Not Sorry",
    "ytsearch1:Demi Lovato Cool For The Summer",
    "ytsearch1:Selena Gomez Lose You To Love Me",
    "ytsearch1:Selena Gomez Come And Get It",
    "ytsearch1:Selena Gomez Good For You",
    "ytsearch1:Selena Gomez Hands To Myself",
    "ytsearch1:Camila Cabello Havana",
    "ytsearch1:Camila Cabello Never Be The Same",
    "ytsearch1:Halsey Without Me",
    "ytsearch1:Halsey Bad At Love",
    "ytsearch1:Halsey Graveyard",
    "ytsearch1:Lorde Royals",
    "ytsearch1:Lorde Green Light",
    "ytsearch1:Lorde Team",
    # ======================================================================
    # === RAP / HIP-HOP (236-310) ===
    # ======================================================================
    "ytsearch1:Eminem Lose Yourself",
    "ytsearch1:Eminem Without Me",
    "ytsearch1:Eminem The Real Slim Shady",
    "ytsearch1:Eminem Rap God",
    "ytsearch1:Eminem Mockingbird",
    "ytsearch1:Eminem Not Afraid",
    "ytsearch1:Eminem Love The Way You Lie ft Rihanna",
    "ytsearch1:Eminem Stan ft Dido",
    "ytsearch1:Eminem Godzilla ft Juice WRLD",
    "ytsearch1:Kendrick Lamar HUMBLE",
    "ytsearch1:Kendrick Lamar Not Like Us",
    "ytsearch1:Kendrick Lamar Swimming Pools",
    "ytsearch1:Kendrick Lamar DNA",
    "ytsearch1:Kendrick Lamar LOYALTY ft Rihanna",
    "ytsearch1:Kendrick Lamar Money Trees",
    "ytsearch1:Kendrick Lamar TV Off ft Lefty Gunplay",
    "ytsearch1:Travis Scott SICKO MODE",
    "ytsearch1:Travis Scott goosebumps",
    "ytsearch1:Travis Scott HIGHEST IN THE ROOM",
    "ytsearch1:Travis Scott BUTTERFLY EFFECT",
    "ytsearch1:Travis Scott Antidote",
    "ytsearch1:Travis Scott FE!N ft Playboi Carti",
    "ytsearch1:Kanye West Stronger",
    "ytsearch1:Kanye West Gold Digger",
    "ytsearch1:Kanye West Heartless",
    "ytsearch1:Kanye West Runaway",
    "ytsearch1:Kanye West Power",
    "ytsearch1:Kanye West All Of The Lights",
    "ytsearch1:Kanye West Flashing Lights",
    "ytsearch1:Kanye West Bound 2",
    "ytsearch1:Dr Dre Still D.R.E. ft Snoop Dogg",
    "ytsearch1:Dr Dre The Next Episode ft Snoop Dogg",
    "ytsearch1:Dr Dre Forgot About Dre",
    "ytsearch1:50 Cent In Da Club",
    "ytsearch1:50 Cent Candy Shop",
    "ytsearch1:50 Cent 21 Questions",
    "ytsearch1:Jay-Z Empire State Of Mind",
    "ytsearch1:Jay-Z 99 Problems",
    "ytsearch1:Jay-Z Run This Town ft Rihanna",
    "ytsearch1:Juice WRLD Lucid Dreams",
    "ytsearch1:Juice WRLD Robbery",
    "ytsearch1:Juice WRLD All Girls Are The Same",
    "ytsearch1:Juice WRLD Wishing Well",
    "ytsearch1:XXXTENTACION Moonlight",
    "ytsearch1:XXXTENTACION SAD",
    "ytsearch1:XXXTENTACION Jocelyn Flores",
    "ytsearch1:XXXTENTACION changes",
    "ytsearch1:Mac Miller Self Care",
    "ytsearch1:Mac Miller Good News",
    "ytsearch1:Cardi B Bodak Yellow",
    "ytsearch1:Cardi B I Like It",
    "ytsearch1:Cardi B WAP ft Megan Thee Stallion",
    "ytsearch1:Megan Thee Stallion Savage",
    "ytsearch1:Megan Thee Stallion Body",
    "ytsearch1:Nicki Minaj Super Bass",
    "ytsearch1:Nicki Minaj Starships",
    "ytsearch1:Nicki Minaj Anaconda",
    "ytsearch1:Nicki Minaj Bang Bang ft Jessie J Ariana Grande",
    "ytsearch1:Tyler The Creator See You Again",
    "ytsearch1:Tyler The Creator EARFQUAKE",
    "ytsearch1:Tyler The Creator NEW MAGIC WAND",
    "ytsearch1:A$AP Rocky Praise The Lord",
    "ytsearch1:A$AP Rocky L$D",
    "ytsearch1:Lil Uzi Vert XO Tour Llif3",
    "ytsearch1:Lil Uzi Vert Just Wanna Rock",
    "ytsearch1:21 Savage A Lot",
    "ytsearch1:21 Savage Bank Account",
    "ytsearch1:J Cole No Role Modelz",
    "ytsearch1:J Cole Middle Child",
    "ytsearch1:J Cole Love Yourz",
    "ytsearch1:Future Mask Off",
    "ytsearch1:Future Life Is Good ft Drake",
    "ytsearch1:Lil Baby Drip Too Hard ft Gunna",
    "ytsearch1:Lil Baby Emotionally Scarred",
    "ytsearch1:Jack Harlow First Class",
    # ======================================================================
    # === ROCK CLASSICS (311-400) ===
    # ======================================================================
    "ytsearch1:Queen Bohemian Rhapsody",
    "ytsearch1:Queen Don't Stop Me Now",
    "ytsearch1:Queen We Will Rock You",
    "ytsearch1:Queen Somebody To Love",
    "ytsearch1:Queen We Are The Champions",
    "ytsearch1:Queen Under Pressure ft David Bowie",
    "ytsearch1:Queen Another One Bites The Dust",
    "ytsearch1:Queen Radio Ga Ga",
    "ytsearch1:Nirvana Smells Like Teen Spirit",
    "ytsearch1:Nirvana Come As You Are",
    "ytsearch1:Nirvana Lithium",
    "ytsearch1:Nirvana In Bloom",
    "ytsearch1:Nirvana Heart-Shaped Box",
    "ytsearch1:Guns N Roses Sweet Child O Mine",
    "ytsearch1:Guns N Roses Welcome To The Jungle",
    "ytsearch1:Guns N Roses Paradise City",
    "ytsearch1:Guns N Roses November Rain",
    "ytsearch1:AC/DC Back In Black",
    "ytsearch1:AC/DC Thunderstruck",
    "ytsearch1:AC/DC Highway To Hell",
    "ytsearch1:AC/DC T.N.T.",
    "ytsearch1:AC/DC You Shook Me All Night Long",
    "ytsearch1:Linkin Park In The End",
    "ytsearch1:Linkin Park Numb",
    "ytsearch1:Linkin Park Crawling",
    "ytsearch1:Linkin Park What I've Done",
    "ytsearch1:Linkin Park Faint",
    "ytsearch1:Linkin Park Breaking The Habit",
    "ytsearch1:Linkin Park One More Light",
    "ytsearch1:Metallica Enter Sandman",
    "ytsearch1:Metallica Nothing Else Matters",
    "ytsearch1:Metallica Master Of Puppets",
    "ytsearch1:Metallica One",
    "ytsearch1:Metallica The Unforgiven",
    "ytsearch1:Arctic Monkeys Do I Wanna Know",
    "ytsearch1:Arctic Monkeys R U Mine",
    "ytsearch1:Arctic Monkeys 505",
    "ytsearch1:Arctic Monkeys Why'd You Only Call Me When You're High",
    "ytsearch1:Arctic Monkeys I Bet You Look Good On The Dancefloor",
    "ytsearch1:Gorillaz Feel Good Inc",
    "ytsearch1:Gorillaz Clint Eastwood",
    "ytsearch1:Gorillaz On Melancholy Hill",
    "ytsearch1:Coldplay Viva La Vida",
    "ytsearch1:Coldplay The Scientist",
    "ytsearch1:Coldplay Yellow",
    "ytsearch1:Coldplay Fix You",
    "ytsearch1:Coldplay Clocks",
    "ytsearch1:Coldplay Paradise",
    "ytsearch1:Coldplay A Sky Full Of Stars",
    "ytsearch1:Coldplay Something Just Like This ft Chainsmokers",
    "ytsearch1:Coldplay Hymn For The Weekend",
    "ytsearch1:Oasis Wonderwall",
    "ytsearch1:Oasis Don't Look Back In Anger",
    "ytsearch1:Oasis Champagne Supernova",
    "ytsearch1:Oasis Live Forever",
    "ytsearch1:The Killers Mr Brightside",
    "ytsearch1:The Killers Human",
    "ytsearch1:The Killers Somebody Told Me",
    "ytsearch1:Bon Jovi Livin On A Prayer",
    "ytsearch1:Bon Jovi It's My Life",
    "ytsearch1:Bon Jovi You Give Love A Bad Name",
    "ytsearch1:Eagles Hotel California",
    "ytsearch1:Led Zeppelin Stairway To Heaven",
    "ytsearch1:Led Zeppelin Whole Lotta Love",
    "ytsearch1:Led Zeppelin Kashmir",
    "ytsearch1:Pink Floyd Comfortably Numb",
    "ytsearch1:Pink Floyd Another Brick In The Wall",
    "ytsearch1:Pink Floyd Wish You Were Here",
    "ytsearch1:Red Hot Chili Peppers Californication",
    "ytsearch1:Red Hot Chili Peppers Can't Stop",
    "ytsearch1:Red Hot Chili Peppers Under The Bridge",
    "ytsearch1:Red Hot Chili Peppers Otherside",
    "ytsearch1:Red Hot Chili Peppers Snow Hey Oh",
    "ytsearch1:Foo Fighters Everlong",
    "ytsearch1:Foo Fighters The Pretender",
    "ytsearch1:Foo Fighters Best Of You",
    "ytsearch1:Foo Fighters Learn To Fly",
    "ytsearch1:System Of A Down Chop Suey",
    "ytsearch1:System Of A Down Toxicity",
    "ytsearch1:System Of A Down B.Y.O.B.",
    "ytsearch1:Green Day Boulevard Of Broken Dreams",
    "ytsearch1:Green Day American Idiot",
    "ytsearch1:Green Day 21 Guns",
    "ytsearch1:Green Day Basket Case",
    "ytsearch1:Green Day Wake Me Up When September Ends",
    "ytsearch1:Blink 182 All The Small Things",
    "ytsearch1:Blink 182 What's My Age Again",
    "ytsearch1:Blink 182 I Miss You",
    "ytsearch1:My Chemical Romance Welcome To The Black Parade",
    "ytsearch1:My Chemical Romance Helena",
    # ======================================================================
    # === ROCK LEGENDS EXTRA (401-440) ===
    # ======================================================================
    "ytsearch1:Radiohead Creep",
    "ytsearch1:Radiohead Karma Police",
    "ytsearch1:Radiohead No Surprises",
    "ytsearch1:Muse Supermassive Black Hole",
    "ytsearch1:Muse Madness",
    "ytsearch1:Muse Uprising",
    "ytsearch1:Muse Starlight",
    "ytsearch1:Toto Africa",
    "ytsearch1:A-ha Take On Me",
    "ytsearch1:Journey Don't Stop Believin",
    "ytsearch1:Journey Faithfully",
    "ytsearch1:Rick Astley Never Gonna Give You Up",
    "ytsearch1:Dire Straits Sultans Of Swing",
    "ytsearch1:Dire Straits Money For Nothing",
    "ytsearch1:Deep Purple Smoke On The Water",
    "ytsearch1:Deep Purple Highway Star",
    "ytsearch1:The Police Every Breath You Take",
    "ytsearch1:The Police Roxanne",
    "ytsearch1:Stevie Wonder Superstition",
    "ytsearch1:Stevie Wonder Sir Duke",
    "ytsearch1:Stevie Wonder I Just Called To Say I Love You",
    "ytsearch1:Michael Jackson Billie Jean",
    "ytsearch1:Michael Jackson Smooth Criminal",
    "ytsearch1:Michael Jackson Beat It",
    "ytsearch1:Michael Jackson Thriller",
    "ytsearch1:Michael Jackson Man In The Mirror",
    "ytsearch1:Michael Jackson Bad",
    "ytsearch1:Michael Jackson The Way You Make Me Feel",
    "ytsearch1:Michael Jackson Rock With You",
    "ytsearch1:Michael Jackson Don't Stop Til You Get Enough",
    "ytsearch1:Michael Jackson Black Or White",
    "ytsearch1:The Beatles Let It Be",
    "ytsearch1:The Beatles Hey Jude",
    "ytsearch1:The Beatles Come Together",
    "ytsearch1:The Beatles Yesterday",
    "ytsearch1:The Beatles Here Comes The Sun",
    "ytsearch1:The Beatles Twist And Shout",
    "ytsearch1:The Rolling Stones Paint It Black",
    "ytsearch1:The Rolling Stones Satisfaction",
    "ytsearch1:The Rolling Stones Sympathy For The Devil",
    "ytsearch1:David Bowie Heroes",
    # ======================================================================
    # === EDM / ELETRONICA (441-500) ===
    # ======================================================================
    "ytsearch1:Avicii Wake Me Up",
    "ytsearch1:Avicii Levels",
    "ytsearch1:Avicii Waiting For Love",
    "ytsearch1:Avicii The Nights",
    "ytsearch1:Avicii Hey Brother",
    "ytsearch1:Avicii Without You ft Sandro Cavazza",
    "ytsearch1:Martin Garrix Animals",
    "ytsearch1:Martin Garrix In The Name Of Love",
    "ytsearch1:Martin Garrix Scared To Be Lonely ft Dua Lipa",
    "ytsearch1:Martin Garrix Summer Days",
    "ytsearch1:Marshmello Alone",
    "ytsearch1:Marshmello Happier ft Bastille",
    "ytsearch1:Marshmello Silence ft Khalid",
    "ytsearch1:Marshmello Friends ft Anne-Marie",
    "ytsearch1:Daft Punk Get Lucky",
    "ytsearch1:Daft Punk Around The World",
    "ytsearch1:Daft Punk One More Time",
    "ytsearch1:Daft Punk Harder Better Faster Stronger",
    "ytsearch1:Daft Punk Something About Us",
    "ytsearch1:Alan Walker Faded",
    "ytsearch1:Alan Walker Alone",
    "ytsearch1:Alan Walker Darkside",
    "ytsearch1:Alan Walker On My Way",
    "ytsearch1:Kygo Firestone",
    "ytsearch1:Kygo It Ain't Me ft Selena Gomez",
    "ytsearch1:Kygo Stole The Show",
    "ytsearch1:Zedd Clarity ft Foxes",
    "ytsearch1:Zedd The Middle ft Maren Morris",
    "ytsearch1:Zedd Stay ft Alessia Cara",
    "ytsearch1:Zedd Beautiful Now ft Jon Bellion",
    "ytsearch1:Major Lazer Lean On ft DJ Snake",
    "ytsearch1:DJ Snake Taki Taki ft Selena Gomez",
    "ytsearch1:DJ Snake Let Me Love You ft Justin Bieber",
    "ytsearch1:DJ Snake Turn Down For What ft Lil Jon",
    "ytsearch1:Skrillex Bangarang",
    "ytsearch1:Skrillex Scary Monsters And Nice Sprites",
    "ytsearch1:Deadmau5 Ghosts N Stuff",
    "ytsearch1:Deadmau5 Strobe",
    "ytsearch1:Tiesto Red Lights",
    "ytsearch1:Tiesto The Business",
    "ytsearch1:Swedish House Mafia Don't You Worry Child",
    "ytsearch1:Swedish House Mafia Save The World",
    "ytsearch1:Robin Schulz Sugar",
    "ytsearch1:Robin Schulz Prayer In C",
    "ytsearch1:Flume Never Be Like You",
    "ytsearch1:Flume Say It ft Tove Lo",
    "ytsearch1:ILLENIUM Takeaway ft Chainsmokers",
    "ytsearch1:Disclosure Latch ft Sam Smith",
    "ytsearch1:Galantis Runaway U And I",
    "ytsearch1:Galantis No Money",
    "ytsearch1:Alesso Heroes ft Tove Lo",
    "ytsearch1:Diplo Revolution",
    "ytsearch1:R3HAB All Around The World",
    "ytsearch1:Kungs This Girl",
    "ytsearch1:Lost Frequencies Are You With Me",
    "ytsearch1:Vicetone Nevada",
    "ytsearch1:KSHMR Secrets",
    "ytsearch1:Fisher Losing It",
    "ytsearch1:Meduza Piece Of Your Heart",
    "ytsearch1:Regard Ride It",
    # ======================================================================
    # === INDIE / ALTERNATIVE (501-560) ===
    # ======================================================================
    "ytsearch1:Tame Impala The Less I Know The Better",
    "ytsearch1:Tame Impala Let It Happen",
    "ytsearch1:Tame Impala Borderline",
    "ytsearch1:Mac DeMarco Chamber Of Reflection",
    "ytsearch1:Mac DeMarco My Kind Of Woman",
    "ytsearch1:Cage The Elephant Ain't No Rest For The Wicked",
    "ytsearch1:Cage The Elephant Trouble",
    "ytsearch1:MGMT Electric Feel",
    "ytsearch1:MGMT Kids",
    "ytsearch1:MGMT Time To Pretend",
    "ytsearch1:Foster The People Pumped Up Kicks",
    "ytsearch1:Vampire Weekend A-Punk",
    "ytsearch1:Vampire Weekend Oxford Comma",
    "ytsearch1:The Neighbourhood Sweater Weather",
    "ytsearch1:The Neighbourhood Afraid",
    "ytsearch1:Florence And The Machine Dog Days Are Over",
    "ytsearch1:Florence And The Machine Shake It Out",
    "ytsearch1:Hozier Take Me To Church",
    "ytsearch1:Hozier Too Sweet",
    "ytsearch1:Hozier Cherry Wine",
    "ytsearch1:alt-J Breezeblocks",
    "ytsearch1:alt-J Left Hand Free",
    "ytsearch1:Portugal The Man Feel It Still",
    "ytsearch1:Gotye Eyes Wide Open",
    "ytsearch1:Phoebe Bridgers Motion Sickness",
    "ytsearch1:Wallows Are You Bored Yet",
    "ytsearch1:The 1975 Somebody Else",
    "ytsearch1:The 1975 Chocolate",
    "ytsearch1:The 1975 The Sound",
    "ytsearch1:Two Door Cinema Club What You Know",
    "ytsearch1:Two Door Cinema Club Undercover Martyn",
    "ytsearch1:The Strokes Reptilia",
    "ytsearch1:The Strokes Last Nite",
    "ytsearch1:The Strokes Someday",
    "ytsearch1:Franz Ferdinand Take Me Out",
    "ytsearch1:Bloc Party Helicopter",
    "ytsearch1:The White Stripes Seven Nation Army",
    "ytsearch1:Yeah Yeah Yeahs Heads Will Roll",
    "ytsearch1:Passion Pit Take A Walk",
    "ytsearch1:Phoenix 1901",
    "ytsearch1:Phoenix Lisztomania",
    "ytsearch1:Empire Of The Sun Walking On A Dream",
    "ytsearch1:M83 Midnight City",
    "ytsearch1:CHVRCHES The Mother We Share",
    "ytsearch1:Bastille Pompeii",
    "ytsearch1:Bastille Happier",
    "ytsearch1:The Lumineers Ho Hey",
    "ytsearch1:The Lumineers Ophelia",
    "ytsearch1:Mumford And Sons I Will Wait",
    "ytsearch1:Mumford And Sons Little Lion Man",
    "ytsearch1:Of Monsters And Men Little Talks",
    "ytsearch1:Vance Joy Riptide",
    "ytsearch1:Milky Chance Stolen Dance",
    "ytsearch1:Twenty One Pilots Stressed Out",
    "ytsearch1:Twenty One Pilots Heathens",
    "ytsearch1:Twenty One Pilots Ride",
    "ytsearch1:Twenty One Pilots Tear In My Heart",
    "ytsearch1:Panic At The Disco I Write Sins Not Tragedies",
    "ytsearch1:Panic At The Disco High Hopes",
    "ytsearch1:Fall Out Boy Sugar We're Goin Down",
    # ======================================================================
    # === CLASSIC POP / 80s-90s (561-630) ===
    # ======================================================================
    "ytsearch1:Prince Purple Rain",
    "ytsearch1:Prince When Doves Cry",
    "ytsearch1:Prince Kiss",
    "ytsearch1:Prince 1999",
    "ytsearch1:Whitney Houston I Will Always Love You",
    "ytsearch1:Whitney Houston I Wanna Dance With Somebody",
    "ytsearch1:Whitney Houston Greatest Love Of All",
    "ytsearch1:Whitney Houston How Will I Know",
    "ytsearch1:George Michael Careless Whisper",
    "ytsearch1:George Michael Faith",
    "ytsearch1:George Michael Freedom 90",
    "ytsearch1:Cyndi Lauper Girls Just Want To Have Fun",
    "ytsearch1:Cyndi Lauper Time After Time",
    "ytsearch1:Tears For Fears Everybody Wants To Rule The World",
    "ytsearch1:Tears For Fears Shout",
    "ytsearch1:Eurythmics Sweet Dreams",
    "ytsearch1:Depeche Mode Enjoy The Silence",
    "ytsearch1:Depeche Mode Personal Jesus",
    "ytsearch1:Depeche Mode Just Can't Get Enough",
    "ytsearch1:The Cure Friday I'm In Love",
    "ytsearch1:The Cure Boys Don't Cry",
    "ytsearch1:The Cure Just Like Heaven",
    "ytsearch1:New Order Blue Monday",
    "ytsearch1:New Order Bizarre Love Triangle",
    "ytsearch1:Duran Duran Hungry Like The Wolf",
    "ytsearch1:Duran Duran Rio",
    "ytsearch1:Phil Collins In The Air Tonight",
    "ytsearch1:Phil Collins Another Day In Paradise",
    "ytsearch1:Phil Collins Against All Odds",
    "ytsearch1:Fleetwood Mac Dreams",
    "ytsearch1:Fleetwood Mac The Chain",
    "ytsearch1:Fleetwood Mac Everywhere",
    "ytsearch1:Fleetwood Mac Go Your Own Way",
    "ytsearch1:Backstreet Boys I Want It That Way",
    "ytsearch1:Backstreet Boys Everybody",
    "ytsearch1:Backstreet Boys As Long As You Love Me",
    "ytsearch1:NSYNC Bye Bye Bye",
    "ytsearch1:NSYNC It's Gonna Be Me",
    "ytsearch1:Spice Girls Wannabe",
    "ytsearch1:Spice Girls Say You'll Be There",
    "ytsearch1:TLC No Scrubs",
    "ytsearch1:TLC Waterfalls",
    "ytsearch1:Destiny's Child Say My Name",
    "ytsearch1:Destiny's Child Jumpin Jumpin",
    "ytsearch1:Destiny's Child Survivor",
    "ytsearch1:No Doubt Don't Speak",
    "ytsearch1:No Doubt Just A Girl",
    "ytsearch1:Alanis Morissette You Oughta Know",
    "ytsearch1:Alanis Morissette Ironic",
    "ytsearch1:Smash Mouth All Star",
    "ytsearch1:Third Eye Blind Semi-Charmed Life",
    "ytsearch1:Ace Of Base The Sign",
    "ytsearch1:Ace Of Base All That She Wants",
    "ytsearch1:Cranberries Zombie",
    "ytsearch1:Cranberries Linger",
    "ytsearch1:Natalie Imbruglia Torn",
    "ytsearch1:Savage Garden Truly Madly Deeply",
    "ytsearch1:Savage Garden I Knew I Loved You",
    "ytsearch1:Goo Goo Dolls Iris",
    "ytsearch1:Goo Goo Dolls Slide",
    "ytsearch1:Matchbox Twenty 3AM",
    "ytsearch1:Matchbox Twenty Unwell",
    "ytsearch1:R.E.M. Losing My Religion",
    "ytsearch1:R.E.M. Everybody Hurts",
    "ytsearch1:Radiohead No Surprises",
    "ytsearch1:U2 One",
    "ytsearch1:U2 With Or Without You",
    "ytsearch1:U2 Beautiful Day",
    "ytsearch1:Pet Shop Boys West End Girls",
    "ytsearch1:Madonna Like A Prayer",
    # ======================================================================
    # === R&B / SOUL (631-690) ===
    # ======================================================================
    "ytsearch1:Frank Ocean Nights",
    "ytsearch1:Frank Ocean Thinkin Bout You",
    "ytsearch1:Frank Ocean Ivy",
    "ytsearch1:Frank Ocean Chanel",
    "ytsearch1:Frank Ocean Pink + White",
    "ytsearch1:Daniel Caesar Best Part ft H.E.R.",
    "ytsearch1:Daniel Caesar Get You ft Kali Uchis",
    "ytsearch1:Khalid Young Dumb And Broke",
    "ytsearch1:Khalid Talk",
    "ytsearch1:Khalid Location",
    "ytsearch1:Khalid Better",
    "ytsearch1:H.E.R. Best Part",
    "ytsearch1:H.E.R. Focus",
    "ytsearch1:Usher Yeah ft Lil Jon Ludacris",
    "ytsearch1:Usher DJ Got Us Fallin In Love",
    "ytsearch1:Usher Burn",
    "ytsearch1:Usher Confessions Part II",
    "ytsearch1:Usher My Boo ft Alicia Keys",
    "ytsearch1:Chris Brown Under The Influence",
    "ytsearch1:Chris Brown No Guidance ft Drake",
    "ytsearch1:Chris Brown With You",
    "ytsearch1:Chris Brown Forever",
    "ytsearch1:Miguel Adorn",
    "ytsearch1:Alicia Keys No One",
    "ytsearch1:Alicia Keys Fallin",
    "ytsearch1:Alicia Keys If I Ain't Got You",
    "ytsearch1:Alicia Keys Girl On Fire",
    "ytsearch1:John Legend Ordinary People",
    "ytsearch1:John Legend All Of Me",
    "ytsearch1:Giveon Heartbreak Anniversary",
    "ytsearch1:Giveon For Tonight",
    "ytsearch1:Summer Walker Playing Games",
    "ytsearch1:Summer Walker Over It",
    "ytsearch1:Bryson Tiller Don't",
    "ytsearch1:Bryson Tiller Exchange",
    "ytsearch1:6LACK PRBLMS",
    "ytsearch1:Kehlani Gangsta",
    "ytsearch1:Jorja Smith Blue Lights",
    "ytsearch1:Steve Lacy Bad Habit",
    "ytsearch1:Steve Lacy Dark Red",
    "ytsearch1:Brent Faiyaz Waste Time",
    "ytsearch1:Kali Uchis telepatia",
    "ytsearch1:Kali Uchis After The Storm",
    "ytsearch1:Lucky Daye Over",
    "ytsearch1:Jhene Aiko The Worst",
    "ytsearch1:Jhene Aiko Sativa ft Rae Sremmurd",
    "ytsearch1:Snoh Aalegra I Want You Around",
    "ytsearch1:Ne-Yo So Sick",
    "ytsearch1:Ne-Yo Miss Independent",
    "ytsearch1:Akon Lonely",
    "ytsearch1:Akon Smack That ft Eminem",
    "ytsearch1:Akon Right Now Na Na Na",
    "ytsearch1:Sean Kingston Beautiful Girls",
    "ytsearch1:T-Pain Buy U A Drank",
    "ytsearch1:T-Pain Bartender ft Akon",
    "ytsearch1:Teddy Swims Lose Control",
    "ytsearch1:Noah Kahan Stick Season",
    "ytsearch1:Zach Bryan Something In The Orange",
    "ytsearch1:Laufey From The Start",
    # ======================================================================
    # === LATIN / REGGAETON (691-750) ===
    # ======================================================================
    "ytsearch1:Daddy Yankee Gasolina",
    "ytsearch1:Daddy Yankee Con Calma",
    "ytsearch1:Daddy Yankee Dura",
    "ytsearch1:Daddy Yankee Limbo",
    "ytsearch1:J Balvin Mi Gente",
    "ytsearch1:J Balvin Ay Vamos",
    "ytsearch1:J Balvin Ginza",
    "ytsearch1:J Balvin In Da Getto ft Skrillex",
    "ytsearch1:Ozuna Taki Taki",
    "ytsearch1:Ozuna Se Preparo",
    "ytsearch1:Ozuna Baila Baila Baila",
    "ytsearch1:Bad Bunny Yonaguni",
    "ytsearch1:Bad Bunny Moscow Mule",
    "ytsearch1:Bad Bunny Titi Me Pregunto",
    "ytsearch1:Bad Bunny Dakiti",
    "ytsearch1:Bad Bunny Callaita",
    "ytsearch1:Bad Bunny Vete",
    "ytsearch1:Bad Bunny Me Porto Bonito",
    "ytsearch1:Bad Bunny Efecto",
    "ytsearch1:Rosalia Despecha",
    "ytsearch1:Rosalia Malamente",
    "ytsearch1:Rosalia Bizcochito",
    "ytsearch1:Rauw Alejandro Todo De Ti",
    "ytsearch1:Rauw Alejandro Baby Hello",
    "ytsearch1:Karol G Tusa ft Nicki Minaj",
    "ytsearch1:Karol G Bichota",
    "ytsearch1:Karol G TQG ft Shakira",
    "ytsearch1:Karol G Provenza",
    "ytsearch1:Shakira Bzrp Music Sessions 53",
    "ytsearch1:Shakira Chantaje ft Maluma",
    "ytsearch1:Shakira La Tortura ft Alejandro Sanz",
    "ytsearch1:Maluma Hawai",
    "ytsearch1:Maluma Felices Los 4",
    "ytsearch1:Maluma Borracha",
    "ytsearch1:Nicky Jam X ft J Balvin",
    "ytsearch1:Nicky Jam El Amante",
    "ytsearch1:Enrique Iglesias Bailando ft Descemer Bueno",
    "ytsearch1:Enrique Iglesias Hero",
    "ytsearch1:Enrique Iglesias Escape",
    "ytsearch1:Enrique Iglesias I Like It",
    "ytsearch1:Anuel AA China",
    "ytsearch1:Sech 911",
    "ytsearch1:Sech Otro Trago ft Darell",
    "ytsearch1:Farruko Pepas",
    "ytsearch1:Farruko La Toxica",
    "ytsearch1:Don Omar Danza Kuduro",
    "ytsearch1:Don Omar Taboo",
    "ytsearch1:Wisin Y Yandel Rakata",
    "ytsearch1:Tego Calderon Pa Que Retozen",
    "ytsearch1:Feid Normal",
    "ytsearch1:Feid Porfa",
    "ytsearch1:Feid Feliz Cumpleanos Ferxxo",
    "ytsearch1:Peso Pluma Ella Baila Sola ft Eslabon Armado",
    "ytsearch1:Peso Pluma Lady Gaga ft Gabito Ballesteros",
    "ytsearch1:Grupo Frontera x Bad Bunny Un x100to",
    "ytsearch1:Becky G Sin Pijama ft Natti Natasha",
    "ytsearch1:Becky G Mayores ft Bad Bunny",
    "ytsearch1:Anitta Envolver",
    "ytsearch1:Anitta Boys Don't Cry",
    # ======================================================================
    # === RECENT VIRAL / TIKTOK / 2023-2025 (751-830) ===
    # ======================================================================
    "ytsearch1:Ice Spice In Ha Mood",
    "ytsearch1:Ice Spice Princess Diana ft Nicki Minaj",
    "ytsearch1:Metro Boomin Creepin ft The Weeknd 21 Savage",
    "ytsearch1:Metro Boomin Like That ft Future Kendrick Lamar",
    "ytsearch1:Rema Calm Down",
    "ytsearch1:Rema Charm ft Selena Gomez",
    "ytsearch1:Jain Makeba",
    "ytsearch1:Benson Boone Beautiful Things",
    "ytsearch1:Benson Boone Slow It Down",
    "ytsearch1:Sabrina Carpenter Espresso",
    "ytsearch1:Sabrina Carpenter Please Please Please",
    "ytsearch1:Sabrina Carpenter Nonsense",
    "ytsearch1:Sabrina Carpenter Feather",
    "ytsearch1:Chappell Roan Pink Pony Club",
    "ytsearch1:Chappell Roan Good Luck Babe",
    "ytsearch1:Chappell Roan HOT TO GO",
    "ytsearch1:Gracie Abrams That's So True",
    "ytsearch1:Gracie Abrams I Love You I'm Sorry",
    "ytsearch1:Gracie Abrams Close To You",
    "ytsearch1:Tommy Richman Million Dollar Baby",
    "ytsearch1:Tyla Water",
    "ytsearch1:Tyla Jump ft Gunna",
    "ytsearch1:Shaboozey A Bar Song Tipsy",
    "ytsearch1:Charli XCX 360",
    "ytsearch1:Charli XCX Apple",
    "ytsearch1:Charli XCX Von Dutch",
    "ytsearch1:Artemas I Like The Way You Kiss Me",
    "ytsearch1:The Weeknd Timeless ft Playboi Carti",
    "ytsearch1:Doja Cat Agora Hills",
    "ytsearch1:Central Cee Doja",
    "ytsearch1:Central Cee Band4Band ft Lil Baby",
    "ytsearch1:Dua Lipa Houdini",
    "ytsearch1:Dua Lipa Illusion",
    "ytsearch1:Jack Harlow Lovin On Me",
    "ytsearch1:Jung Kook Seven ft Latto",
    "ytsearch1:Jung Kook Standing Next To You",
    "ytsearch1:Olivia Rodrigo get him back",
    "ytsearch1:Olivia Rodrigo obsessed",
    "ytsearch1:Tate McRae Greedy",
    "ytsearch1:Tate McRae Exes",
    "ytsearch1:Tate McRae You Broke Me First",
    "ytsearch1:Madison Beer Make You Mine",
    "ytsearch1:Madison Beer Reckless",
    "ytsearch1:Madison Beer Selfish",
    "ytsearch1:Djo End Of Beginning",
    "ytsearch1:Kenya Grace Strangers",
    "ytsearch1:Tinashe Nasty",
    "ytsearch1:Addison Rae Diet Pepsi",
    "ytsearch1:Sophie Ellis-Bextor Murder On The Dancefloor",
    "ytsearch1:David Kushner Daylight",
    "ytsearch1:David Kushner Miserable Man",
    "ytsearch1:Hozier Too Sweet",
    "ytsearch1:Teddy Swims The Door",
    "ytsearch1:Brent Faiyaz WY@",
    "ytsearch1:SZA Saturn",
    "ytsearch1:Tyler The Creator Noid",
    "ytsearch1:Kendrick Lamar Squabble Up",
    "ytsearch1:Megan Moroney Tennessee Orange",
    "ytsearch1:Chase Atlantic Swim",
    "ytsearch1:Arctic Monkeys Body Paint",
    "ytsearch1:Lana Del Rey Say Yes To Heaven",
    "ytsearch1:Lana Del Rey Summertime Sadness",
    "ytsearch1:Lana Del Rey Video Games",
    "ytsearch1:Lana Del Rey Born To Die",
    "ytsearch1:Lana Del Rey Young And Beautiful",
    "ytsearch1:Lana Del Rey West Coast",
    "ytsearch1:Lana Del Rey Brooklyn Baby",
    "ytsearch1:FKA twigs Cellophane",
    "ytsearch1:Grimes Genesis",
    "ytsearch1:Troye Sivan Rush",
    "ytsearch1:Troye Sivan Youth",
    "ytsearch1:Troye Sivan My My My",
    "ytsearch1:Kim Petras Unholy ft Sam Smith",
    "ytsearch1:Rina Sawayama XS",
    "ytsearch1:Raye Escapism ft 070 Shake",
    "ytsearch1:070 Shake Guilty Conscience",
    "ytsearch1:PinkPantheress Boy's A Liar Pt 2 ft Ice Spice",
    "ytsearch1:PinkPantheress Just For Me",
    "ytsearch1:Doja Cat Scarlet",
    # ======================================================================
    # === COUNTRY CROSSOVER / FOLK (831-860) ===
    # ======================================================================
    "ytsearch1:Morgan Wallen Last Night",
    "ytsearch1:Morgan Wallen Whiskey Glasses",
    "ytsearch1:Morgan Wallen 7 Summers",
    "ytsearch1:Luke Combs Fast Car",
    "ytsearch1:Luke Combs Beautiful Crazy",
    "ytsearch1:Chris Stapleton Tennessee Whiskey",
    "ytsearch1:Chris Stapleton Starting Over",
    "ytsearch1:Zach Bryan Something In The Orange",
    "ytsearch1:Zach Bryan I Remember Everything ft Kacey Musgraves",
    "ytsearch1:Noah Kahan Northern Attitude",
    "ytsearch1:Noah Kahan Dial Drunk",
    "ytsearch1:Hozier Almost Sweet Music",
    "ytsearch1:Bon Iver Skinny Love",
    "ytsearch1:Bon Iver Holocene",
    "ytsearch1:Fleet Foxes White Winter Hymnal",
    "ytsearch1:Iron And Wine Flightless Bird American Mouth",
    "ytsearch1:Laufey From The Start",
    "ytsearch1:Laufey Letter To My 13 Year Old Self",
    "ytsearch1:Phoebe Bridgers Kyoto",
    "ytsearch1:Phoebe Bridgers I Know The End",
    "ytsearch1:Hozier Work Song",
    "ytsearch1:Tracy Chapman Fast Car",
    "ytsearch1:John Denver Take Me Home Country Roads",
    "ytsearch1:Johnny Cash Ring Of Fire",
    "ytsearch1:Johnny Cash Hurt",
    "ytsearch1:Dolly Parton Jolene",
    "ytsearch1:Dolly Parton 9 To 5",
    "ytsearch1:Fleetwood Mac Landslide",
    "ytsearch1:Simon And Garfunkel The Sound Of Silence",
    "ytsearch1:Simon And Garfunkel Bridge Over Troubled Water",
    # ======================================================================
    # === K-POP / GLOBAL (861-900) ===
    # ======================================================================
    "ytsearch1:BTS Dynamite",
    "ytsearch1:BTS Butter",
    "ytsearch1:BTS Boy With Luv ft Halsey",
    "ytsearch1:BTS Fake Love",
    "ytsearch1:BTS DNA",
    "ytsearch1:BTS MIC Drop",
    "ytsearch1:BTS Spring Day",
    "ytsearch1:BTS Permission To Dance",
    "ytsearch1:BLACKPINK How You Like That",
    "ytsearch1:BLACKPINK DDU-DU DDU-DU",
    "ytsearch1:BLACKPINK Kill This Love",
    "ytsearch1:BLACKPINK Pink Venom",
    "ytsearch1:BLACKPINK Shut Down",
    "ytsearch1:BLACKPINK Lovesick Girls",
    "ytsearch1:LISA LALISA",
    "ytsearch1:LISA Money",
    "ytsearch1:ROSE On The Ground",
    "ytsearch1:ROSE APT ft Bruno Mars",
    "ytsearch1:JENNIE Solo",
    "ytsearch1:JENNIE You And Me",
    "ytsearch1:Stray Kids God's Menu",
    "ytsearch1:Stray Kids MANIAC",
    "ytsearch1:NewJeans Hype Boy",
    "ytsearch1:NewJeans Super Shy",
    "ytsearch1:NewJeans Ditto",
    "ytsearch1:LE SSERAFIM ANTIFRAGILE",
    "ytsearch1:LE SSERAFIM FEARLESS",
    "ytsearch1:aespa Supernova",
    "ytsearch1:aespa Next Level",
    "ytsearch1:IVE LOVE DIVE",
    "ytsearch1:IVE I AM",
    "ytsearch1:TWICE Feel Special",
    "ytsearch1:TWICE What Is Love",
    "ytsearch1:EXO Love Shot",
    "ytsearch1:EXO Growl",
    "ytsearch1:SEVENTEEN Super",
    "ytsearch1:ATEEZ Wonderland",
    "ytsearch1:Jimin Like Crazy",
    "ytsearch1:V Slow Dancing",
    "ytsearch1:Jung Kook 3D ft Jack Harlow",
    # ======================================================================
    # === AFROBEATS / GLOBAL SOUTH (901-930) ===
    # ======================================================================
    "ytsearch1:Burna Boy Last Last",
    "ytsearch1:Burna Boy Ye",
    "ytsearch1:Burna Boy On The Low",
    "ytsearch1:Burna Boy City Boys",
    "ytsearch1:Burna Boy Anybody",
    "ytsearch1:Wizkid Essence ft Tems",
    "ytsearch1:Wizkid Ojuelegba",
    "ytsearch1:Wizkid Come Closer ft Drake",
    "ytsearch1:Tems Free Mind",
    "ytsearch1:Tems Higher",
    "ytsearch1:Davido Fall",
    "ytsearch1:Davido IF",
    "ytsearch1:CKay Love Nwantiti",
    "ytsearch1:Fireboy DML Peru",
    "ytsearch1:Rema Calm Down Remix ft Selena Gomez",
    "ytsearch1:Ayra Starr Rush",
    "ytsearch1:Ayra Starr Bloody Samaritan",
    "ytsearch1:Omah Lay Understand",
    "ytsearch1:Tiwa Savage Somebody's Son",
    "ytsearch1:Yemi Alade Johnny",
    "ytsearch1:Major Lazer ft DJ Maphorisa Particula",
    "ytsearch1:Master KG Jerusalema",
    "ytsearch1:Tyla Getting Late",
    "ytsearch1:Black Coffee Drive ft David Guetta Delilah Montagu",
    "ytsearch1:Asake Lonely At The Top",
    "ytsearch1:Asake Sungba",
    "ytsearch1:Victony Soweto ft Don Toliver Rema",
    "ytsearch1:Patoranking Girlie O",
    "ytsearch1:Diamond Platnumz Jeje",
    "ytsearch1:Innoss'B Yope",
    # ======================================================================
    # === CLASSIC ANTHEMS / TIMELESS (931-975) ===
    # ======================================================================
    "ytsearch1:Elton John Rocket Man",
    "ytsearch1:Elton John Your Song",
    "ytsearch1:Elton John Tiny Dancer",
    "ytsearch1:Elton John Crocodile Rock",
    "ytsearch1:Elton John Bennie And The Jets",
    "ytsearch1:Elton John I'm Still Standing",
    "ytsearch1:Billy Joel Piano Man",
    "ytsearch1:Billy Joel Uptown Girl",
    "ytsearch1:Billy Joel Vienna",
    "ytsearch1:Madonna Material Girl",
    "ytsearch1:Madonna Vogue",
    "ytsearch1:Madonna Hung Up",
    "ytsearch1:Madonna Like A Virgin",
    "ytsearch1:Cher Believe",
    "ytsearch1:ABBA Dancing Queen",
    "ytsearch1:ABBA Mamma Mia",
    "ytsearch1:ABBA Gimme Gimme Gimme",
    "ytsearch1:ABBA The Winner Takes It All",
    "ytsearch1:Bee Gees Stayin Alive",
    "ytsearch1:Bee Gees How Deep Is Your Love",
    "ytsearch1:Gloria Gaynor I Will Survive",
    "ytsearch1:Donna Summer Hot Stuff",
    "ytsearch1:Donna Summer I Feel Love",
    "ytsearch1:Earth Wind And Fire September",
    "ytsearch1:Earth Wind And Fire Boogie Wonderland",
    "ytsearch1:KC And The Sunshine Band That's The Way I Like It",
    "ytsearch1:Jackson 5 I Want You Back",
    "ytsearch1:Jackson 5 ABC",
    "ytsearch1:Marvin Gaye What's Going On",
    "ytsearch1:Marvin Gaye Let's Get It On",
    "ytsearch1:Marvin Gaye Ain't No Mountain High Enough",
    "ytsearch1:Aretha Franklin Respect",
    "ytsearch1:Aretha Franklin Natural Woman",
    "ytsearch1:Ray Charles Georgia On My Mind",
    "ytsearch1:James Brown I Got You I Feel Good",
    "ytsearch1:Otis Redding Sittin On The Dock Of The Bay",
    "ytsearch1:Al Green Let's Stay Together",
    "ytsearch1:Commodores Easy",
    "ytsearch1:Lionel Richie All Night Long",
    "ytsearch1:Lionel Richie Hello",
    "ytsearch1:Diana Ross I'm Coming Out",
    "ytsearch1:Chic Le Freak",
    "ytsearch1:Kool And The Gang Celebration",
    "ytsearch1:Blondie Heart Of Glass",
    "ytsearch1:Blondie Call Me",
    # ======================================================================
    # === EXTRA HITS TO REACH 1000 (976-1000) ===
    # ======================================================================
    "ytsearch1:Dua Lipa Dance The Night",
    "ytsearch1:Olivia Rodrigo brutal",
    "ytsearch1:Miley Cyrus Party In The USA",
    "ytsearch1:Miley Cyrus The Climb",
    "ytsearch1:P!nk Raise Your Glass",
    "ytsearch1:P!nk So What",
    "ytsearch1:P!nk Just Give Me A Reason ft Nate Ruess",
    "ytsearch1:Kesha TiK ToK",
    "ytsearch1:Kesha Die Young",
    "ytsearch1:LMFAO Party Rock Anthem",
    "ytsearch1:LMFAO Sexy And I Know It",
    "ytsearch1:Flo Rida Low ft T-Pain",
    "ytsearch1:Flo Rida Whistle",
    "ytsearch1:Flo Rida Right Round",
    "ytsearch1:Sean Paul Temperature",
    "ytsearch1:Sean Paul Get Busy",
    "ytsearch1:Black Eyed Peas I Gotta Feeling",
    "ytsearch1:Black Eyed Peas Where Is The Love",
    "ytsearch1:Black Eyed Peas Boom Boom Pow",
    "ytsearch1:Outkast Hey Ya",
    "ytsearch1:Outkast Roses",
    "ytsearch1:Nelly Hot In Herre",
    "ytsearch1:Nelly Dilemma ft Kelly Rowland",
    "ytsearch1:Fergie Glamorous",
    "ytsearch1:Fergie London Bridge",
    "ytsearch1:Nelly Furtado Maneater",
    "ytsearch1:Nelly Furtado Promiscuous ft Timbaland",
]
