#!/usr/bin/env python3
"""Build scripts/topup_5000_hits.py with songs missing from canonical pool."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))

from rebuild_random_songs import (  # noqa: E402
    TARGET_COUNT,
    _apply_fill_hits,
    _collect_candidates,
    _load_catalog_artists,
    _merge_unique,
    _normalize_entry,
    canonical_song_key,
)

# Large seed pool — validated against existing catalog before write.
_SEED: list[str] = [
    "Take Five - Dave Brubeck",
    "So What - Miles Davis",
    "At Last - Etta James",
    "What A Diff'rence A Day Makes - Dinah Washington",
    "Fly Me To The Moon - Frank Sinatra",
    "The Way You Look Tonight - Frank Sinatra",
    "Unforgettable - Nat King Cole",
    "Mona Lisa - Nat King Cole",
    "Georgia On My Mind - Ray Charles",
    "Hit The Road Jack - Ray Charles",
    "A Case Of You - Joni Mitchell",
    "Big Yellow Taxi - Joni Mitchell",
    "Both Sides Now - Joni Mitchell",
    "Piano Man - Billy Joel",
    "Uptown Girl - Billy Joel",
    "Vienna - Billy Joel",
    "Rosanna - Toto",
    "Hold The Line - Toto",
    "Separate Ways - Journey",
    "Open Arms - Journey",
    "Don't Stop Believin' - Journey",
    "Carry On Wayward Son - Kansas",
    "Dust In The Wind - Kansas",
    "More Than A Feeling - Boston",
    "Peace Of Mind - Boston",
    "Black Magic Woman - Santana",
    "Smooth - Santana ft Rob Thomas",
    "Maria Maria - Santana",
    "Riders On The Storm - The Doors",
    "Light My Fire - The Doors",
    "Break On Through - The Doors",
    "Paint It Black - The Rolling Stones",
    "Gimme Shelter - The Rolling Stones",
    "Start Me Up - The Rolling Stones",
    "Sympathy For The Devil - The Rolling Stones",
    "While My Guitar Gently Weeps - The Beatles",
    "Come Together - The Beatles",
    "Let It Be - The Beatles",
    "Hey Jude - The Beatles",
    "Yesterday - The Beatles",
    "Here Comes The Sun - The Beatles",
    "Twist And Shout - The Beatles",
    "I Want To Hold Your Hand - The Beatles",
    "Like A Rolling Stone - Bob Dylan",
    "Knockin' On Heaven's Door - Bob Dylan",
    "The Times They Are A-Changin' - Bob Dylan",
    "Hurt - Johnny Cash",
    "Ring Of Fire - Johnny Cash",
    "Folsom Prison Blues - Johnny Cash",
    "Jolene - Dolly Parton",
    "9 To 5 - Dolly Parton",
    "I Will Always Love You - Dolly Parton",
    "Friends In Low Places - Garth Brooks",
    "The Dance - Garth Brooks",
    "Amarillo By Morning - George Strait",
    "Check Yes Or No - George Strait",
    "Live Like You Were Dying - Tim McGraw",
    "Before He Cheats - Carrie Underwood",
    "Jesus Take The Wheel - Carrie Underwood",
    "Wagon Wheel - Old Crow Medicine Show",
    "Take Me Home Country Roads - John Denver",
    "Rocky Mountain High - John Denver",
    "Annie's Song - John Denver",
    "Con Te Partirò - Andrea Bocelli",
    "Time To Say Goodbye - Andrea Bocelli",
    "The Prayer - Andrea Bocelli",
    "Volare - Domenico Modugno",
    "Nel Blu Dipinto Di Blu - Domenico Modugno",
    "La Vie En Rose - Edith Piaf",
    "Non Je Ne Regrette Rien - Edith Piaf",
    "Ne Me Quitte Pas - Jacques Brel",
    "Formidable - Stromae",
    "Papaoutai - Stromae",
    "Alors On Danse - Stromae",
    "Dernière Danse - Indila",
    "Tourner Dans Le Vide - Indila",
    "Djadja - Aya Nakamura",
    "Pookie - Aya Nakamura",
    "Copines - Aya Nakamura",
    "Je Veux - Zaz",
    "On Ira - Zaz",
    "Bella Ciao - Manu Pilas",
    "Felicità - Al Bano",
    "L'Italiano - Toto Cutugno",
    "Ti Amo - Umberto Tozzi",
    "Vivo Per Lei - Giorgia",
    "Con Calma - Daddy Yankee",
    "Gasolina - Daddy Yankee",
    "Limbo - Daddy Yankee",
    "La Gasolina - Daddy Yankee",
    "Bailando - Enrique Iglesias",
    "Hero - Enrique Iglesias",
    "El Perdón - Nicky Jam",
    "Hasta El Amanecer - Nicky Jam",
    "X - Nicky Jam",
    "Te Boté - Casper",
    "Ella Quiere Beber - Anuel AA",
    "China - Anuel AA",
    "Secreto - Anuel AA",
    "Te Soñé De Nuevo - Yandel",
    "Explícale - Yandel",
    "Dile - Don Omar",
    "Virtual Diva - Don Omar",
    "Taboo - Don Omar",
    "La Gozadera - Gente De Zona",
    "Bailando - Gente De Zona",
    "Propuesta Indecente - Romeo Santos",
    "Eres Tu - Jesse y Joy",
    "Lo Que Construimos - Natalia Lafourcade",
    "Hasta La Raiz - Natalia Lafourcade",
    "No Surprises - Radiohead",
    "Fake Plastic Trees - Radiohead",
    "High And Dry - Radiohead",
    "Street Spirit - Radiohead",
    "Bitter Sweet Symphony - The Verve",
    "The Drugs Don't Work - The Verve",
    "Song 2 - Blur",
    "Parklife - Blur",
    "Common People - Pulp",
    "Disco 2000 - Pulp",
    "There Is A Light That Never Goes Out - The Smiths",
    "How Soon Is Now - The Smiths",
    "Love Will Tear Us Apart - Joy Division",
    "Blue Monday - New Order",
    "Enjoy The Silence - Depeche Mode",
    "Personal Jesus - Depeche Mode",
    "Just Can't Get Enough - Depeche Mode",
    "Tainted Love - Soft Cell",
    "Don't You Want Me - Human League",
    "Take On Me - a-ha",
    "The Sun Always Shines On TV - a-ha",
    "Total Eclipse Of The Heart - Bonnie Tyler",
    "Holding Out For A Hero - Bonnie Tyler",
    "I Drove All Night - Cyndi Lauper",
    "Time After Time - Cyndi Lauper",
    "True Colors - Cyndi Lauper",
    "Girls Just Want To Have Fun - Cyndi Lauper",
    "Material Girl - Madonna",
    "Like A Prayer - Madonna",
    "Express Yourself - Madonna",
    "Ray Of Light - Madonna",
    "Frozen - Madonna",
    "Music - Madonna",
    "Hung Up - Madonna",
    "4 Minutes - Madonna",
    "Wrecking Ball - Miley Cyrus",
    "Flowers - Miley Cyrus",
    "Party In The USA - Miley Cyrus",
    "Old Town Road - Lil Nas X",
    "Industry Baby - Lil Nas X",
    "Montero - Lil Nas X",
    "Peaches - Justin Bieber",
    "Ghost - Justin Bieber",
    "Stay - The Kid LAROI",
    "Heat Waves - Glass Animals",
    "As It Was - Harry Styles",
    "Watermelon Sugar - Harry Styles",
    "Sign Of The Times - Harry Styles",
    "About Damn Time - Lizzo",
    "Truth Hurts - Lizzo",
    "Good As Hell - Lizzo",
    "Anti-Hero - Taylor Swift",
    "Cruel Summer - Taylor Swift",
    "Fortnight - Taylor Swift",
    "Blank Space - Taylor Swift",
    "Love Story - Taylor Swift",
    "You Belong With Me - Taylor Swift",
    "We Are Never Ever Getting Back Together - Taylor Swift",
    "I Knew You Were Trouble - Taylor Swift",
    "Bad Blood - Taylor Swift",
    "Delicate - Taylor Swift",
    "Cardigan - Taylor Swift",
    "Willow - Taylor Swift",
    "All Too Well - Taylor Swift",
    "Espresso - Sabrina Carpenter",
    "Please Please Please - Sabrina Carpenter",
    "Vampire - Olivia Rodrigo",
    "Drivers License - Olivia Rodrigo",
    "Good 4 U - Olivia Rodrigo",
    "Bad Idea Right - Olivia Rodrigo",
    "Birds Of A Feather - Billie Eilish",
    "What Was I Made For - Billie Eilish",
    "Not Like Us - Kendrick Lamar",
    "Humble - Kendrick Lamar",
    "DNA - Kendrick Lamar",
    "Alright - Kendrick Lamar",
    "Sicko Mode - Travis Scott",
    "FE!N - Travis Scott",
    "Goosebumps - Travis Scott",
    "Highest In The Room - Travis Scott",
    "Life Is Good - Future",
    "Mask Off - Future",
    "Turn On The Lights - Future",
    "Super Bass - Nicki Minaj",
    "Starships - Nicki Minaj",
    "Anaconda - Nicki Minaj",
    "Bodak Yellow - Cardi B",
    "I Like It - Cardi B",
    "WAP - Cardi B",
    "Savage - Megan Thee Stallion",
    "Hot Girl Summer - Megan Thee Stallion",
    "Industry Baby - Lil Nas X ft Jack Harlow",
    "Sunroof - Nicky Youre",
    "abcdefu - Gayle",
    "Unholy - Sam Smith",
    "Stay With Me - Sam Smith",
    "Too Good At Goodbyes - Sam Smith",
    "Dancing With A Stranger - Sam Smith",
    "I'm Not The Only One - Sam Smith",
    "Shallow - Lady Gaga",
    "Rain On Me - Lady Gaga",
    "Poker Face - Lady Gaga",
    "Bad Romance - Lady Gaga",
    "Just Dance - Lady Gaga",
    "Born This Way - Lady Gaga",
    "Applause - Lady Gaga",
    "Million Reasons - Lady Gaga",
    "Die With A Smile - Lady Gaga",
    "Easy On Me - Adele",
    "Hello - Adele",
    "Someone Like You - Adele",
    "Rolling In The Deep - Adele",
    "Set Fire To The Rain - Adele",
    "Skyfall - Adele",
    "Send My Love - Adele",
    "When We Were Young - Adele",
    "Halo - Beyonce",
    "Single Ladies - Beyonce",
    "Crazy In Love - Beyonce",
    "Formation - Beyonce",
    "Run The World - Beyonce",
    "Drunk In Love - Beyonce",
    "Break My Soul - Beyonce",
    "Texas Hold Em - Beyonce",
    "Cuff It - Beyonce",
    "We Found Love - Rihanna",
    "Umbrella - Rihanna",
    "Diamonds - Rihanna",
    "Only Girl - Rihanna",
    "Work - Rihanna",
    "Needed Me - Rihanna",
    "Love On The Brain - Rihanna",
    "Calm Down - Rema",
    "People - Libianca",
    "Water - Tyla",
    "Peru - Fireboy DML",
    "Essence - Wizkid",
    "Last Last - Burna Boy",
    "Ye - Burna Boy",
    "Jerusalema - Master KG",
    "Love Nwantiti - CKay",
    "Soweto - Victony",
    "Bandana - Fireboy DML",
    "Monalisa - Lojay",
    "Soso - Omah Lay",
    "Understand - Omah Lay",
    "Bloody Samaritan - Ayra Starr",
    "Rush - Ayra Starr",
    "Calm Down - Rema ft Selena Gomez",
    "Seven - Jungkook",
    "Standing Next To You - Jungkook",
    "Super Shy - NewJeans",
    "Ditto - NewJeans",
    "ETA - NewJeans",
    "Cupid - Fifty Fifty",
    "Queencard - G I-DLE",
    "Super - Seventeen",
    "God's Menu - Stray Kids",
    "Butter - BTS",
    "Dynamite - BTS",
    "Life Goes On - BTS",
    "Spring Day - BTS",
    "Blood Sweat Tears - BTS",
    "Fake Love - BTS",
    "Boy With Luv - BTS",
    "Gangnam Style - PSY",
    "Gentleman - PSY",
    "That That - PSY",
    "Ddu-Du Ddu-Du - Blackpink",
    "Kill This Love - Blackpink",
    "How You Like That - Blackpink",
    "Pink Venom - Blackpink",
    "Shut Down - Blackpink",
    "As If It's Your Last - Blackpink",
    "Lovesick Girls - Blackpink",
    "Next Level - aespa",
    "Savage - aespa",
    "Spicy - aespa",
    "Drama - aespa",
    "Antifragile - Le Sserafim",
    "Unforgiven - Le Sserafim",
    "Perfect Night - Le Sserafim",
    "Magnetic - Illit",
    "Sheesh - Babymonster",
    "Magnetic - Illit",
    "APT - Rosé",
    "Die With A Smile - Bruno Mars",
    "Locked Out Of Heaven - Bruno Mars",
    "When I Was Your Man - Bruno Mars",
    "Treasure - Bruno Mars",
    "That's What I Like - Bruno Mars",
    "24K Magic - Bruno Mars",
    "Uptown Funk - Mark Ronson",
    "Can't Stop The Feeling - Justin Timberlake",
    "Mirrors - Justin Timberlake",
    "SexyBack - Justin Timberlake",
    "Cry Me A River - Justin Timberlake",
    "My Love - Justin Timberlake",
    "Rock Your Body - Justin Timberlake",
    "Suit And Tie - Justin Timberlake",
    "Can't Hold Us - Macklemore",
    "Thrift Shop - Macklemore",
    "Glorious - Macklemore",
    "Same Love - Macklemore",
    "Timber - Pitbull",
    "Give Me Everything - Pitbull",
    "Hotel Room Service - Pitbull",
    "Fireball - Pitbull",
    "Feel This Moment - Pitbull",
    "International Love - Pitbull",
    "DJ Got Us Fallin In Love - Usher",
    "OMG - Usher",
    "Scream - Usher",
    "Yeah - Usher",
    "Burn - Usher",
    "U Remind Me - Usher",
    "Confessions Part II - Usher",
    "No Limit - Usher",
    "Good Good - Usher",
    "Blurred Lines - Robin Thicke",
    "Lost Without You - Robin Thicke",
    "Call Me Maybe - Carly Rae Jepsen",
    "I Really Like You - Carly Rae Jepsen",
    "Run Away With Me - Carly Rae Jepsen",
    "Stitches - Shawn Mendes",
    "Treat You Better - Shawn Mendes",
    "There's Nothing Holdin Me Back - Shawn Mendes",
    "Senorita - Shawn Mendes",
    "Mercy - Shawn Mendes",
    "In My Blood - Shawn Mendes",
    "Lost In Japan - Shawn Mendes",
    "Beautiful - Shawn Mendes",
    "Attention - Charlie Puth",
    "We Don't Talk Anymore - Charlie Puth",
    "See You Again - Charlie Puth",
    "One Call Away - Charlie Puth",
    "How Long - Charlie Puth",
    "Light Switch - Charlie Puth",
    "Left And Right - Charlie Puth",
    "Bad Habits - Ed Sheeran",
    "Shape Of You - Ed Sheeran",
    "Perfect - Ed Sheeran",
    "Thinking Out Loud - Ed Sheeran",
    "Photograph - Ed Sheeran",
    "Castle On The Hill - Ed Sheeran",
    "Galway Girl - Ed Sheeran",
    "Shivers - Ed Sheeran",
    "Bad Habits - Ed Sheeran",
    "Someone You Loved - Lewis Capaldi",
    "Before You Go - Lewis Capaldi",
    "Forget Me - Lewis Capaldi",
    "Pointless - Lewis Capaldi",
    "Hold Me While You Wait - Lewis Capaldi",
    "Dance Monkey - Tones And I",
    "Fly Away - Tones And I",
    "Ur So Gay - Katy Perry",
    "I Kissed A Girl - Katy Perry",
    "Hot N Cold - Katy Perry",
    "Teenage Dream - Katy Perry",
    "Firework - Katy Perry",
    "Roar - Katy Perry",
    "Dark Horse - Katy Perry",
    "Chained To The Rhythm - Katy Perry",
    "Never Really Over - Katy Perry",
    "Smile - Katy Perry",
    "Part Of Me - Katy Perry",
    "Wide Awake - Katy Perry",
    "E.T. - Katy Perry",
    "California Gurls - Katy Perry",
    "Last Friday Night - Katy Perry",
    "The One That Got Away - Katy Perry",
    "Unconditionally - Katy Perry",
    "Swish Swish - Katy Perry",
    "Bon Appetit - Katy Perry",
    "Harleys In Hawaii - Katy Perry",
    "Never Worn White - Katy Perry",
    "When I'm Gone - Katy Perry",
    "Woman's World - Katy Perry",
    "Lifetimes - Katy Perry",
    "Cozy Little Christmas - Katy Perry",
    "Small Talk - Katy Perry",
    "365 - Katy Perry",
    "Daisies - Katy Perry",
    "What Makes A Man - Katy Perry",
    "Peacock - Katy Perry",
    "Circle The Drain - Katy Perry",
    "Who You Love - Katy Perry",
    "Walking On Air - Katy Perry",
    "Birthday - Katy Perry",
    "This Is How We Do - Katy Perry",
    "Choose Your Battles - Katy Perry",
    "It Takes Two - Katy Perry",
    "International Smile - Katy Perry",
    "Legendary Lovers - Katy Perry",
    "Spiritual - Katy Perry",
    "Love Me - Katy Perry",
    "Double Rainbow - Katy Perry",
    "By The Grace Of God - Katy Perry",
    "Ghost - Katy Perry",
    "It Takes Two - Katy Perry",
    "Mannequin - Katy Perry",
    "Self Inflicted - Katy Perry",
    "Thinking Of You - Katy Perry",
    "I'm Still Breathing - Katy Perry",
    "Lost - Katy Perry",
    "Hummingbird Heartbeat - Katy Perry",
    "Pearl - Katy Perry",
    "Who Am I Living For - Katy Perry",
    "Circle The Drain - Katy Perry",
    "The One That Got Away - Katy Perry",
    "Peacock - Katy Perry",
    "Hummingbird Heartbeat - Katy Perry",
    "Not Like The Movies - Katy Perry",
    "Long Shot - Katy Perry",
    "Self Inflicted - Katy Perry",
    "Who Am I Living For - Katy Perry",
    "Pearl - Katy Perry",
    "Circle The Drain - Katy Perry",
    "The One That Got Away - Katy Perry",
    "Peacock - Katy Perry",
    "Hummingbird Heartbeat - Katy Perry",
    "Not Like The Movies - Katy Perry",
    "Long Shot - Katy Perry",
    "Self Inflicted - Katy Perry",
    "Who Am I Living For - Katy Perry",
    "Pearl - Katy Perry",
]


def main() -> None:
    existing, catalog, supplemental = _collect_candidates()
    merged = _apply_fill_hits(
        _merge_unique([existing, catalog, supplemental]),
        set(_load_catalog_artists().keys()),
    )
    seen = {canonical_song_key(s) for s in merged}
    catalog_artists = set(_load_catalog_artists().keys())
    topup: list[str] = []
    for s in _SEED:
        norm = _normalize_entry(s.strip(), catalog_artists)
        if not norm:
            continue
        ck = canonical_song_key(norm)
        if ck in seen:
            continue
        seen.add(ck)
        topup.append(norm)
    need = TARGET_COUNT - len(merged)
    print(f"merged={len(merged)} topup_found={len(topup)} need={need}")
    if len(topup) < need:
        raise SystemExit(f"Only {len(topup)} topup hits; need {need}")
    topup = topup[:need]
    out = ROOT / "scripts" / "topup_5000_hits.py"
    lines = [
        '"""Extra famous hits to reach exactly 5000 unique canonical entries."""\n\n',
        "TOPUP_HITS: list[str] = [\n",
    ]
    for s in topup:
        lines.append(f'    "{s}",\n')
    lines.append("]\n")
    out.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {len(topup)} hits to {out}")


if __name__ == "__main__":
    main()
