"""Curated mega-hits in Title - Artist format (used by rebuild_random_songs.py)."""

FAMOUS_HITS: list[str] = [
    "Slow Dancing - V",
    "Somebody That I Used To Know - Gotye ft Kimbra",
    "Love Me Again - V",
    "M - Ayumi Hamasaki",
    "Empire State Of Mind - Jay-Z ft Alicia Keys",
    "Run This Town - Jay-Z ft Rihanna",
    "Without You - David Guetta ft Usher",
    "Hips Don't Lie - Shakira ft Wyclef Jean",
    "La Tortura - Shakira ft Alejandro Sanz",
    "Oops!... I Did It Again - Britney Spears",
    "Baby One More Time - Britney Spears",
    "What's My Age Again? - blink-182",
    "Lovely - Billie Eilish ft Khalid",
    "Sunflower - Post Malone ft Swae Lee",
    "Rockstar - Post Malone ft 21 Savage",
    "Starboy - The Weeknd ft Daft Punk",
    "Shallow - Lady Gaga ft Bradley Cooper",
    "Uptown Funk - Mark Ronson ft Bruno Mars",
    "Despacito - Luis Fonsi ft Daddy Yankee",
    "El Perdón - Nicky Jam ft Enrique Iglesias",
    "Mi Gente - J Balvin ft Willy William",
    "Taki Taki - DJ Snake ft Selena Gomez, Ozuna, Cardi B",
    "Con Calma - Daddy Yankee ft Snow",
    "Me Porto Bonito - Bad Bunny ft Chencho Corleone",
    "I Like It - Cardi B, Bad Bunny, J Balvin",
    "WAP - Cardi B ft Megan Thee Stallion",
    "Industry Baby - Lil Nas X ft Jack Harlow",
    "Old Town Road - Lil Nas X ft Billy Ray Cyrus",
    "Peaches - Justin Bieber ft Daniel Caesar, Giveon",
    "What Do You Mean? - Justin Bieber",
    "Baby - Justin Bieber ft Ludacris",
    "Stay - The Kid LAROI ft Justin Bieber",
    "Thank U, Next - Ariana Grande",
    "Problem - Ariana Grande ft Iggy Azalea",
    "Side To Side - Ariana Grande ft Nicki Minaj",
    "Party In The U.S.A. - Miley Cyrus",
    "California Gurls - Katy Perry ft Snoop Dogg",
    "Boy With Luv - BTS ft Halsey",
    "Unholy - Sam Smith ft Kim Petras",
    "Say Something - A Great Big World ft Christina Aguilera",
    "Moves Like Jagger - Maroon 5 ft Christina Aguilera",
    "Payphone - Maroon 5 ft Wiz Khalifa",
    "Enemy - Imagine Dragons ft JID",
    "Titanium - David Guetta ft Sia",
    "Without You - Avicii ft Sandro Cavazza",
    "Darkside - Alan Walker ft Au/Ra, Tomine Harket",
    "Closer - The Chainsmokers ft Halsey",
    "Don't Let Me Down - The Chainsmokers ft Daya",
    "Something Just Like This - The Chainsmokers ft Coldplay",
    "Roses - The Chainsmokers ft ROZES",
    "Takeaway - The Chainsmokers ft ILLENIUM ft Lennon Stella",
    "Mr. Brightside - The Killers",
    "Do I Wanna Know? - Arctic Monkeys",
    "R U Mine? - Arctic Monkeys",
    "Why'd You Only Call Me When You're High? - Arctic Monkeys",
    "Glory - John Legend ft Common",
    "South Of The Border - Ed Sheeran ft Camila Cabello, Cardi B",
    "New York, New York - Frank Sinatra",
    "Something Just Like This - Coldplay ft The Chainsmokers",
    "Help! - The Beatles",
    "Take It Easy - Eagles",
    "New Kid In Town - Eagles",
    "Under Pressure - Queen ft David Bowie",
    "Feel Good Inc. - Gorillaz",
    "Telephone - Lady Gaga ft Beyoncé",
    "Rain On Me - Lady Gaga ft Ariana Grande",
    "Umbrella - Rihanna ft Jay-Z",
    "We Found Love - Rihanna ft Calvin Harris",
    "Work - Rihanna ft Drake",
    "Stay - Rihanna ft Mikky Ekko",
    "Yeah! - Usher ft Lil Jon, Ludacris",
    "OMG - Usher ft will.i.am",
    "Empire State Of Mind - Alicia Keys ft Jay-Z",
    "Bang Bang - Jessie J ft Ariana Grande, Nicki Minaj",
    "Moment 4 Life - Nicki Minaj ft Drake",
    "Low - Flo Rida ft T-Pain",
    "Right Round - Flo Rida ft Ke$ha",
    "Club Can't Handle Me - Flo Rida ft David Guetta",
    "Timber - Pitbull ft Kesha",
    "Give Me Everything - Pitbull ft Ne-Yo, Afrojack, Nayer",
    "International Love - Pitbull ft Chris Brown",
    "Fireball - Pitbull ft John Ryan",
    "On The Floor - Jennifer Lopez ft Pitbull",
    "X - Nicky Jam ft J Balvin, Maluma, Ozuna",
    "Te Boté - Casper, Nio García, Darell, Nicky Jam, Bad Bunny, Ozuna",
    "TQG - Karol G ft Shakira",
    "Dakiti - Bad Bunny ft Jhay Cortez",
    "Subeme La Radio - Enrique Iglesias ft Descemer Bueno, Zion & Lennox",
    "Chantaje - Shakira ft Maluma",
    "Whenever, Wherever - Shakira",
    "Kiss Me More - Doja Cat ft SZA",
    "Best Friend - Saweetie ft Doja Cat",
    "Please Me - Cardi B ft Bruno Mars",
    "Die With A Smile - Lady Gaga ft Bruno Mars",
    "APT. - ROSÉ ft Bruno Mars",
    "Danza Kuduro - Don Omar ft Lucenzo",
    "Bailando - Enrique Iglesias ft Descemer Bueno, Gente De Zona",
    "California Love - 2Pac ft Dr. Dre",
    "Mo Money Mo Problems - The Notorious B.I.G. ft Puff Daddy, Mase",
    "Forgot About Dre - Dr. Dre ft Eminem",
    "Candy Shop - 50 Cent ft Olivia",
    "Lean Back - Terror Squad ft Fat Joe, Remy Ma",
    "All The Way Up - Fat Joe ft Remy Ma, French Montana",
    "Gold Digger - Kanye West ft Jamie Foxx",
    "Touch The Sky - Kanye West ft Lupe Fiasco",
    "Ni**as In Paris - Jay-Z ft Kanye West",
    "Drop It Like It's Hot - Snoop Dogg ft Pharrell",
    "See You Again - Wiz Khalifa ft Charlie Puth",
    "Love The Way You Lie - Eminem ft Rihanna",
    "Stan - Eminem ft Dido",
    "Till I Collapse - Eminem ft Nate Dogg",
    "Ms. Jackson - OutKast",
    "Hey Ya! - OutKast",
    "The Way You Move - OutKast ft Sleepy Brown",
    "No Diggity - Blackstreet ft Dr. Dre, Queen Pen",
    "Johnny B. Goode - Chuck Berry",
    "Cruise - Florida Georgia Line ft Nelly",
    "Meant To Be - Bebe Rexha ft Florida Georgia Line",
    "Rakata - Wisin & Yandel",
    "Abusadora - Wisin & Yandel",
    "Mayor Que Yo - Luny Tunes ft Baby Ranks, Daddy Yankee, Wisin & Yandel",
    "Oye Mi Canto - N.O.R.E. ft Nina Sky, Gem Star, Big Mato",
    "Lean On - Major Lazer ft DJ Snake, MØ",
    "Light It Up - Major Lazer ft Nyla, Fuse ODG",
    "Cold Water - Major Lazer ft Justin Bieber, MØ",
    "Turn Down For What - DJ Snake ft Lil Jon",
    "Let Me Love You - DJ Snake ft Justin Bieber",
    "Middle - DJ Snake ft Bipolar Sunshine",
    "In The Name Of Love - Martin Garrix ft Bebe Rexha",
    "Scared To Be Lonely - Martin Garrix ft Dua Lipa",
    "This Is What You Came For - Calvin Harris ft Rihanna",
    "One Kiss - Calvin Harris ft Dua Lipa",
    "Promises - Calvin Harris ft Sam Smith",
    "How Deep Is Your Love - Calvin Harris ft Disciples",
    "Under Control - Calvin Harris ft Hurts, Big Sean",
    "Memories - David Guetta ft Kid Cudi",
    "Hey Mama - David Guetta ft Nicki Minaj, Bebe Rexha, Afrojack",
    "Turn Me On - David Guetta ft Nicki Minaj",
    "Where Them Girls At - David Guetta ft Flo Rida, Nicki Minaj",
    "When Love Takes Over - David Guetta ft Kelly Rowland",
    "Bangarang - Skrillex ft Sirah",
    "Clarity - Zedd ft Foxes",
    "The Middle - Zedd ft Maren Morris, Grey",
    "Break Free - Ariana Grande ft Zedd",
    "Beautiful Now - Zedd ft Jon Bellion",
    "Dirrty - Christina Aguilera ft Redman",
    "FourFiveSeconds - Rihanna ft Kanye West, Paul McCartney",
    "Wild Thoughts - DJ Khaled ft Rihanna, Bryson Tiller",
    "I'll Be Missing You - Puff Daddy ft Faith Evans, 112",
    "If I Ruled The World - Nas ft Lauryn Hill",
    "Beautiful - Snoop Dogg ft Pharrell",
    "Young Wild & Free - Snoop Dogg ft Wiz Khalifa, Bruno Mars",
    "Signs - Snoop Dogg ft Justin Timberlake, Charlie Wilson",
    "Ambitionz Az A Ridah - 2Pac",
    "You Don't Know How It Feels - Tom Petty",
    "Stop Draggin' My Heart Around - Stevie Nicks ft Tom Petty",
    "Edge Of Seventeen - Stevie Nicks",
    "Stand Back - Stevie Nicks",
    "Leather And Lace - Stevie Nicks ft Don Henley",
    "Silver Springs - Fleetwood Mac",
    "Say You Love Me - Fleetwood Mac",
    "Over My Head - Fleetwood Mac",
    "Hold Me - Fleetwood Mac",
    "Tusk - Fleetwood Mac",
    "Big Love - Fleetwood Mac",
    "Seven Wonders - Fleetwood Mac",
    "As Long As You Follow - Fleetwood Mac",
    "Skateaway - Dire Straits",
    "Private Investigations - Dire Straits",
    "So Far Away - Dire Straits",
    "Your Latest Trick - Dire Straits",
    "On Every Street - Dire Straits",
    "Heavy Fuel - Dire Straits",
    "Calling Elvis - Dire Straits",
    "The Bug - Dire Straits",
    "Through The Never - Metallica",
    "Of Wolf And Man - Metallica",
    "The God That Failed - Metallica",
    "My Friend Of Misery - Metallica",
    "The Struggle Within - Metallica",
    "Creeping Death - Metallica",
    "Seek And Destroy - Metallica",
    "Whiplash - Metallica",
    "Battery - Metallica",
    "Damage Inc. - Metallica",
    "Welcome Home - Metallica",
    "Disposable Heroes - Metallica",
    "Leper Messiah - Metallica",
    "Orion - Metallica",
    "Anarchy In The U.K. - Sex Pistols",
    "God Save The Queen - Sex Pistols",
    "Walk On The Wild Side - Lou Reed",
    "Perfect Day - Lou Reed",
    "Life On Mars? - David Bowie",
    "Young Americans - David Bowie",
    "Fame - David Bowie",
    "Golden Years - David Bowie",
    "China Girl - David Bowie",
    "Suffragette City - David Bowie",
    "Changes - David Bowie",
    "The Jean Genie - David Bowie",
    "Moonage Daydream - David Bowie",
    "Fashion - David Bowie",
    "Cat People - David Bowie",
    "Blue Jean - David Bowie",
    "Dancing In The Street - David Bowie ft Mick Jagger",
    "Garota De Ipanema - João Gilberto ft Stan Getz",
    "Baianá - Bakermat",
    "Rampampam - Minelli",
    "Bailando - Enrique Iglesias ft Gente De Zona, Descemer Bueno",
    "Travesuras - Nicky Jam",
    "Livin' La Vida Loca - Ricky Martin",
    "Shake Your Bon-Bon - Ricky Martin",
    "Nobody Wants To Be Lonely - Ricky Martin ft Christina Aguilera",
    "Blood Sweat & Tears - BTS",
    "Unforgiven - LE SSERAFIM ft Nile Rodgers",
    "I Can't Stop Me - TWICE",
    "Cry For Me - TWICE",
    "Paprika - Foorin",
    "Guren No Yumiya - Linked Horizon",
    "Unravel - TK from Ling Tosite Sigure",
    "A Cruel Angel's Thesis - Yoko Takahashi",
    "The Real Folk Blues - Seatbelts",
    "Tank! - Seatbelts",
    "Again - YUI",
    "Silhouette - KANA-BOON",
    "Blue Bird - Ikimonogakari",
    "We Are! - Hiroshi Kitadani",
    "Zitti E Buoni - Måneskin",
    "Cake By The Ocean - DNCE",
    "Can't Stop The Feeling! - Justin Timberlake",
    "Blurred Lines - Robin Thicke ft T.I., Pharrell",
    "Get Lucky - Daft Punk ft Pharrell Williams",
]
