# Faixas adicionais (Artist Title) — lote final para meta +3000
FINAL_HITS: list[str] = [
    "Studio Ghibli Spirited Away Always With Me",
    "Studio Ghibli My Neighbor Totoro Main Theme",
    "Naruto Blue Bird",
    "Naruto Silhouette",
    "One Piece We Are",
    "One Piece Binks Sake",
    "Attack on Titan Guren no Yumiya",
    "Attack on Titan Shinzou wo Sasageyo",
    "Demon Slayer Gurenge",
    "Demon Slayer Kizuna no Kiseki",
    "Jujutsu Kaisen Kaikai Kitan",
    "Chainsaw Man Kick Back",
    "Spy x Family Mixed Nuts",
    "Death Note The World",
    "Death Note Light Theme",
    "Evangelion A Cruel Angel's Thesis",
    "Cowboy Bebop Tank",
    "Sailor Moon Moonlight Densetsu",
    "Dragon Ball Cha-La Head-Cha-La",
    "Pokemon Theme Song",
    "Digimon Brave Heart",
    "Yu-Gi-Oh Season 0",
    "Hunter x Hunter Departure",
    "Fullmetal Alchemist Again",
    "Fullmetal Alchemist Brotherhood Again",
    "Bleach Number One",
    "My Hero Academia Peace Sign",
    "Tokyo Ghoul Unravel",
    "Sword Art Online Crossing Field",
    "Your Name Zenzenzense",
    "Weathering With You Grand Escape",
    "Suzume Suzume",
    "Minecraft Sweden C418",
    "Minecraft Wet Hands C418",
    "Tetris Theme Korobeiniki",
    "Super Mario Bros Ground Theme",
    "Legend of Zelda Main Theme",
    "Sonic Green Hill Zone",
    "Pac-Man Theme",
    "Street Fighter Guile Theme",
    "Final Fantasy VII Main Theme",
    "Final Fantasy VIII Eyes On Me",
    "Final Fantasy X To Zanarkand",
    "Kingdom Hearts Simple and Clean",
    "Metal Gear Solid Main Theme",
    "Halo Theme",
    "God of War Main Theme",
    "The Last of Us Main Theme",
    "Undertale Megalovania",
    "Portal Still Alive",
    "Portal 2 Want You Gone",
    "Baba O Riley The Who",
    "Smells Like Teen Spirit Nirvana",
    "Wonderwall Oasis",
    "Creep Radiohead",
    "Yellow Coldplay",
    "Everlong Foo Fighters",
    "Under The Bridge Red Hot Chili Peppers",
    "Sweet Child O Mine Guns N Roses",
    "Stairway To Heaven Led Zeppelin",
    "Bohemian Rhapsody Queen",
    "Hotel California Eagles",
    "Imagine John Lennon",
    "Hey Jude The Beatles",
    "Billie Jean Michael Jackson",
    "Like A Rolling Stone Bob Dylan",
    "Respect Aretha Franklin",
    "What's Going On Marvin Gaye",
    "Good Vibrations The Beach Boys",
    "Johnny B Goode Chuck Berry",
    "What A Wonderful World Louis Armstrong",
    "My Way Frank Sinatra",
    "New York New York Frank Sinatra",
    "Fly Me To The Moon Frank Sinatra",
    "Unchained Melody The Righteous Brothers",
    "Stand By Me Ben E King",
    "I Will Survive Gloria Gaynor",
    "Dancing Queen ABBA",
    "Stayin Alive Bee Gees",
    "I Will Always Love You Whitney Houston",
    "My Heart Will Go On Celine Dion",
    "I Wanna Dance With Somebody Whitney Houston",
    "Vision Of Love Mariah Carey",
    "Hero Mariah Carey",
    "Baby One More Time Britney Spears",
    "Genie In A Bottle Christina Aguilera",
    "Bye Bye Bye NSYNC",
    "I Want It That Way Backstreet Boys",
    "Wannabe Spice Girls",
    "No Scrubs TLC",
    "Waterfalls TLC",
    "Say My Name Destiny's Child",
    "In Da Club 50 Cent",
    "Lose Yourself Eminem",
    "Stan Eminem",
    "Gold Digger Kanye West",
    "Stronger Kanye West",
    "Empire State Of Mind Jay-Z",
    "Hotline Bling Drake",
    "God's Plan Drake",
    "HUMBLE Kendrick Lamar",
    "Alright Kendrick Lamar",
    "SICKO MODE Travis Scott",
    "goosebumps Travis Scott",
    "Old Town Road Lil Nas X",
    "Truth Hurts Lizzo",
    "Bad Guy Billie Eilish",
    "Drivers License Olivia Rodrigo",
    "Thank U Next Ariana Grande",
    "7 rings Ariana Grande",
    "Umbrella Rihanna",
    "We Found Love Rihanna",
    "Single Ladies Beyonce",
    "Crazy In Love Beyonce",
    "Halo Beyonce",
    "Poker Face Lady Gaga",
    "Bad Romance Lady Gaga",
    "Shallow Lady Gaga",
    "Firework Katy Perry",
    "Roar Katy Perry",
    "Rolling In The Deep Adele",
    "Someone Like You Adele",
    "Hello Adele",
    "Shape Of You Ed Sheeran",
    "Perfect Ed Sheeran",
    "Thinking Out Loud Ed Sheeran",
    "Blinding Lights The Weeknd",
    "Starboy The Weeknd",
    "Can't Feel My Face The Weeknd",
    "Save Your Tears The Weeknd",
    "Levitating Dua Lipa",
    "Don't Start Now Dua Lipa",
    "New Rules Dua Lipa",
    "Watermelon Sugar Harry Styles",
    "As It Was Harry Styles",
    "Sign Of The Times Harry Styles",
    "Peaches Justin Bieber",
    "Sorry Justin Bieber",
    "Love Yourself Justin Bieber",
    "Despacito Luis Fonsi",
    "Bailando Enrique Iglesias",
    "Hips Don't Lie Shakira",
    "Waka Waka Shakira",
    "La Bamba Ritchie Valens",
    "Volare Dean Martin",
    "That's Amore Dean Martin",
    "Mambo No 5 Lou Bega",
    "Macarena Los Del Rio",
    "Gangnam Style PSY",
    "Gentleman PSY",
    "Butter BTS",
    "Dynamite BTS",
    "Kill This Love BLACKPINK",
    "How You Like That BLACKPINK",
    "Attention NewJeans",
    "Hype Boy NewJeans",
    "Next Level aespa",
    "Tomboy GIDLE",
    "Love Dive IVE",
    "Cupid FIFTY FIFTY",
    "Rich Man LISA",
    "Money LISA",
    "On The Ground Rosé",
    "APT Rosé Bruno Mars",
    "Seven Jungkook",
    "Gurenge LiSA",
    "Lemon Kenshi Yonezu",
    "Pretender Official HIGE DANdism",
    "Yoru ni Kakeru YOASOBI",
    "Idol YOASOBI",
    "First Love Hikaru Utada",
    "PONPONPON Kyary Pamyu Pamyu",
    "Koi Gen Hoshino",
    "Paprika Foorin",
    "Livin La Vida Loca Ricky Martin",
    "Maria Ricky Martin",
    "Bamboleo Gipsy Kings",
    "Volare Nel Blu Di Pinto Di Blu",
    "Con Te Partirò Andrea Bocelli",
    "Time To Say Goodbye Andrea Bocelli Sarah Brightman",
    "The Prayer Celine Dion Andrea Bocelli",
    "Nessun Dorma Luciano Pavarotti",
    "O Sole Mio Luciano Pavarotti",
    "La Vie En Rose Edith Piaf",
    "Non Je Ne Regrette Rien Edith Piaf",
    "La Bohème Charles Aznavour",
    "Papaoutai Stromae",
    "Alors On Danse Stromae",
    "Dernière Danse Indila",
    "Je Veux Zaz",
    "Pumped Up Kicks Foster The People",
    "Somebody That I Used To Know Gotye",
    "Royals Lorde",
    "Team Lorde",
    "Riptide Vance Joy",
    "Ho Hey The Lumineers",
    "Little Talks Of Monsters and Men",
    "Shut Up And Dance Walk The Moon",
    "Come On Eileen Dexys Midnight Runners",
    "Don't You Forget About Me Simple Minds",
    "Take On Me a-ha",
    "The Final Countdown Europe",
    "Total Eclipse Of The Heart Bonnie Tyler",
    "I Love Rock And Roll Joan Jett",
    "Hit Me With Your Best Shot Pat Benatar",
    "We're Not Gonna Take It Twisted Sister",
    "Cherry Pie Warrant",
    "More Than Words Extreme",
    "To Be With You Mr Big",
    "Wind Of Change Scorpions",
    "Nothing Else Matters Metallica",
    "Enter Sandman Metallica",
    "Back In Black AC/DC",
    "Thunderstruck AC/DC",
    "Paranoid Black Sabbath",
    "Iron Man Black Sabbath",
    "Breaking The Law Judas Priest",
    "Run To The Hills Iron Maiden",
    "Crazy Train Ozzy Osbourne",
    "Pour Some Sugar On Me Def Leppard",
    "Livin On A Prayer Bon Jovi",
    "You Give Love A Bad Name Bon Jovi",
    "It's My Life Bon Jovi",
    "Dream On Aerosmith",
    "I Don't Want To Miss A Thing Aerosmith",
    "November Rain Guns N Roses",
    "Welcome To The Jungle Guns N Roses",
    "Every Breath You Take The Police",
    "Roxanne The Police",
    "Message In A Bottle The Police",
    "With Or Without You U2",
    "One U2",
    "Beautiful Day U2",
    "Losing My Religion R.E.M.",
    "Everybody Hurts R.E.M.",
    "Zombie The Cranberries",
    "Linger The Cranberries",
    "Black Hole Sun Soundgarden",
    "Man In The Box Alice In Chains",
    "Interstate Love Song Stone Temple Pilots",
    "Glycerine Bush",
    "Lightning Crashes Live",
    "Shine Collective Soul",
    "Iris Goo Goo Dolls",
    "Semi-Charmed Life Third Eye Blind",
    "All Star Smash Mouth",
    "Flagpole Sitta Harvey Danger",
    "Basket Case Green Day",
    "American Idiot Green Day",
    "Boulevard Of Broken Dreams Green Day",
    "All The Small Things Blink-182",
    "In The End Linkin Park",
    "Numb Linkin Park",
    "Bring Me To Life Evanescence",
    "Chop Suey System Of A Down",
    "Killing In The Name Rage Against The Machine",
    "Schism Tool",
    "Closer Nine Inch Nails",
    "Mr Brightside The Killers",
    "Do I Wanna Know Arctic Monkeys",
    "Last Nite The Strokes",
    "Starlight Muse",
    "Wonderwall Oasis",
    "Song 2 Blur",
    "Common People Pulp",
    "Teardrop Massive Attack",
    "Glory Box Portishead",
    "Feel Good Inc Gorillaz",
    "Paper Planes M.I.A.",
    "Kids MGMT",
    "Electric Feel MGMT",
    "1901 Phoenix",
    "Heat Waves Glass Animals",
    "Pompeii Bastille",
    "Radioactive Imagine Dragons",
    "Believer Imagine Dragons",
    "Take Me To Church Hozier",
    "The Night We Met Lord Huron",
    "Someone You Loved Lewis Capaldi",
    "Before You Go Lewis Capaldi",
    "Let Her Go Passenger",
    "You're Beautiful James Blunt",
    "Chasing Cars Snow Patrol",
    "Yellow Coldplay",
    "Fix You Coldplay",
    "The Scientist Coldplay",
    "Viva La Vida Coldplay",
    "Clocks Coldplay",
    "Paradise Coldplay",
    "Everlong Foo Fighters",
    "Best Of You Foo Fighters",
    "Learn To Fly Foo Fighters",
    "Smells Like Teen Spirit Nirvana",
    "Come As You Are Nirvana",
    "Heart-Shaped Box Nirvana",
    "Under The Bridge Red Hot Chili Peppers",
    "Californication Red Hot Chili Peppers",
    "Can't Stop Red Hot Chili Peppers",
    "Scar Tissue Red Hot Chili Peppers",
    "Otherside Red Hot Chili Peppers",
    "Karma Police Radiohead",
    "Paranoid Android Radiohead",
    "No Surprises Radiohead",
    "Fake Plastic Trees Radiohead",
    "High and Dry Radiohead",
    "Street Spirit Radiohead",
    "Wake Up Arcade Fire",
    "The Suburbs Arcade Fire",
    "A-Punk Vampire Weekend",
    "Harmony Hall Vampire Weekend",
    "The Less I Know The Better Tame Impala",
    "Let It Happen Tame Impala",
    "Feels Like We Only Go Backwards Tame Impala",
    "Dance Yrself Clean LCD Soundsystem",
    "All My Friends LCD Soundsystem",
    "Midnight City M83",
    "Wait M83",
    "Clarity Zedd Foxes",
    "The Middle Zedd",
    "Wake Me Up Avicii",
    "Levels Avicii",
    "Titanium David Guetta",
    "Don't You Worry Child Swedish House Mafia",
    "Animals Martin Garrix",
    "Lean On Major Lazer",
    "Turn Down For What DJ Snake",
    "One More Time Daft Punk",
    "Get Lucky Daft Punk",
    "Harder Better Faster Stronger Daft Punk",
    "Galvanize The Chemical Brothers",
    "Praise You Fatboy Slim",
    "Right Here Right Now Fatboy Slim",
    "Sandstorm Darude",
    "Rhythm Is A Dancer Snap",
    "What Is Love Haddaway",
    "Blue Eiffel 65",
    "Barbie Girl Aqua",
    "Rhythm Of The Night Corona",
    "All That She Wants Ace of Base",
    "The Sign Ace of Base",
    "Take On Me a-ha",
    "It Must Have Been Love Roxette",
    "Listen To Your Heart Roxette",
    "The Final Countdown Europe",
    "Carrie Europe",
    "Eye Of The Tiger Survivor",
    "Burning Heart Survivor",
    "Don't Stop Believin Journey",
    "Separate Ways Journey",
    "Open Arms Journey",
    "Faithfully Journey",
    "Any Way You Want It Journey",
    "I Want To Know What Love Is Foreigner",
    "Waiting For A Girl Like You Foreigner",
    "Cold As Ice Foreigner",
    "More Than A Feeling Boston",
    "Peace of Mind Boston",
    "Carry On Wayward Son Kansas",
    "Dust In The Wind Kansas",
    "Alone Heart",
    "Barracuda Heart",
    "Hit Me With Your Best Shot Pat Benatar",
    "Love Is A Battlefield Pat Benatar",
    "I Love Rock And Roll Joan Jett",
    "Heart Of Glass Blondie",
    "Call Me Blondie",
    "One Way Or Another Blondie",
    "Drive The Cars",
    "Just What I Needed The Cars",
    "Hungry Like The Wolf Duran Duran",
    "Rio Duran Duran",
    "Ordinary World Duran Duran",
    "Everybody Wants To Rule The World Tears For Fears",
    "Shout Tears For Fears",
    "Sweet Dreams Eurythmics",
    "Here Comes The Rain Again Eurythmics",
    "Would I Lie To You Eurythmics",
    "Smooth Operator Sade",
    "No Ordinary Love Sade",
    "Kiss From A Rose Seal",
    "I Try Macy Gray",
    "Fallin Alicia Keys",
    "No One Alicia Keys",
    "If I Ain't Got You Alicia Keys",
    "Girl On Fire Alicia Keys",
    "All Of Me John Legend",
    "Ordinary People John Legend",
    "Just The Way You Are Bruno Mars",
    "Grenade Bruno Mars",
    "Locked Out Of Heaven Bruno Mars",
    "Uptown Funk Mark Ronson Bruno Mars",
    "24K Magic Bruno Mars",
    "That's What I Like Bruno Mars",
    "Happy Pharrell Williams",
    "Cry Me A River Justin Timberlake",
    "SexyBack Justin Timberlake",
    "Mirrors Justin Timberlake",
    "Can't Stop The Feeling Justin Timberlake",
    "Havana Camila Cabello",
    "Señorita Shawn Mendes Camila Cabello",
    "Stitches Shawn Mendes",
    "Treat You Better Shawn Mendes",
    "Senorita Shawn Mendes",
    "There's Nothing Holdin Me Back Shawn Mendes",
    "Sorry Not Sorry Demi Lovato",
    "Skyscraper Demi Lovato",
    "Flowers Miley Cyrus",
    "Wrecking Ball Miley Cyrus",
    "Party In The USA Miley Cyrus",
    "Come And Get It Selena Gomez",
    "Lose You To Love Me Selena Gomez",
    "Calm Down Rema Selena Gomez",
    "Industry Baby Lil Nas X Jack Harlow",
    "Montero Lil Nas X",
    "Say So Doja Cat",
    "Paint The Town Red Doja Cat",
    "Kiss Me More Doja Cat",
    "Savage Megan Thee Stallion",
    "WAP Cardi B Megan Thee Stallion",
    "Bodak Yellow Cardi B",
    "Super Bass Nicki Minaj",
    "Anaconda Nicki Minaj",
    "Starships Nicki Minaj",
    "Kill Bill SZA",
    "Snooze SZA",
    "Good Days SZA",
    "Heartbreak Anniversary Giveon",
    "Get You Daniel Caesar",
    "Best Part Daniel Caesar H.E.R.",
    "Thinkin Bout You Frank Ocean",
    "Redbone Childish Gambino",
    "This Is America Childish Gambino",
    "See You Again Tyler The Creator",
    "EARFQUAKE Tyler The Creator",
    "Self Care Mac Miller",
    "Circles Mac Miller",
    "Congratulations Post Malone",
    "Rockstar Post Malone",
    "Sunflower Post Malone",
    "Circles Post Malone",
    "Better Now Post Malone",
    "Lucid Dreams Juice WRLD",
    "Sad XXXTentacion",
    "Moonlight XXXTentacion",
    "XO Tour Llif3 Lil Uzi Vert",
    "Magnolia Playboi Carti",
    "Dior Pop Smoke",
    "The Box Roddy Ricch",
    "Rockstar DaBaby",
    "Suge DaBaby",
    "Bank Account 21 Savage",
    "a lot 21 Savage",
    "Not Like Us Kendrick Lamar",
    "Family Affair Mary J Blige",
    "No More Drama Mary J Blige",
    "Real Love Mary J Blige",
    "Doo Wop That Thing Lauryn Hill",
    "Killing Me Softly Fugees",
    "Ready or Not Fugees",
    "Gin And Juice Snoop Dogg",
    "Drop It Like It's Hot Snoop Dogg",
    "Still D.R.E. Dr Dre",
    "The Next Episode Dr Dre",
    "California Love 2Pac",
    "Changes 2Pac",
    "Dear Mama 2Pac",
    "Juicy The Notorious B.I.G.",
    "Hypnotize The Notorious B.I.G.",
    "Mo Money Mo Problems The Notorious B.I.G.",
    "Hey Ya OutKast",
    "Ms Jackson OutKast",
    "C.R.E.A.M. Wu-Tang Clan",
    "Fight The Power Public Enemy",
    "No Sleep Till Brooklyn Beastie Boys",
    "Sabotage Beastie Boys",
    "Intergalactic Beastie Boys",
    "Walk This Way Run-DMC",
    "U Can't Touch This MC Hammer",
    "Ice Ice Baby Vanilla Ice",
    "Jump Around House of Pain",
    "Insane In The Brain Cypress Hill",
    "Straight Outta Compton N.W.A",
    "It Was A Good Day Ice Cube",
    "Ridin Chamillionaire",
    "Crank That Soulja Boy",
    "Teach Me How To Dougie Cali Swag District",
    "Replay Iyaz",
    "Whatcha Say Jason Derulo",
    "Low Flo Rida",
    "Good Feeling Flo Rida",
    "Party Rock Anthem LMFAO",
    "Sexy And I Know It LMFAO",
    "I Gotta Feeling Black Eyed Peas",
    "Boom Boom Pow Black Eyed Peas",
    "Where Is The Love Black Eyed Peas",
    "Promiscuous Nelly Furtado",
    "Say It Right Nelly Furtado",
    "Maneater Nelly Furtado",
    "Temperature Sean Paul",
    "Get Busy Sean Paul",
    "It Wasn't Me Shaggy",
    "Angel Shaggy",
    "Boombastic Shaggy",
    "Red Red Wine UB40",
    "Bad Boys Inner Circle",
    "Three Little Birds Bob Marley",
    "No Woman No Cry Bob Marley",
    "Redemption Song Bob Marley",
    "Is This Love Bob Marley",
    "Welcome To Jamrock Damian Marley",
    "Toast Koffee",
    "One Love Bob Marley",
    "Could You Be Loved Bob Marley",
    "Jamming Bob Marley",
    "Buffalo Soldier Bob Marley",
    "Stir It Up Bob Marley",
    "I Shot The Sheriff Bob Marley",
    "Get Up Stand Up Bob Marley",
    "Sweat A La La La La Long Inner Circle",
    "Kingston Town UB40",
    "Pass The Dutchie Musical Youth",
    "Electric Avenue Eddy Grant",
    "I Don't Want To Miss A Thing Aerosmith",
    "Janie's Got A Gun Aerosmith",
    "Sweet Emotion Aerosmith",
    "Walk This Way Aerosmith",
    "Crazy Aerosmith",
    "Love In An Elevator Aerosmith",
    "Joker Steve Miller Band",
    "The Joker Steve Miller Band",
    "Fly Like An Eagle Steve Miller Band",
    "Take The Money And Run Steve Miller Band",
    "Abracadabra Steve Miller Band",
    "Black Magic Woman Santana",
    "Smooth Santana Rob Thomas",
    "Maria Maria Santana",
    "Oye Como Va Santana",
    "Evil Ways Santana",
    "Soul Sacrifice Santana",
    "Samba Pa Ti Santana",
    "Everybody's Everything Santana",
    "Winning Santana",
    "Hold On Santana",
    "Corazon Espinado Santana",
    "The Game of Love Santana Michelle Branch",
]
