#!/usr/bin/env python3
"""Gera scripts/extra_songs_bulk.txt com milhares de hits (Artist Title)."""
from __future__ import annotations

from pathlib import Path

OUT = Path(__file__).resolve().parent / "extra_songs_bulk.txt"

# artist -> list of song titles (sem repetir artista no titulo)
BULK: dict[str, list[str]] = {}

def add(artist: str, *titles: str) -> None:
    BULK.setdefault(artist, []).extend(titles)


# --- K-POP / J-POP / ASIA ---
add("BTS", "Dynamite", "Butter", "Permission To Dance", "Boy With Luv", "DNA", "Fake Love",
    "Blood Sweat and Tears", "Spring Day", "IDOL", "ON", "Life Goes On", "Yet To Come", "Take Two")
add("BLACKPINK", "DDU-DU DDU-DU", "Kill This Love", "How You Like That", "Pink Venom", "Shut Down",
    "As If It's Your Last", "Playing With Fire", "Lovesick Girls", "Whistle")
add("PSY", "Gangnam Style", "Gentleman", "Daddy", "New Face")
add("BIGBANG", "Fantastic Baby", "Bang Bang Bang", "Loser", "FXXK IT", "Still Life")
add("G-Dragon", "Crayon", "Crooked", "Who You")
add("2NE1", "I Am The Best", "Lonely", "Come Back Home", "Fire")
add("Girls Generation", "Gee", "The Boys", "I Got A Boy", "Oh")
add("TWICE", "Cheer Up", "TT", "Fancy", "Feel Special", "Talk That Talk", "Set Me Free")
add("ITZY", "Dalla Dalla", "Wannabe", "Not Shy", "Loco", "Sneakers")
add("aespa", "Next Level", "Savage", "Spicy", "Drama", "Supernova")
add("NewJeans", "Attention", "Hype Boy", "Ditto", "OMG", "Super Shy", "ETA", "How Sweet")
add("IVE", "Love Dive", "After LIKE", "I AM", "Kitsch")
add("(G)I-DLE", "Tomboy", "Nxde", "Queencard", "Super Lady", "Latata")
add("Stray Kids", "God's Menu", "Back Door", "Maniac", "S-Class", "LALALALA")
add("SEVENTEEN", "Don't Wanna Cry", "Left and Right", "Super", "God of Music")
add("EXO", "Growl", "Call Me Baby", "Love Shot", "Monster", "Ko Ko Bop")
add("SHINee", "Replay", "Ring Ding Dong", "View", "Sherlock", "Don't Call Me")
add("Super Junior", "Sorry Sorry", "Mr Simple", "Mamacita")
add("TVXQ", "Mirotic", "Keep Your Head Down")
add("IU", "Good Day", "Palette", "Celebrity", "Through the Night", "Love poem")
add("AKMU", "How can I love the heartbreak", "Dinosaur", "Nakka")
add("Red Velvet", "Red Flavor", "Psycho", "Feel My Rhythm", "Queendom")
add("MAMAMOO", "HIP", "Starry Night", "Yes I Am")
add("Sunmi", "Gashina", "Heroine", "Siren")
add("HyunA", "Bubble Pop", "Red", "I'm Not Cool")
add("CL", "Hello Bitches", "Lifted", "Spicy")
add("BLACKPINK Jennie", "Solo", "You and Me")
add("BLACKPINK Lisa", "Money", "LALISA")
add("Rosé", "On The Ground", "APT")
add("Jungkook", "Seven", "Standing Next To You", "Golden")
add("V", "Love Me Again", "Slow Dancing")
add("Agust D", "Haegeum", "Daechwita")
add("LE SSERAFIM", "ANTIFRAGILE", "UNFORGIVEN", "Perfect Night", "EASY", "CRAZY")
add("ENHYPEN", "Given-Taken", "Fever", "Bite Me", "Polaroid Love")
add("TOMORROW X TOGETHER", "Crown", "0X1=LOVESONG", "Sugar Rush Ride", "Deja Vu")
add("NCT 127", "Kick It", "Sticker", "Fact Check")
add("NCT DREAM", "Candy", "Hello Future", "Hot Sauce")
add("ATEEZ", "Answer", "Bouncy", "Guerrilla")
add("KARA", "Mister", "Step")
add("Wonder Girls", "Nobody", "Tell Me")
add("BoA", "No.1", "Only One", "Atlantis")
add("Hikaru Utada", "First Love", "Flavor Of Life", "Automatic", "One Last Kiss")
add("YOASOBI", "Yoru ni Kakeru", "Idol", "Ayase Racing into the Night")
add("LiSA", "Gurenge", "Homura", "Akeboshi")
add("Kenshi Yonezu", "Lemon", "Paprika", "KICK BACK", "Loser")
add("Official HIGE DANdism", "Pretender", "Cry Baby", "Mixed Nuts")
add("King Gnu", "Hakujitsu", "Ichizu", "Specialz")
add("Mrs GREEN APPLE", "WanteD WanteD", "Soranji", "Lilac")
add("Ado", "Usseewa", "New Genesis", "Show")
add("Aimer", "Brave Shine", "Ref:rain", "Kataomoi")
add("ONE OK ROCK", "Wherever you are", "The Beginning", "We Are")
add("X Japan", "Endless Rain", "Art of Life", "Kurenai")
add("L'Arc-en-Ciel", "Driver's High", "Ready Steady Go", "Honey")
add("Namie Amuro", "Can You Celebrate", "Body Feels EXIT")
add("Ayumi Hamasaki", "M", "Dearest", "Seasons")
add("SMAP", "Sekai ni Hitotsu Dake no Hana", "Lion Heart")
add("Arashi", "Love So Sweet", "Happiness", "Truth")
add("AKB48", "Heavy Rotation", "Koi Suru Fortune Cookie")
add("Perfume", "Polyrhythm", "Chocolate Disco", "Flash")
add("Kyary Pamyu Pamyu", "PONPONPON", "Fashion Monster")
add("Gen Hoshino", "Koi", "Comedy", "Dramatic")
add("Sakanaction", "Shin Takarajima", "Boku to Hana")
add("Radwimps", "Zenzenzense", "Sparkle", "Grand Escape")
add("Fujii Kaze", "Kirari", "Shinunoga E-Wa", "Matsuri")
add("Vaundy", "Kaiju", "odoriko", "Tokyo Flash")
add("imase", "NIGHT DANCER", "Billy Billy")
add("Yuuri", "Betelgeuse", "Dry Flower")
add("Saucy Dog", "Shion", "Cinderella Boy")
add("back number", "Christmas Song", "Heroine", "Instant")
add("SPITZ", "Cherry", "Robinson")
add("BUMP OF CHICKEN", "Karma", "Sailing Day")
add("GReeeeN", "Ai Uta", "Kiseki")
add("EXILE", "Lovers Again", "Ti Amo")
add("Jay Chou", "Qi Li Xiang", "Blue and White Porcelain", "Sunny Day")
add("JJ Lin", "Jiang Nan", "Practice Love", "Twilight")
add("G.E.M.", "Light Years Away", "Bubble", "Tang")
add("Mayday", "Stubborn", "Party Animal", "Leaving Now")
add("Faye Wong", "Red Bean", "Legend", "Easily Hurt Woman")
add("Teresa Teng", "The Moon Represents My Heart", "Sweet Honey")
add("Beyond", "Glorious Years", "Really Love You")
add("Leslie Cheung", "Monica", "Wind Continues Blowing")
add("Jacky Cheung", "Kiss Goodbye", "Wishing We Last Forever")
add("Eason Chan", "Ten Years", "Fujian", "Lonely Heart")
add("Ariana Grande", "Focus", "God Is A Woman", "Breathin", "Monopoly")
add("Taylor Swift", "Love Story", "You Belong With Me", "Wildest Dreams",
    "Style", "Delicate", "Lavender Haze", "Karma", "Fortnight")
add("Drake", "Hotline Bling", "One Dance", "Passionfruit", "Hold On We're Going Home",
    "Started From The Bottom", "Nice For What", "In My Feelings", "Toosie Slide")
add("Kendrick Lamar", "HUMBLE", "DNA", "Swimming Pools", "Bitch Don't Kill My Vain",
    "King Kunta", "Alright", "Money Trees")
add("Travis Scott", "Highest In The Room", "Yosemite", "Butterfly Effect", "FEIN")
add("Metro Boomin", "Creepin", "Superhero", "Too Many Nights")
add("Future", "Mask Off", "March Madness", "Low Life", "Life Is Good")
add("Migos", "Bad and Boujee", "Walk It Talk It", "Stir Fry", "T-Shirt")
add("Quavo", "Workin Me", "Honey Bun")
add("Offset", "Clout", "Ric Flair Drip")
add("Cardi B", "I Like It", "WAP", "Be Careful", "Press", "Up")
add("Megan Thee Stallion", "Savage", "Body", "HISS", "Cobra")
add("Nicki Minaj", "Super Bass", "Anaconda", "Starships", "Moment 4 Life",
    "Beez In The Trap", "Chun-Li", "Barbie World")
add("Ice Spice", "Munch", "In Ha Mood", "Think U The Shit")
add("Sexyy Red", "SkeeYee", "Pound Town", "Hood Rats")
add("GloRilla", "Tomorrow 2", "F.N.F.", "TGIF")
add("Latto", "Big Energy", "Lottery", "Put It On Da Floor")
add("Coi Leray", "Players", "Blick Blick", "No More Parties")
add("Saweetie", "My Type", "Best Friend", "Tap In")
add("City Girls", "Act Up", "Twerkulator")
add("Doja Cat", "Mooo", "Cybersex", "Streets", "Get Into It")
add("SZA", "Kill Bill", "Snooze", "Shirt", "Saturn", "BMF")
add("Summer Walker", "Playing Games", "Girls Need Love", "Come Thru")
add("H.E.R.", "Best Part", "Focus", "Damage", "Slide")
add("Daniel Caesar", "Get You", "Best Part", "Who Hurt You")
add("PARTYNEXTDOOR", "Break From Toronto", "Recognize", "With Me")
add("Brent Faiyaz", "Trust", "Dead Man Walking", "Gravity")
add("Giveon", "Heartbreak Anniversary", "For Tonight")
add("Lucky Daye", "Roll Some Mo", "Over", "That's You")
add("6lack", "PRBLMS", "Free", "Calling My Phone")
add("Bryson Tiller", "Don't", "Exchange", "Right My Wrongs")
add("Jeremih", "Birthday Sex", "Oui", "Don't Tell Em")
add("Tinashe", "2 On", "Nasty", "Needs")
add("Kehlani", "Gangsta", "Distraction", "Nights Like This")
add("Normani", "Motivation", "Wild Side", "Fair")
add("Victoria Monét", "On My Mama", "Alright")
add("Chlöe", "Have Mercy", "Surprise", "Treat Me")
add("Halle", "Angel", "Part of Your World")
add("PinkPantheress", "Boy's a liar", "Pain", "Break It Off", "Nice to meet you")
add("Raye", "Escapism", "Black Mascara", "Prada")
add("Mabel", "Don't Call Me Up", "Mad Love")
add("Anne-Marie", "2002", "Rockabye", "Birthday")
add("Rag'n'Bone Man", "Human", "Skin")
add("Sam Smith", "Too Good At Goodbyes", "Dancing With A Stranger", "I'm Not The Only One")
add("Calvin Harris", "Feel So Close", "Summer", "This Is What You Came For", "Promises", "One Kiss")
add("David Guetta", "Titanium", "Without You", "Hey Mama", "2U", "I'm Good")
add("Swedish House Mafia", "Don't You Worry Child", "Save The World", "Moth To A Flame")
add("Avicii", "Wake Me Up", "Levels", "The Nights", "Waiting For Love", "Hey Brother")
add("Martin Garrix", "Animals", "In The Name Of Love", "Scared To Be Lonely")
add("Tiësto", "Red Lights", "The Business", "10:35")
add("Hardwell", "Spaceman", "Apollo", "Follow Me")
add("Armin van Buuren", "This Is What It Feels Like", "Blah Blah Blah")
add("Above and Beyond", "Sun and Moon", "Thing Called Love")
add("Deadmau5", "Ghosts n Stuff", "Strobe", "I Remember")
add("Skrillex", "Scary Monsters And Nice Sprites", "Bangarang", "Where Are U Now")
add("Daft Punk", "One More Time", "Harder Better Faster Stronger", "Get Lucky",
    "Around The World", "Digital Love", "Instant Crush")
add("Justice", "D.A.N.C.E.", "We Are Your Friends", "Genesis")
add("The Chemical Brothers", "Galvanize", "Block Rockin Beats", "Hey Boy Hey Girl")
add("Fatboy Slim", "Praise You", "Right Here Right Now", "Weapon Of Choice")
add("Basement Jaxx", "Where's Your Head At", "Red Alert")
add("Prodigy", "Firestarter", "Breathe", "Smack My Bitch Up")
add("Underworld", "Born Slippy", "Two Months Off")
add("Orbital", "Halcyon", "Chime")
add("Aphex Twin", "Windowlicker", "Avril 14th")
add("Boards of Canada", "Dayvan Cowboy", "Roygbiv")
add("Moby", "Porcelain", "Natural Blues", "Why Does My Heart Feel So Bad")
add("Faithless", "Insomnia", "God Is A DJ")
add("Robert Miles", "Children")
add("Darude", "Sandstorm")
add("ATB", "9 PM Till I Come")
add("Paul van Dyk", "For An Angel")
add("Sash", "Encore Une Fois", "Ecuador")
add("Scooter", "How Much Is The Fish", "Maria", "Hyper Hyper")
add("Snap", "Rhythm Is A Dancer", "The Power")
add("Haddaway", "What Is Love", "Life")
add("Corona", "Rhythm Of The Night", "Baby Baby")
add("Ace of Base", "All That She Wants", "The Sign", "Beautiful Life")
add("Aqua", "Barbie Girl", "Doctor Jones", "My Oh My")
add("Vengaboys", "We Like To Party", "Boom Boom Boom Boom")
add("Eiffel 65", "Blue Da Ba Dee", "Move Your Body")
add("Lasgo", "Something", "Alone")
add("Ian Van Dahl", "Castles In The Sky")
add("Gigi D'Agostino", "L'Amour Toujours", "Bla Bla Bla")
add("Yolanda Be Cool", "We No Speak Americano")
add("Stardust", "Music Sounds Better With You")
add("Modjo", "Lady Hear Me Tonight")
add("Bob Sinclar", "World Hold On", "Love Generation")
add("Cassius", "Toop Toop", "Feeling For You")
add("Phoenix", "1901", "Lisztomania", "Trying To Be Cool")
add("Two Door Cinema Club", "What You Know", "Changing Of The Seasons")
add("Foals", "My Number", "Mountain at My Gates")
add("Bombay Bicycle Club", "Shuffle", "Luna")
add("Alt-J", "Breezeblocks", "Left Hand Free", "In Cold Blood")
add("Bastille", "Pompeii", "Good Grief", "Happier")
add("Imagine Dragons", "Believer", "Natural", "Whatever It Takes", "Demons acoustic")
add("X Ambassadors", "Renegades", "Unsteady")
add("Walk The Moon", "Shut Up And Dance", "Anna Sun")
add("American Authors", "Best Day Of My Life", "Go Big Or Go Home")
add("Of Monsters and Men", "Little Talks", "Dirty Paws", "Mountain Sound")
add("Mumford and Sons", "The Cave", "I Will Wait", "Little Lion Man")
add("The Lumineers", "Ho Hey", "Ophelia", "Cleopatra")
add("Lord Huron", "The Night We Met", "Ends of the Earth")
add("Hozier", "Take Me To Church", "Someone New", "Eat Your Young")
add("Kaleo", "Way Down We Go", "All The Pretty Girls")
add("Nothing But Thieves", "Amsterdam", "Broken Machine")
add("Royal Blood", "Figure It Out", "Out of the Black")
add("Bring Me The Horizon", "Can You Feel My Heart", "Throne", "Follow You")
add("Parkway Drive", "Carrion", "Vice Grip")
add("Architects", "Doomsday", "Hereafter")
add("Bullet For My Valentine", "Tears Don't Fall", "Your Betrayal")
add("Avenged Sevenfold", "Hail To The King", "Nightmare", "Bat Country")
add("Disturbed", "Down With The Sickness", "The Sound Of Silence cover")
add("Five Finger Death Punch", "Wrong Side Of Heaven", "Jekyll And Hyde")
add("Shinedown", "Second Chance", "Sound Of Madness", "45")
add("Three Days Grace", "I Hate Everything About You", "Animal I Have Become")
add("Breaking Benjamin", "The Diary Of Jane", "Breath")
add("Papa Roach", "Last Resort", "Scars", "Getting Away With Murder")
add("Godsmack", "I Stand Alone", "Awake", "Whatever")
add("Staind", "It's Been Awhile", "Outside", "Mudshovel")
add("Seether", "Broken", "Fake It", "Remedy")
add("Hinder", "Lips Of An Angel", "Get Stoned")
add("Theory of a Deadman", "Bad Girlfriend", "Rx")
add("Nickelback", "How You Remind Me", "Photograph", "Rockstar", "If Today Was Your Last Day")
add("Creed", "With Arms Wide Open", "Higher", "My Sacrifice")
add("Alter Bridge", "Open Your Eyes", "Metalingus")
add("Volbeat", "Still Counting", "A Warrior's Call")
add("Ghost", "Square Hammer", "Dance Macabre", "Mary On A Cross")
add("Sabaton", "Primo Victoria", "The Last Stand", "To Hell And Back")
add("Powerwolf", "We Drink Your Blood", "Army of the Night")
add("Nightwish", "Nemo", "Amaranth", "Storytime")
add("Within Temptation", "Ice Queen", "Mother Earth")
add("Epica", "Cry For The Moon", "Storm the Sorrow")
add("Delain", "We Are The Others", "Suckerpunch")
add("Halestorm", "I Miss The Misery", "Love Bites")
add("The Pretty Reckless", "Make Me Wanna Die", "Heaven Knows")
add("Evanescence", "Bring Me To Life", "My Immortal", "Going Under", "Call Me When You're Sober")
add("Flyleaf", "All Around Me", "I'm So Sick")
add("Paramore", "Misery Business", "Still Into You", "The Only Exception", "Ain't It Fun", "Hard Times")
add("Panic At The Disco", "I Write Sins Not Tragedies", "High Hopes", "Nine In The Afternoon")
add("Fall Out Boy", "Sugar We're Goin Down", "Dance Dance", "Centuries", "My Songs Know What You Did")
add("My Chemical Romance", "Welcome To The Black Parade", "Helena", "Teenagers", "I'm Not Okay")
add("Taking Back Sunday", "MakeDamnSure", "Cute Without The E")
add("Brand New", "The Quiet Things That No One Ever Knows", "Sic Transit Gloria")
add("Jimmy Eat World", "The Middle", "Sweetness", "Pain")
add("Yellowcard", "Ocean Avenue", "Only One")
add("All Time Low", "Dear Maria Count Me In", "Weightless")
add("Mayday Parade", "Miserable At Best", "Jamie All Over")
add("State Champs", "Elevated", "Deadly Conversation")
add("Neck Deep", "Wish You Were Here", "In Bloom")
add("The Story So Far", "Roam", "Out Of It")
add("Knocked Loose", "Blinding Faith", "Moss Covers All")
add("Turnstile", "BLACKOUT", "NEVER ENOUGH", "T.L.C.")
add("Deftones", "Change In The House Of Flies", "My Own Summer", "Be Quiet And Drive")
add("Tool", "Schism", "Forty Six and 2", "Vicarious", "Stinkfist")
add("A Perfect Circle", "The Outsider", "Judith", "3 Libras")
add("Puscifer", "The Humbling River", "Vagina")
add("Nine Inch Nails", "Closer", "Hurt", "Head Like A Hole", "The Hand That Feeds")
add("Ministry", "Jesus Built My Hotrod", "N.W.O.")
add("KMFDM", "Juke Joint Jezebel", "A Drug Against War")
add("Rammstein", "Mein Herz Brennt", "Amerika", "Ohne Dich")
add("Powerwolf", "Resurrection By Erection")
add("Weezer", "Buddy Holly", "Say It Ain't So", "Island In The Sun", "Pork and Beans")
add("Pixies", "Where Is My Mind", "Debaser", "Here Comes Your Man")
add("Sonic Youth", "Teen Age Riot", "Kool Thing")
add("Pavement", "Cut Your Hair", "Range Life")
add("Built To Spill", "Car", "I Would Hurt A Fly")
add("Modest Mouse", "Float On", "Dashboard", "The World At Large")
add("Death Cab for Cutie", "I Will Follow You Into The Dark", "Soul Meets Body")
add("The Shins", "New Slang", "Simple Song", "Phantom Limb")
add("Bright Eyes", "First Day Of My Life", "Lua")
add("Iron and Wine", "Flightless Bird American Mouth", "Naked As We Came")
add("Bon Iver", "Skinny Love", "Holocene", "For Emma")
add("Sufjan Stevens", "Chicago", "Casimir Pulaski Day")
add("Fleet Foxes", "White Winter Hymnal", "Helplessness Blues")
add("Grizzly Bear", "Two Weeks", "Yet Again")
add("Animal Collective", "My Girls", "Fireworks")
add("Beach House", "Space Song", "Myth", "Lazuli")
add("Real Estate", "Talking Backwards", "Darling")
add("Mac DeMarco", "Chamber of Reflection", "My Kind of Woman")
add("Tyler Childers", "Feathered Indians", "All Your'n")
add("Chris Stapleton", "Tennessee Whiskey", "Broken Halos", "Starting Over")
add("Luke Combs", "Beautiful Crazy", "Forever After All", "When It Rains It Pours")
add("Morgan Wallen", "Whiskey Glasses", "Last Night", "You Proof", "Wasted On You")
add("Zach Bryan", "Something In The Orange", "Heading South")
add("Tyler Hubbard", "Dancin In The Country")
add("Jason Aldean", "Dirt Road Anthem", "Burnin It Down", "Try That In A Small Town")
add("Florida Georgia Line", "Cruise", "H.O.L.Y.", "Meant to Be")
add("Dan and Shay", "Tequila", "Speechless", "From The Ground Up")
add("Old Dominion", "One Man Band", "Snapback")
add("Carrie Underwood", "Before He Cheats", "Jesus Take The Wheel", "Blown Away")
add("Miranda Lambert", "The House That Built Me", "Gunpowder and Lead", "Mama's Broken Heart")
add("Kacey Musgraves", "Follow Your Arrow", "Space Cowboy", "Slow Burn")
add("Maren Morris", "The Bones", "My Church", "Girl")
add("Ashley McBryde", "One Night Standards", "Light On In The Kitchen")
add("Lainey Wilson", "Heart Like A Truck", "Things A Man Oughta Know")
add("Jelly Roll", "Need A Favor", "Son of a Sinner", "Save Me")
add("Hardy", "Wait In The Truck", "One Beer")
add("Bailey Zimmerman", "Rock and A Hard Place", "Fall In Love")
add("Parker McCollum", "Pretty Heart", "To Be Loved By You")
add("Cody Johnson", "Til You Can't", "Dear Rodeo")
add("George Strait", "Check Yes Or No", "Carrying Your Love With Me", "Amarillo By Morning")
add("Alan Jackson", "Chattahoochee", "Remember When", "It's Five O'Clock Somewhere")
add("Garth Brooks", "Friends In Low Places", "The Dance", "Thunder Rolls")
add("Tim McGraw", "Live Like You Were Dying", "Humble And Kind", "Don't Take The Girl")
add("Kenny Chesney", "No Shoes No Shirt No Problems", "American Kids")
add("Blake Shelton", "God's Country", "Austin", "Honey Bee")
add("Dolly Parton", "Jolene", "9 to 5", "I Will Always Love You original")
add("Johnny Cash", "Ring Of Fire", "Folsom Prison Blues", "Hurt cover", "Walk The Line")
add("Willie Nelson", "On The Road Again", "Always On My Mind", "Blue Eyes Crying In The Rain")
add("Waylon Jennings", "Good Hearted Woman", "Luckenbach Texas")
add("Merle Haggard", "Okie From Muskogee", "Mama Tried")
add("Hank Williams", "Your Cheatin Heart", "Jambalaya")
add("Patsy Cline", "Crazy", "Walkin After Midnight")
add("Loretta Lynn", "Coal Miner's Daughter", "You Ain't Woman Enough")
add("Tammy Wynette", "Stand By Your Man", "D-I-V-O-R-C-E")
add("Shania Twain", "Man I Feel Like A Woman", "Any Man Of Mine", "You're Still The One")
add("Faith Hill", "Breathe", "This Kiss", "The Way You Love Me")
add("Martina McBride", "Independence Day", "A Broken Wing")
add("Reba McEntire", "Fancy", "Does He Love You")
add("Randy Travis", "Forever And Ever Amen", "Three Wooden Crosses")
add("Alabama", "Mountain Music", "Song Of The South")
add("Zac Brown Band", "Chicken Fried", "Toes", "Colder Weather")
add("Rascal Flatts", "Life Is A Highway", "What Hurts The Most", "Bless The Broken Road")
add("Lady A", "Need You Now", "Just A Kiss")
add("Little Big Town", "Girl Crush", "Pontoon")
add("The Chicks", "Not Ready To Make Nice", "Wide Open Spaces", "Cowboy Take Me Away")
add("A.R. Rahman", "Jai Ho", "Slumdog Millionaire OST", "Tere Bina")
add("Lata Mangeshkar", "Lag Ja Gale", "Aye Mere Watan Ke Logo")
add("Kishore Kumar", "Pal Pal Dil Ke Paas", "Roop Tera Mastana")
add("Arijit Singh", "Tum Hi Ho", "Raabta", "Gerua", "Channa Mereya")
add("Shreya Ghoshal", "Teri Meri", "Bahara")
add("Badshah", "Genda Phool", "DJ Waley Babu", "Mercy")
add("Honey Singh", "Brown Rang", "High Heels", "Lungi Dance")
add("Diljit Dosanjh", "Lover", "G.O.A.T.", "Clash")
add("AP Dhillon", "Excuses", "Brown Munde", "With You")
add("Sidhu Moose Wala", "So High", "295", "The Last Ride")
add("BTS Jungkook", "Still With You")
add("Shakira", "Hips Don't Lie", "Whenever Wherever", "Waka Waka", "She Wolf", "Chantaje")
add("Juan Luis Guerra", "Burbujas de Amor", "Ojala Que Llueva Cafe")
add("Romeo Santos", "Propuesta Indecente", "Eres Mia", "Imitadora")
add("Prince Royce", "Stand By Me bachata", "Darte un Beso", "La Carretera")
add("Ozuna", "Criminal", "Se Preparo", "La Modelo")
add("Anuel AA", "China", "Secreto", "Adictiva")
add("Myke Towers", "La Playa", "Llegan La Bella", "Lala")
add("Ryan Castro", "Sed de Ti", "Mona Lisa")
add("Blessd", "Medallo", "Ojitos Rojos")
add("Karol G", "Provenza", "Mientras Me Curo", "TQG")
add("Shakira BZRP", "Shakira Bzrp Music Sessions 53")
add("Rosalía", "Con Altura", "Despechá", "Bizcochito")
add("Camilo", "Tutu", "Vida de Rico", "Indigo")
add("Morat", "Cuando Nadie Ve", "Amor con Hielo", "Besos en Guerra")
add("Reik", "Creo en Ti", "Noviembre sin ti", "Me Niego")
add("Sin Bandera", "Entra en mi vida", "Sirena", "Que me alcance la vida")
add("Camila", "Todo Cambió", "Mientes", "De mí enamórate")
add("Jesse y Joy", "Espacio Sideral", "Corre", "La de la mala suerte")
add("Ha Ash", "Perdón", "Lo Aprendí de Ti", "Te lo pido por favor")
add("Paty Cantú", "Afortunadamente no eres tú", "Recuérdame")
add("Belanova", "Rosa Pastel", "Por Ti", "Baila mi corazón")
add("Kinky", "Solo le pido a Dios", "A Donde van los muertos")
add("Caifanes", "La Negra Tomasa", "Afuera", "Nubes")
add("Los Fabulosos Cadillacs", "Matador", "El Matador", "Vasos Vacíos")
add("Los Auténticos Decadentes", "El Mismo Sol", "La Guitarra")
add("Babasónicos", "Como eran las cosas", "La partida de la gallina")
add("Soda Stereo", "De música ligera", "Persiana americana")
add("Los Prisioneros", "Tren al sur", "Estrechez de corazón")
add("Los Bunkers", "Bailando solo", "Llueve sobre la ciudad")
add("Los Tres", "La primera vez", "El apagón")
add("Aterciopelados", "Bolero falaz", "Florecita rockera")
add("Shakira", "Antología", "Estoy Aquí")
add("Maluma", "Hawái", "11 PM", "Felices los 4")
add("J Balvin", "Mi Gente", "Ay Vamos", "Ginza", "6 AM")
add("Nicky Jam", "Hasta el amanecer", "El perdón", "X")
add("Wisin y Yandel", "Abusadora", "Pam Pam", "Algo me gusta de ti")
add("Don Omar", "Danza Kuduro", "Taboo", "Virtual Diva")
add("Zion y Lennox", "La player", "Otra vez")
add("Arcángel", "Pa' que la pases bien", "Me acostumbré")
add("De La Ghetto", "Sensacion del bloque", "Favorito")
add("Tito El Bambino", "El Amor", "Flow Natural")
add("Hector Lavoe", "Periodico de ayer", "El cantante")
add("Celia Cruz", "La Vida Es Un Carnaval", "Quimbara", "Bemba Colorá")
add("Willie Colón", "Idilio", "Gitana")
add("Rubén Blades", "Pedro Navaja", "Plástico")
add("Marc Anthony", "Vivir mi vida", "Valió la pena")
add("Gilberto Santa Rosa", "Conteo regresivo", "Conciencia")
add("La India", "Ese hombre", "Sedúceme")
add("Gloria Estefan", "Conga", "Rhythm Is Gonna Get You", "1-2-3")
add("Emilio Estefan", "Mi tierra")
add("José José", "El triste", "La nave del olvido", "Lo pasado pasado")
add("Luis Miguel", "La incondicional", "Ahora te puedes marchar", "Cuando calienta el sol")
add("Vicente Fernández", "Por tu maldito amor", "Mujeres divinas")
add("Pedro Infante", "Cien años", "Amorcito corazón")
add("Rocío Dúrcal", "Amor eterno", "La gata bajo la lluvia")
add("Raphael", "Yo soy aquel", "Escándalo")
add("Mocedades", "Eres tú")
add("Mecano", "Hijo de la luna", "Me cuesta tanto olvidarte")
add("Radio Futura", "Escuela de calor", "Semilla negra")
add("Nacha Pop", "Lucha de gigantes", "Chica gangster")
add("Los Secretos", "Déjame", "Y no quiero saber")
add("Hombres G", "Devuélveme a mi chica", "Voy a pasármelo bien")
add("Los Delinqüentes", "El aire de la calle", "Dame veneno")
add("Estopa", "La raja de tu falda", "Vino tinto")
add("Melendi", "Caminando por la vida", "Tu jardín con enanitos")
add("Pablo Alborán", "Solamente tú", "Por fin", "Saturno")
add("David Bisbal", "Bulería", "Digale", "Corazón latino")
add("Alejandro Sanz", "Corazón partío", "No es lo mismo")
add("Enrique Iglesias", "Bailando", "Subeme la radio", "El perdedor")
add("Ricky Martin", "Livin la vida loca", "María", "She bangs")
add("Chayanne", "Torero", "Yo te amo", "Madre tierra")
add("Thalía", "Arrasando", "Amor a la mexicana", "Entre el mar y una estrella")
add("Paulina Rubio", "Y yo sigo aquí", "Dame otro tequila")
add("Belinda", "Angel", "Luz sin gravedad")
add("Anahí", "Mi delirio", "Rumba")
add("RBD", "Sálvame", "Rebelde", "Ser o parecer")
add("Luis Fonsi", "Despacito", "Échame la culpa")
add("Reik", "Noviembre sin ti", "Creo en ti")
add("Camila Cabello", "Never be the same", "My oh my")
add("Selena Gomez", "Come and get it", "Who says")
add("Demi Lovato", "Skyscraper", "Sorry not sorry")
add("Ariana Grande", "God is a woman", "Breathin")
add("Justin Bieber", "Baby", "Sorry", "Love yourself", "Peaches", "Ghost", "Stay")
add("One Direction", "What makes you beautiful", "Story of my life", "Night changes", "Drag me down")
add("Harry Styles", "Watermelon sugar", "As it was", "Sign of the times")
add("Louis Tomlinson", "Back to you", "Just hold on")
add("Zayn", "Pillowtalk", "Dusk till dawn")
add("Niall Horan", "Slow hands", "This town")
add("5 Seconds of Summer", "Youngblood", "She looks so perfect", "Teeth")
add("Little Mix", "Shout out to my ex", "Black magic", "Woman like me")
add("Spice Girls", "Wannabe", "Spice up your life", "Say you'll be there")
add("Backstreet Boys", "I want it that way", "Everybody", "As long as you love me")
add("NSYNC", "Bye bye bye", "It's gonna be me", "Tearin up my heart")
add("New Kids On The Block", "Step by step", "Hangin tough")
add("Boyz II Men", "End of the road", "I'll make love to you", "On bended knee")
add("TLC", "Waterfalls", "No scrubs", "Creep", "Unpretty")
add("Destiny's Child", "Say my name", "Survivor", "Bootylicious", "Independent women")
add("En Vogue", "Don't let go", "Free your mind", "My lovin")
add("SWV", "Weak", "Right here", "Rain")
add("Aaliyah", "Try again", "Are you that somebody", "One in a million")
add("Brandy", "The boy is mine", "Have you ever", "Afrodisiac")
add("Monica", "Angel of mine", "So gone", "Don't take it personal")
add("Ciara", "Goodies", "1 2 step", "Level up", "Ride")
add("Ashanti", "Foolish", "Rock wit u", "Rain on me")
add("Keyshia Cole", "Love", "Trust", "Heaven sent")
add("Fantasia", "When I see u", "Free yourself")
add("Jill Scott", "A long walk", "Golden")
add("Erykah Badu", "On and on", "Tyrone", "Bag lady")
add("D'Angelo", "Untitled", "Brown sugar", "Lady")
add("Maxwell", "Ascension", "Pretty wings")
add("Musiq Soulchild", "Just friends", "Love")
add("Anthony Hamilton", "Charlene", "Comin from where I'm from")
add("Jaheim", "Put that woman first", "Finding my way back")
add("Ginuwine", "Pony", "Differences", "In those jeans")
add("Joe", "I wanna know", "Stutter")
add("112", "Peaches and cream", "Cupid")
add("Jagged Edge", "Where the party at", "Promise")
add("B2K", "Bump bump bump", "Gots ta be")
add("Omarion", "O", "Post to be", "Touch")
add("Mario", "Let me love you", "How do I breathe")
add("Cassie", "Me and u", "Long way 2 go")
add("Amerie", "1 thing", "Why don't we fall in love")
add("Tweet", "Oops", "Call me")
add("Lil Kim", "Magic stick", "How many licks")
add("Eve", "Let me blow ya mind", "Who's that girl")
add("Trina", "Here we go", "Pull over")
add("Khia", "My neck my back")
add("Trick Daddy", "Let's go", "Shut up")
add("Plies", "Bust it baby", "Hypnotized")
add("T-Pain", "Buy u a drank", "Bartender")
add("Yung Joc", "It's goin down", "Coffee shop")
add("Chamillionaire", "Ridin", "Goodmorning")
add("Mike Jones", "Still Tippin", "Back then")
add("Paul Wall", "Sittin sideways", "They don't know")
add("Slim Thug", "Still tippin", "I ain't heard of that")
add("Z-Ro", "Mo city don", "I hate you bitch")
add("UGK", "Int'l players anthem", "One two three")
add("Scarface", "On my block", "Mind playing tricks")
add("Geto Boys", "Mind playing tricks on me", "Damn it feels good")
add("Three 6 Mafia", "Stay fly", "Side 2 side", "Slob on my knob")
add("Project Pat", "Chickenhead", "Don't save her")
add("Juvenile", "Back that azz up", "Slow motion", "Set it off")
add("Master P", "Make em say uhh", "Bout it bout it")
add("Silkk the Shocker", "It ain't my fault", "Party like a rockstar")
add("Soulja Boy", "Crank that", "Kiss me thru the phone", "Turn my swag on")
add("Bow Wow", "Like you", "Let me hold you", "Fresh azimiz")
add("Lil Romeo", "My baby", "Basketball")
add("Cali Swag District", "Teach me how to dougie")
add("New Boyz", "You're a jerk", "Backseat")
add("Iyaz", "Replay", "Pretty girls")
add("Jason Derulo", "Whatcha say", "Ridin solo", "Want to want me")
add("Pitbull", "Timber", "Give me everything", "Hotel room service")
add("Flo Rida", "Low", "Good feeling", "Club can't handle me")
add("LMFAO", "Party rock anthem", "Sexy and I know it")
add("will.i.am", "Scream and shout", "This is love")
add("Black Eyed Peas", "I gotta feeling", "Boom boom pow", "Where is the love")
add("Fergie", "Big girls don't cry", "Glamorous", "London bridge")
add("Nelly Furtado", "Promiscuous", "Say it right", "Maneater")
add("Shakira", "Objection", "La tortura", "Loca")
add("Juanes", "La camisa negra", "A dios le pido")
add("Maná", "Rayando el sol", "En el muelle de San Blas")
add("Caetano Veloso", "Sozinho", "Terra")
add("Gilberto Gil", "Aquele abraço", "Palco")
add("Jorge Ben", "Mas que nada", "Chove chuva")
add("Tim Maia", "Gostava tanto de você", "Descobridor dos sete mares")
add("Djavan", "Oceano", "Flor de lis")
add("Ivete Sangalo", "Sorte grande", "Arerê")
add("Ludmilla", "Hoje", "Invocada")
add("Anitta", "Vai malandra", "Show das poderosas")
add("Pabllo Vittar", "Amor de que", "Seu crime")
add("Luísa Sonza", "Bomba", "Dona de mim")
add("Marília Mendonça", "Infiel", "Todo mundo menos eu")
add("Henrique e Juliano", "Cuida bem dela", "Arranhão")
add("Jorge e Mateus", "Os anjos cantam", "Logo eu")
add("Zé Neto e Cristiano", "Largado às traças", "Status que eu não queria")
add("Gusttavo Lima", "Balada", "Apelido carinhoso")
add("Luan Santana", "Meteoro", "Te esperando")
add("Michel Teló", "Ai se eu te pego", "Fugidinha")
add("Racionais MCs", "Diário de um detento", "Vida loka")
add("Emicida", "Levanta e anda", "Passarinhos")
add("Criolo", "Não existe amor em SP", "Subirusdoistiozin")
add("Projota", "Oh meu Deus", "Liga da justiça")
add("Poesia Acústica", "Poesia Acústica 2", "Poesia Acústica 5")
add("Matuê", "Máquina do tempo", "Cronograma")
add("Teto", "Mustang preto", "M4")
add("Wiu", "Coração de gelo", "Mania de você")
add("Filipe Ret", "Amor livre", "Cypher sincero")
add("BK", "Planos", "Poesia acústica")
add("Veigh", "Artista Genérico", "Ballena")
add("Orochi", "Poesia Acústica", "Osasco")
add("Chefin", "Ameaça", "Melhorzin")
add("Mc Poze do Rodo", "Vida louca", "Manifesto")
add("Mc Cabelinho", "Cartão black", "Bem melhor")
add("Mc IG", "3 letras", "Fazendo dinheiro")
add("Mc Ryan SP", "Sexta feira", "Sempre na simplicidade")
add("Mc Luuky", "Fuleragem", "Automotivo")
add("Mc Don Juan", "Os mlk tá de parabéns", "Sexta feira 2")
add("Mc GP", "Let's go 4", "Ta rico ainda")
add("Mc PH", "Let's go 5", "Vem pra cá")
add("Mc Meno K", "Let's go 6", "Ta ok")
add("Mc Davi", "Let's go 3", "Pique da vó")
add("Mc L da Vinte", "Surra de cama", "Vidrado em você")
add("Mc Tuto", "Barbie", "Mão na parede")
add("Mc Jvila", "Tipo Nino vs Kabrinha", "Automotivo arrocha")
add("Mc Rodrigo do CN", "Pique da vó", "Tchau pro invejoso")
add("Mc Negão Original", "Eu te amo", "Só love")
add("Mc Lipi", "Ela é da ppk", "Tipo terremoto")
add("Mc Marks", "Romance com safadeza", "Desculpa mãe")
add("Mc Paiva", "Funk de verão", "Automotivo bibi fogosa")
add("Mc 2Jhow", "Eu achei", "Toma tomada")
add("Mc Kadu", "Ta facil", "Vem desce")
add("Mc G15", "Menina da favela", "Automotivo embraza")
add("Mc Carol", "Bateu a língua", "Chama ela de pretinha")
add("Mc Gw", "Mágica", "Automotivo embrazado")
add("Mc Larinha", "Novinha da favela", "Senta e levanta")
add("Mc Pipokinha", "Bateu a língua", "Automotivo pa pa papai")
add("Mc Rodrigo HK", "Vai tomar estalo", "Senta e levanta")
add("Mc Topre", "Tchau obrigado", "Vem pro baile")
add("Mc Lele JP", "Automotivo arrocha", "Só se vive uma vez")
add("Mc Carolzinha", "Automotivo pa pa papai", "Novinha da favela")
add("Mc Jhey", "Vem pro baile", "Só love")
add("Mc Cebezinho", "Vem pro baile", "Tchau obrigado")
add("Mc Leozinho ZS", "Vem pro baile", "Só love")
add("Mc Leozin", "Vem pro baile", "Só love")
add("Mc Rick", "Vem pro baile", "Só love")
add("Mc Joãozinho VT", "Vem pro baile", "Só love")

# --- Parte 2: trilhas, clássicos adicionais, one-hit wonders ---
add("Disney", "Let It Go Frozen", "Circle of Life", "A Whole New World", "Under the Sea",
    "Be Our Guest", "You've Got a Friend in Me", "Colors of the Wind", "Reflection Mulan")
add("Phil Collins", "You'll Be In My Heart Tarzan", "Strangers Like Me")
add("Celine Dion", "Beauty and the Beast", "Because You Loved Me")
add("Elton John", "Can You Feel The Love Tonight", "Your Song", "Rocket Man", "Tiny Dancer",
    "Bennie and the Jets", "Don't Go Breaking My Heart", "I'm Still Standing", "Cold Heart")
add("Whitney Houston", "I Have Nothing Bodyguard", "I Will Always Love You Bodyguard")
add("Titanic Soundtrack", "My Heart Will Go On", "Rose")
add("Grease", "Summer Nights", "You're The One That I Want", "We Go Together")
add("Dirty Dancing", "Time Of My Life", "Hungry Eyes")
add("Footloose", "Footloose Kenny Loggins", "Let's Hear It For The Boy")
add("Flashdance", "What A Feeling", "Maniac")
add("Top Gun", "Danger Zone", "Take My Breath Away")
add("Ghostbusters", "Ghostbusters Ray Parker Jr")
add("Back to the Future", "The Power Of Love Huey Lewis")
add("Beverly Hills Cop", "Axel F Harold Faltermeyer")
add("Rocky", "Eye Of The Tiger", "Gonna Fly Now")
add("Chariots of Fire", "Chariots of Fire Vangelis")
add("Mission Impossible", "Mission Impossible Theme")
add("James Bond", "Skyfall Adele", "Live and Let Die", "Goldfinger")
add("Pirates of the Caribbean", "He's a Pirate")
add("Star Wars", "Imperial March", "Main Title")
add("Harry Potter", "Hedwig's Theme")
add("Lord of the Rings", "May It Be Enya", "Into The West")
add("Game of Thrones", "Main Theme")
add("Stranger Things", "Running Up That Hill Kate Bush")
add("Squid Game", "Pink Soldiers")
add("Kate Bush", "Running Up That Hill", "Wuthering Heights", "Babooshka")
add("Peter Gabriel", "Sledgehammer", "In Your Eyes", "Solsbury Hill")
add("Toto", "Africa", "Rosanna", "Hold the Line", "I'll Be Over You")
add("Chicago", "If You Leave Me Now", "Hard To Say I'm Sorry", "You're The Inspiration")
add("Journey", "Don't Stop Believin", "Separate Ways", "Open Arms", "Faithfully", "Any Way You Want It")
add("Foreigner", "I Want To Know What Love Is", "Waiting For A Girl Like You", "Cold As Ice")
add("REO Speedwagon", "Can't Fight This Feeling", "Keep On Loving You", "Take It On The Run")
add("Styx", "Come Sail Away", "Mr Roboto", "Babe")
add("Boston", "More Than A Feeling", "Peace of Mind", "Amanda")
add("Kansas", "Carry On Wayward Son", "Dust In The Wind", "Point of Know Return")
add("Heart", "Alone", "Barracuda", "These Dreams", "Magic Man")
add("Pat Benatar", "Hit Me With Your Best Shot", "Love Is A Battlefield", "We Belong")
add("Joan Jett", "I Love Rock And Roll", "Bad Reputation", "Crimson and Clover")
add("Blondie", "Heart Of Glass", "Call Me", "One Way Or Another", "Rapture")
add("The Cars", "Drive", "Just What I Needed", "Good Times Roll", "You Might Think")
add("Talking Heads", "Burning Down The House", "Psycho Killer", "Once In A Lifetime")
add("The B-52's", "Love Shack", "Rock Lobster", "Roam")
add("Culture Club", "Karma Chameleon", "Do You Really Want To Hurt Me", "Time Clock Of The Heart")
add("Duran Duran", "Hungry Like The Wolf", "Rio", "Ordinary World", "Come Undone")
add("A Flock of Seagulls", "I Ran", "Space Age Love Song")
add("Tears For Fears", "Everybody Wants To Rule The World", "Shout", "Head Over Heels")
add("Simple Minds", "Don't You Forget About Me", "Alive and Kicking", "Belfast Child")
add("Human League", "Don't You Want Me", "Human")
add("Pet Shop Boys", "West End Girls", "It's A Sin", "Always On My Mind")
add("Erasure", "A Little Respect", "Always", "Chains Of Love")
add("Depeche Mode", "Personal Jesus", "Enjoy The Silence", "Just Can't Get Enough")
add("New Order", "Blue Monday", "Bizarre Love Triangle", "True Faith")
add("The Smiths", "There Is A Light That Never Goes Out", "How Soon Is Now", "This Charming Man")
add("The Cranberries", "Zombie", "Linger", "Dreams", "Ode To My Family")
add("U2", "With Or Without You", "One", "Beautiful Day", "Where The Streets Have No Name",
    "I Still Haven't Found What I'm Looking For", "Sunday Bloody Sunday", "Pride")
add("R.E.M.", "Losing My Religion", "Everybody Hurts", "Shiny Happy People", "The One I Love")
add("Pearl Jam", "Alive", "Even Flow", "Jeremy", "Black", "Better Man")
add("Soundgarden", "Black Hole Sun", "Spoonman", "Outshined", "Fell On Black Days")
add("Alice In Chains", "Man In The Box", "Rooster", "Would", "Down In A Hole")
add("Stone Temple Pilots", "Interstate Love Song", "Plush", "Vasoline", "Creep STP")
add("Bush", "Glycerine", "Machinehead", "Comedown")
add("Live", "Lightning Crashes", "I Alone", "Selling The Drama")
add("Collective Soul", "Shine", "December", "The World I Know")
add("Creed", "With Arms Wide Open", "Higher", "My Sacrifice", "One Last Breath")
add("Matchbox Twenty", "Push", "3AM", "Unwell", "Bright Lights")
add("Goo Goo Dolls", "Iris", "Slide", "Name", "Black Balloon")
add("Third Eye Blind", "Semi-Charmed Life", "Jumper", "How's It Going To Be")
add("Everclear", "Santa Monica", "Wonderful", "Father Of Mine")
add("Lit", "My Own Worst Enemy", "Zip-Lock")
add("Harvey Danger", "Flagpole Sitta")
add("Smash Mouth", "All Star", "Walkin On The Sun", "Then The Morning Comes")
add("Sugar Ray", "Fly", "Every Morning", "Someday")
add("Crazy Town", "Butterfly", "Starry Eyed Surprise")
add("Limp Bizkit", "Nookie", "Break Stuff", "Rollin", "My Way")
add("Linkin Park", "In The End", "Numb", "Crawling", "What I've Done", "Faint", "One Step Closer")
add("Evanescence", "Bring Me To Life", "My Immortal", "Going Under")
add("System of a Down", "Chop Suey", "Toxicity", "B.Y.O.B.", "Aerials")
add("Korn", "Freak On A Leash", "Falling Away From Me", "Coming Undone")
add("Slipknot", "Duality", "Before I Forget", "Psychosocial", "Wait And Bleed")
add("Metallica", "Enter Sandman", "Nothing Else Matters", "One", "Master of Puppets",
    "Fade To Black", "The Unforgiven", "For Whom The Bell Tolls")
add("Megadeth", "Symphony Of Destruction", "Peace Sells", "Hangar 18")
add("Pantera", "Walk", "Cowboys From Hell", "Cemetery Gates")
add("Slayer", "Raining Blood", "Angel Of Death")
add("Anthrax", "Madhouse", "Bring The Noise")
add("Motörhead", "Ace of Spades", "Overkill")
add("AC/DC", "Back In Black", "Highway To Hell", "Thunderstruck", "You Shook Me All Night Long",
    "Shoot To Thrill", "Hells Bells", "Dirty Deeds Done Dirt Cheap")
add("Led Zeppelin", "Stairway To Heaven", "Whole Lotta Love", "Black Dog", "Kashmir",
    "Rock And Roll", "Immigrant Song", "Ramble On")
add("Pink Floyd", "Another Brick In The Wall", "Wish You Were Here", "Comfortably Numb",
    "Money", "Time", "Hey You", "Shine On You Crazy Diamond")
add("The Rolling Stones", "Paint It Black", "Gimme Shelter", "Sympathy For The Devil",
    "Angie", "Start Me Up", "Satisfaction", "Wild Horses")
add("The Beatles", "Hey Jude", "Let It Be", "Yesterday", "Come Together", "Here Comes The Sun",
    "Twist And Shout", "Help", "Eleanor Rigby", "While My Guitar Gently Weeps")
add("The Who", "Baba O Riley", "Won't Get Fooled Again", "Behind Blue Eyes", "Pinball Wizard")
add("Cream", "Sunshine Of Your Love", "White Room", "Crossroads")
add("The Jimi Hendrix Experience", "All Along The Watchtower", "Purple Haze", "Foxey Lady")
add("Bob Marley", "Three Little Birds", "No Woman No Cry", "Redemption Song", "Is This Love",
    "Could You Be Loved", "Jamming", "One Love")
add("Peter Tosh", "Legalize It", "Equal Rights")
add("Burning Spear", "Marcus Garvey")
add("Shaggy", "It Wasn't Me", "Angel", "Boombastic")
add("Sean Paul", "Get Busy", "Temperature", "We Be Burnin")
add("Beenie Man", "Who Am I", "Girls Dem Sugar")
add("Vybz Kartel", "Fever", "Clarks")
add("Popcaan", "Only Man She Want", "Family")
add("Koffee", "Toast", "West Indies")
add("Chronixx", "Here Comes Trouble", "Skankin Sweet")
add("Protoje", "Who Knows", "Blood Money")
add("Damian Marley", "Welcome To Jamrock")
add("UB40", "Red Red Wine", "Kingston Town")
add("Inner Circle", "Bad Boys", "Sweat A La La La La Long")
add("Ace of Base", "The Sign", "All That She Wants", "Beautiful Life")
add("Roxette", "It Must Have Been Love", "Listen To Your Heart", "Joyride", "The Look")
add("a-ha", "Take On Me", "The Sun Always Shines On TV")
add("Europe", "The Final Countdown", "Carrie")
add("Survivor", "Eye Of The Tiger", "Burning Heart")
add("Wham", "Wake Me Up Before You Go-Go", "Last Christmas", "Careless Whisper George Michael")
add("George Michael", "Faith", "Freedom 90", "Careless Whisper")
add("Rick Astley", "Never Gonna Give You Up", "Together Forever")
add("Tiffany", "I Think We're Alone Now")
add("Debbie Gibson", "Lost In Your Eyes", "Only In My Dreams")
add("Cyndi Lauper", "Girls Just Want To Have Fun", "Time After Time", "True Colors")
add("Madonna", "Like A Virgin", "Material Girl", "Vogue", "Like A Prayer", "Hung Up", "4 Minutes")
add("Michael Jackson", "Billie Jean", "Beat It", "Thriller", "Smooth Criminal", "Black Or White",
    "Man In The Mirror", "Don't Stop Til You Get Enough", "The Way You Make Me Feel")
add("Prince", "When Doves Cry", "Purple Rain", "Kiss", "1999", "Raspberry Beret")
add("Janet Jackson", "Rhythm Nation", "Together Again", "That's The Way Love Goes", "All For You")
add("Whitney Houston", "I Wanna Dance With Somebody", "Greatest Love Of All", "How Will I Know")
add("Mariah Carey", "Hero", "We Belong Together", "Fantasy", "Always Be My Baby", "Vision Of Love")
add("Celine Dion", "My Heart Will Go On", "Because You Loved Me", "The Power Of Love")
add("Barbra Streisand", "Woman In Love", "Evergreen")
add("Diana Ross", "Ain't No Mountain High Enough", "I'm Coming Out", "Upside Down")
add("Donna Summer", "Hot Stuff", "Last Dance", "On The Radio", "She Works Hard For The Money")
add("Gloria Gaynor", "I Will Survive")
add("Village People", "YMCA", "Macho Man")
add("Kool and The Gang", "Celebration", "Get Down On It", "Joanna")
add("Earth Wind and Fire", "September", "Boogie Wonderland", "Let's Groove")
add("Commodores", "Easy", "Brick House", "Three Times A Lady")
add("The Isley Brothers", "Shout", "Between The Sheets", "For The Love Of You")
add("Marvin Gaye", "What's Going On", "Sexual Healing", "Let's Get It On", "Ain't No Mountain")
add("Stevie Wonder", "Superstition", "Signed Sealed Delivered", "Isn't She Lovely")
add("Al Green", "Let's Stay Together", "Tired Of Being Alone")
add("Otis Redding", "Sittin On The Dock Of The Bay", "Try A Little Tenderness")
add("Sam Cooke", "A Change Is Gonna Come", "Wonderful World", "Chain Gang")
add("Ray Charles", "Hit The Road Jack", "Georgia On My Mind", "I Can't Stop Loving You")
add("Etta James", "At Last", "I'd Rather Go Blind")
add("Nina Simone", "Feeling Good", "I Put A Spell On You")
add("Bill Withers", "Ain't No Sunshine", "Lean On Me", "Lovely Day", "Just The Two Of Us")
add("Curtis Mayfield", "Move On Up", "Superfly")
add("Isaac Hayes", "Theme From Shaft")
add("Sly and the Family Stone", "Everyday People", "Dance To The Music")
add("Parliament", "Give Up The Funk", "Flash Light")
add("Funkadelic", "One Nation Under A Groove", "Maggot Brain")
add("Chic", "Le Freak", "Good Times", "Everybody Dance")
add("Sister Sledge", "We Are Family", "He's The Greatest Dancer")
add("The Trammps", "Disco Inferno")
add("Bee Gees", "Stayin Alive", "Night Fever", "How Deep Is Your Love", "More Than A Woman")
add("ABBA", "Dancing Queen", "Mamma Mia", "Waterloo", "Fernando", "Take A Chance On Me")
add("Boney M", "Rasputin", "Daddy Cool", "Ma Baker")
add("Modern Talking", "You're My Heart You're My Soul", "Brother Louie")
add("Alphaville", "Forever Young", "Big In Japan")
add("Nena", "99 Luftballons")
add("Falco", "Rock Me Amadeus", "Der Kommissar")
add("Scorpions", "Wind Of Change", "Still Loving You", "Rock You Like A Hurricane")
add("Rammstein", "Du Hast", "Sonne", "Deutschland")
add("Kraftwerk", "The Model", "Autobahn", "Tour De France")
add("Jean-Michel Jarre", "Oxygene")
add("Vangelis", "Chariots of Fire", "Conquest of Paradise")
add("Enya", "Orinoco Flow", "Only Time", "May It Be")
add("Clannad", "Theme From Harry's Game")
add("Sinéad O'Connor", "Nothing Compares 2 U")
add("The Corrs", "Breathless", "Runaway", "What Can I Do")
add("Westlife", "My Love", "Flying Without Wings", "World Of Our Own")
add("Boyzone", "No Matter What", "Baby Can I Hold You")
add("Take That", "Back For Good", "Never Forget", "Patience")
add("Spice Girls", "Wannabe", "Say You'll Be There", "2 Become 1")
add("Robbie Williams", "Angels", "Feel", "Rock DJ", "Let Me Entertain You")
add("Gary Barlow", "Forever Love")
add("James Blunt", "You're Beautiful", "Goodbye My Lover")
add("Dido", "Thank You", "White Flag", "Here With Me")
add("Emeli Sandé", "Next To Me", "Read All About It")
add("Jess Glynne", "Hold My Hand", "Don't Be So Hard On Yourself")
add("Ella Henderson", "Ghost", "Glow")
add("Paloma Faith", "Changing", "Only Love Can Hurt Like This")
add("Tom Jones", "Sex Bomb", "It's Not Unusual", "Delilah")
add("Shirley Bassey", "Goldfinger", "Diamonds Are Forever")
add("Adele", "Someone Like You", "Rolling In The Deep", "Hello", "Set Fire To The Rain")
add("Ed Sheeran", "Shape Of You", "Perfect", "Thinking Out Loud", "Castle On The Hill", "Photograph")
add("Sam Fender", "Seventeen Going Under", "Will We Talk")
add("Lewis Capaldi", "Someone You Loved", "Before You Go", "Hold Me While You Wait")
add("Calum Scott", "You Are The Reason", "Dancing On My Own")
add("Michael Bublé", "Haven't Met You Yet", "Feeling Good", "Home")
add("Norah Jones", "Don't Know Why", "Come Away With Me", "Sunrise")
add("Diana Krall", "The Look Of Love")
add("Frank Sinatra", "My Way", "Fly Me To The Moon", "New York New York", "That's Life")
add("Dean Martin", "That's Amore", "Everybody Loves Somebody")
add("Louis Armstrong", "What A Wonderful World", "La Vie En Rose")
add("Ella Fitzgerald", "Summertime", "Dream A Little Dream Of Me")
add("Nat King Cole", "Unforgettable", "L-O-V-E", "The Christmas Song")
add("Johnny Mathis", "Misty", "Chances Are")
add("Andy Williams", "Moon River", "Can't Take My Eyes Off You")
add("Perry Como", "Catch A Falling Star")
add("Bing Crosby", "White Christmas", "Swinging On A Star")
add("Frank Sinatra and Count Basie", "Fly Me To The Moon")
add("Louis Prima", "Sing Sing Sing", "Jump Jive an Wail")
add("Benny Goodman", "Sing Sing Sing")
add("Glenn Miller", "In The Mood", "Moonlight Serenade")
add("Duke Ellington", "Take The A Train", "It Don't Mean A Thing")
add("Miles Davis", "So What", "Blue In Green")
add("John Coltrane", "My Favorite Things", "Giant Steps")
add("Thelonious Monk", "Round Midnight")
add("Herbie Hancock", "Watermelon Man", "Cantaloupe Island")
add("Weather Report", "Birdland")
add("Chuck Berry", "Johnny B Goode", "Roll Over Beethoven", "Maybellene")
add("Little Richard", "Tutti Frutti", "Good Golly Miss Molly")
add("Jerry Lee Lewis", "Great Balls Of Fire", "Whole Lotta Shakin")
add("Buddy Holly", "Peggy Sue", "That'll Be The Day", "Everyday")
add("The Beach Boys", "Good Vibrations", "God Only Knows", "Surfin USA", "Wouldn't It Be Nice")
add("Roy Orbison", "Oh Pretty Woman", "Crying", "You Got It")
add("The Righteous Brothers", "Unchained Melody", "You've Lost That Lovin Feelin")
add("Ben E King", "Stand By Me", "Spanish Harlem")
add("The Drifters", "Under The Boardwalk", "Save The Last Dance For Me")
add("The Platters", "Only You", "The Great Pretender", "Smoke Gets In Your Eyes")
add("Frankie Valli", "Can't Take My Eyes Off You", "Greased Lightning")
add("The Monkees", "I'm A Believer", "Daydream Believer")
add("The Mamas and The Papas", "California Dreamin", "Monday Monday")
add("Simon and Garfunkel", "The Sound Of Silence", "Bridge Over Troubled Water", "Mrs Robinson", "Cecilia")
add("Crosby Stills Nash and Young", "Ohio", "Teach Your Children", "Suite Judy Blue Eyes")
add("The Byrds", "Mr Tambourine Man", "Turn Turn Turn")
add("Buffalo Springfield", "For What It's Worth")
add("Creedence Clearwater Revival", "Have You Ever Seen The Rain", "Bad Moon Rising",
    "Fortunate Son", "Proud Mary", "Down On The Corner")
add("Lynyrd Skynyrd", "Sweet Home Alabama", "Free Bird", "Simple Man", "Gimme Three Steps")
add("Allman Brothers Band", "Ramblin Man", "Jessica")
add("The Marshall Tucker Band", "Can't You See")
add("ZZ Top", "Sharp Dressed Man", "La Grange", "Gimme All Your Lovin", "Legs")
add("George Thorogood", "Bad To The Bone", "One Bourbon One Scotch One Beer")
add("Steppenwolf", "Born To Be Wild", "Magic Carpet Ride")
add("Grand Funk Railroad", "We're An American Band", "Some Kind Of Wonderful")
add("Cheap Trick", "I Want You To Want Me", "Surrender", "The Flame")
add("Starship", "We Built This City", "Nothing's Gonna Stop Us Now", "Sara")
add("Journey", "Don't Stop Believin", "Open Arms", "Separate Ways")
add("Night Ranger", "Sister Christian", "Don't Tell Me You Love Me")
add("Mr Mister", "Broken Wings", "Kyrie", "Take These Broken Wings")
add("Toto", "Africa", "Hold the Line", "Rosanna")
add("Supertramp", "Breakfast In America", "Give A Little Bit", "The Logical Song")
add("Electric Light Orchestra", "Mr Blue Sky", "Don't Bring Me Down", "Livin Thing", "Telephone Line")
add("10cc", "I'm Not In Love", "Dreadlock Holiday")
add("Stealers Wheel", "Stuck In The Middle With You")
add("Looking Glass", "Brandy You're A Fine Girl")
add("America", "A Horse With No Name", "Sister Golden Hair", "Ventura Highway")
add("Bread", "Make It With You", "Everything I Own", "Baby I'm A Want You")
add("Air Supply", "Making Love Out Of Nothing At All", "All Out Of Love", "Lost In Love")
add("Chicago", "Saturday In The Park", "You're The Inspiration", "Hard To Say I'm Sorry")
add("Hall and Oates", "Maneater", "Rich Girl", "You Make My Dreams", "Kiss On My List", "Private Eyes")
add("Kenny Loggins", "Footloose", "Danger Zone", "I'm Alright", "House At Pooh Corner")
add("Steve Winwood", "Higher Love", "Back In The High Life Again", "Valerie")
add("Phil Collins", "In The Air Tonight", "Another Day In Paradise", "Against All Odds", "Sussudio")
add("Genesis", "Invisible Touch", "That's All", "Land Of Confusion", "Follow You Follow Me")
add("Peter Gabriel", "Shock The Monkey", "Big Time")
add("Mike and The Mechanics", "The Living Years", "All I Need Is A Miracle")
add("Billy Ocean", "Caribbean Queen", "When The Going Gets Tough", "Suddenly")
add("Sheena Easton", "Morning Train", "For Your Eyes Only")
add("Kim Wilde", "Kids In America", "You Keep Me Hangin On")
add("Bananarama", "Venus", "Cruel Summer", "Love In The First Degree")
add("Culture Club", "Karma Chameleon", "Do You Really Want To Hurt Me")
add("Frankie Goes to Hollywood", "Relax", "Two Tribes", "The Power Of Love")
add("Dead or Alive", "You Spin Me Round")
add("Soft Cell", "Tainted Love")
add("Gary Numan", "Cars")
add("Visage", "Fade To Grey")
add("Ultravox", "Dancing With Tears In My Eyes", "Vienna")
add("OMD", "If You Leave", "Enola Gay")
add("Yazoo", "Only You", "Don't Go")
add("Eurythmics", "Sweet Dreams", "Here Comes The Rain Again", "Would I Lie To You")
add("Annie Lennox", "Why", "Walking On Broken Glass")
add("Sade", "Smooth Operator", "No Ordinary Love", "The Sweetest Taboo", "By Your Side")
add("Simply Red", "Holding Back The Years", "If You Don't Know Me By Now", "Stars")
add("Lisa Stansfield", "All Around The World", "Never Never Give You Up")
add("Des'ree", "You Gotta Be", "Kissing You")
add("Seal", "Kiss From A Rose", "Crazy", "Fly Like An Eagle")
add("Macy Gray", "I Try", "Sweet Baby")
add("Corinne Bailey Rae", "Put Your Records On", "Like A Star")
add("Norah Jones", "Come Away With Me", "Don't Know Why")
add("Alicia Keys", "Fallin", "No One", "If I Ain't Got You", "Girl On Fire", "Empire State Of Mind")
add("John Legend", "All Of Me", "Ordinary People", "Glory")
add("Bruno Mars", "Just The Way You Are", "Grenade", "Locked Out Of Heaven", "Uptown Funk",
    "24K Magic", "That's What I Like", "When I Was Your Man")
add("Mark Ronson", "Uptown Funk", "Nothing Breaks Like A Heart")
add("Pharrell Williams", "Happy", "Frontin", "Get Lucky")
add("Justin Timberlake", "Cry Me A River", "SexyBack", "Mirrors", "Can't Stop The Feeling", "Suit and Tie")
add("NSYNC", "Bye Bye Bye", "It's Gonna Be Me", "Tearin Up My Heart")
add("Christina Aguilera", "Genie In A Bottle", "Beautiful", "Fighter", "Hurt", "Lady Marmalade")
add("Britney Spears", "Baby One More Time", "Toxic", "Oops I Did It Again", "Womanizer", "Gimme More")
add("Katy Perry", "Firework", "Roar", "Dark Horse", "California Gurls", "I Kissed A Girl", "Hot N Cold")
add("Lady Gaga", "Bad Romance", "Poker Face", "Born This Way", "Shallow", "Just Dance", "Rain On Me")
add("Rihanna", "Umbrella", "We Found Love", "Diamonds", "Work", "Only Girl", "Stay", "Disturbia")
add("Beyonce", "Single Ladies", "Crazy In Love", "Halo", "Drunk In Love", "Formation", "Run The World")
add("Shakira", "Hips Don't Lie", "Whenever Wherever", "Waka Waka", "She Wolf")
add("Jennifer Lopez", "On The Floor", "Jenny From The Block", "If You Had My Love", "Let's Get Loud")
add("Pitbull", "Timber", "Give Me Everything", "Hotel Room Service", "Fireball", "International Love")
add("Flo Rida", "Low", "Good Feeling", "Whistle", "My House", "Club Can't Handle Me")
add("Kesha", "Tik Tok", "We R Who We R", "Timber", "Die Young")
add("Taio Cruz", "Dynamite", "Break Your Heart", "Hangover")
add("Far East Movement", "Like A G6", "Rocketeer")
add("Wiz Khalifa", "Black And Yellow", "See You Again", "We Dem Boyz")
add("Snoop Dogg", "Gin And Juice", "Drop It Like It's Hot", "Young Wild And Free")
add("Dr Dre", "Still DRE", "The Next Episode", "Forgot About Dre", "Nuthin But A G Thang")
add("Eminem", "Lose Yourself", "Without Me", "The Real Slim Shady", "Stan", "Love The Way You Lie",
    "Not Afraid", "Rap God", "Mockingbird", "Till I Collapse")
add("Kanye West", "Stronger", "Gold Digger", "Heartless", "Power", "All Of The Lights", "Touch The Sky")
add("Jay-Z", "99 Problems", "Empire State Of Mind", "Hard Knock Life", "Big Pimpin", "Run This Town")
add("Nas", "If I Ruled The World", "NY State Of Mind", "The World Is Yours")
add("The Notorious B.I.G.", "Juicy", "Big Poppa", "Hypnotize", "Mo Money Mo Problems")
add("2Pac", "California Love", "Changes", "Dear Mama", "Ambitionz Az A Ridah", "Hit Em Up")
add("Wu-Tang Clan", "C.R.E.A.M.", "Gravel Pit", "Triumph")
add("OutKast", "Hey Ya", "Ms Jackson", "So Fresh So Clean", "Roses")
add("A Tribe Called Quest", "Can I Kick It", "Electric Relaxation")
add("De La Soul", "Me Myself And I", "Ring Ring Ring")
add("Public Enemy", "Fight The Power", "Don't Believe The Hype")
add("Beastie Boys", "No Sleep Till Brooklyn", "Sabotage", "Intergalactic", "Fight For Your Right")
add("Run-DMC", "Walk This Way", "It's Tricky", "My Adidas")
add("LL Cool J", "Mama Said Knock You Out", "I Need Love", "Going Back To Cali")
add("Salt-N-Pepa", "Push It", "Shoop", "Whatta Man")
add("MC Hammer", "U Can't Touch This", "2 Legit 2 Quit")
add("Vanilla Ice", "Ice Ice Baby")
add("House of Pain", "Jump Around")
add("Cypress Hill", "Insane In The Brain", "How I Could Just Kill A Man")
add("N.W.A", "Straight Outta Compton", "Fuck Tha Police")
add("Ice Cube", "It Was A Good Day", "Check Yo Self", "No Vaseline")
add("Snoop Dogg", "Who Am I", "Beautiful", "Peaches N Cream")
add("50 Cent", "In Da Club", "21 Questions", "Candy Shop", "Many Men")
add("The Game", "Hate It Or Love It", "How We Do")
add("G-Unit", "Stunt 101", "Poppin Them Thangs")
add("Lloyd Banks", "On Fire", "Karma")
add("Cam'ron", "Hey Ma", "Oh Boy")
add("Dipset", "Built This", "Santana's Town")
add("Jadakiss", "Why", "We Gonna Make It")
add("Fabolous", "Into You", "Can't Deny It", "Breathe")
add("Ja Rule", "Always On Time", "Mesmerize", "Livin It Up")
add("DMX", "X Gon Give It To Ya", "Party Up", "Where The Hood At", "Ruff Ryders Anthem")
add("Busta Rhymes", "Woo Hah", "Break Ya Neck", "Pass The Courvoisier", "Look At Me Now")
add("Missy Elliott", "Work It", "Get Ur Freak On", "Lose Control", "The Rain")
add("Lil Wayne", "A Milli", "Lollipop", "6 Foot 7 Foot", "Go DJ", "Mrs Officer")
add("Birdman", "Still Fly", "Money To Blow")
add("Young Money", "BedRock", "Every Girl")
add("Drake", "Hotline Bling", "One Dance", "God's Plan", "In My Feelings", "Started From The Bottom")
add("Travis Scott", "SICKO MODE", "goosebumps", "Highest In The Room", "FEIN")
add("Kendrick Lamar", "HUMBLE", "Alright", "DNA", "Swimming Pools", "Money Trees", "Not Like Us")
add("J Cole", "No Role Modelz", "Middle Child", "Work Out", "Power Trip")
add("Big Sean", "Blessings", "I Don't Fuck With You", "Bounce Back")
add("Logic", "1-800-273-8255", "Homicide", "Gang Related")
add("Joyner Lucas", "I'm Not Racist", "Lucky You")
add("Eminem ft Rihanna", "Love The Way You Lie")
add("Post Malone", "Congratulations", "Rockstar", "Sunflower", "Circles", "Better Now", "White Iverson")
add("21 Savage", "Bank Account", "a lot", "Rockstar")
add("Metro Boomin", "Mask Off", "Creepin")
add("Future", "Mask Off", "March Madness", "Low Life")
add("Young Thug", "Hot", "Best Friend", "Relationship")
add("Lil Uzi Vert", "XO Tour Llif3", "Money Longer", "Just Wanna Rock")
add("Playboi Carti", "Magnolia", "Sky", "Fein")
add("XXXTentacion", "Sad", "Moonlight", "Changes")
add("Juice WRLD", "Lucid Dreams", "Robbery", "All Girls Are The Same")
add("Pop Smoke", "Dior", "What You Know Bout Love", "For The Night")
add("King Von", "Crazy Story", "Took Her To The O")
add("Polo G", "Rapstar", "Pop Out")
add("Roddy Ricch", "The Box", "High Fashion")
add("DaBaby", "Rockstar", "Suge", "BOP")
add("Megan Thee Stallion", "Savage", "Body", "WAP")
add("Cardi B", "Bodak Yellow", "I Like It", "WAP")
add("Nicki Minaj", "Super Bass", "Anaconda", "Starships", "Moment 4 Life")
add("Doja Cat", "Say So", "Kiss Me More", "Paint The Town Red", "Woman")
add("SZA", "Kill Bill", "Snooze", "Good Days")
add("Summer Walker", "Playing Games", "Girls Need Love")
add("Brent Faiyaz", "Trust", "Dead Man Walking")
add("Giveon", "Heartbreak Anniversary")
add("Daniel Caesar", "Get You", "Best Part")
add("H.E.R.", "Best Part", "Focus", "Damage")
add("Frank Ocean", "Thinkin Bout You", "Pyramids", "Lost", "Pink White")
add("Tyler The Creator", "See You Again", "EARFQUAKE", "Yonkers", "NEW MAGIC WAND")
add("Childish Gambino", "Redbone", "This Is America", "3005")
add("Mac Miller", "Donald Trump", "Self Care", "Circles")
add("Chance The Rapper", "No Problem", "Same Drugs", "Sunday Candy")
add("Vince Staples", "Norf Norf", "Blue Suede")
add("Earl Sweatshirt", "Chum", "Grief")
add("MF DOOM", "All Caps", "Rapp Snitch Knishes")
add("Aesop Rock", "None Shall Pass", "Daylight")
add("Atmosphere", "GodLovesUgly", "Sunshine")
add("The Roots", "The Seed 2.0", "You Got Me")
add("Common", "The Light", "I Used To Love H.E.R.")
add("Kanye West", "Jesus Walks", "All Falls Down", "Through The Wire")
add("Lupe Fiasco", "Superstar", "Kick Push", "Daydreamin")
add("Talib Kweli", "Get By", "The Blast")
add("Mos Def", "Mathematics", "Ms Fat Booty")
add("Black Star", "Definition", "Respiration")
add("Gang Starr", "Mass Appeal", "Moment Of Truth", "Full Clip")
add("Pete Rock and CL Smooth", "They Reminisce Over You TROY")
add("Eric B and Rakim", "Paid In Full", "Don't Sweat The Technique")
add("Boogie Down Productions", "My Philosophy", "South Bronx")
add("KRS-One", "Sound of da Police", "MC's Act Like They Don't Know")
add("Slick Rick", "Children's Story", "La Di Da Di")
add("Doug E Fresh", "The Show", "La Di Da Di")
add("Whodini", "Friends", "Freaks Come Out At Night")
add("Grandmaster Flash", "The Message", "White Lines")
add("Afrika Bambaataa", "Planet Rock")
add("Sugarhill Gang", "Rapper's Delight")
add("Kurtis Blow", "The Breaks")
add("Blondie", "Rapture")
add("Beastie Boys", "Paul Revere", "Brass Monkey")
add("Beck", "Loser", "Where It's At", "Devils Haircut", "E-Pro")
add("Weezer", "Buddy Holly", "Say It Ain't So", "Island In The Sun")
add("Pixies", "Where Is My Mind", "Debaser")
add("Sonic Youth", "Teen Age Riot")
add("Pavement", "Cut Your Hair")
add("Built To Spill", "Car")
add("Modest Mouse", "Float On", "Dashboard")
add("Death Cab for Cutie", "I Will Follow You Into The Dark")
add("The Shins", "New Slang")
add("Bright Eyes", "First Day Of My Life")
add("Iron and Wine", "Flightless Bird American Mouth")
add("Bon Iver", "Skinny Love", "Holocene")
add("Fleet Foxes", "White Winter Hymnal")
add("Grizzly Bear", "Two Weeks")
add("Animal Collective", "My Girls")
add("Beach House", "Space Song")
add("Real Estate", "Talking Backwards")
add("Mac DeMarco", "Chamber of Reflection")
add("Tyler Childers", "Feathered Indians")
add("Chris Stapleton", "Tennessee Whiskey")
add("Luke Combs", "Beautiful Crazy")
add("Morgan Wallen", "Last Night")
add("Zach Bryan", "Something In The Orange")
add("Jason Aldean", "Dirt Road Anthem")
add("Florida Georgia Line", "Cruise")
add("Carrie Underwood", "Before He Cheats")
add("Shania Twain", "Man I Feel Like A Woman")
add("Garth Brooks", "Friends In Low Places")
add("Johnny Cash", "Ring Of Fire", "Hurt")
add("Dolly Parton", "Jolene", "9 to 5")
add("Willie Nelson", "On The Road Again")
add("Patsy Cline", "Crazy")
add("Hank Williams", "Your Cheatin Heart")
add("George Strait", "Amarillo By Morning")
add("Alan Jackson", "Chattahoochee")
add("Tim McGraw", "Live Like You Were Dying")
add("Blake Shelton", "God's Country")
add("Zac Brown Band", "Chicken Fried")
add("Lady A", "Need You Now")
add("Little Big Town", "Girl Crush")
add("The Chicks", "Not Ready To Make Nice")
add("A.R. Rahman", "Jai Ho")
add("Arijit Singh", "Tum Hi Ho")
add("Badshah", "Genda Phool")
add("AP Dhillon", "Brown Munde")
add("Sidhu Moose Wala", "295")
add("Stromae", "Alors On Danse", "Papaoutai", "Formidable")
add("Angèle", "Tout oublier", "Balance ton quoi")
add("Måneskin", "Beggin", "I Wanna Be Your Slave")
add("Eros Ramazzotti", "Più bella cosa")
add("Laura Pausini", "La solitudine")
add("Vasco Rossi", "Albachiara")
add("Alejandro Sanz", "Corazón partío")
add("Rosalía", "Malamente", "Despechá")
add("Camilo", "Vida de Rico")
add("Morat", "Cuando Nadie Ve")
add("Reik", "Noviembre sin ti")
add("Maná", "Rayando el sol")
add("Juanes", "La camisa negra")
add("Shakira", "La tortura")
add("Maluma", "Felices los 4")
add("J Balvin", "Mi Gente")
add("Bad Bunny", "Tití me preguntó", "Me porto bonito", "Dakiti", "Safaera")
add("Feid", "Chorrito pa las ánimas")
add("Karol G", "TQG", "Provenza")
add("Peso Pluma", "Ella baila sola", "La bebe")
add("Fuerza Regida", "Bebe dame")
add("Grupo Frontera", "Un x100to")
add("Eminem", "Stan", "Mockingbird", "Lose Yourself")
add("Radiohead", "Creep", "Karma Police", "Paranoid Android", "No Surprises", "Fake Plastic Trees")
add("Coldplay", "Yellow", "Fix You", "The Scientist", "Viva La Vida", "Clocks", "Paradise")
add("Foo Fighters", "Everlong", "The Pretender", "Best Of You", "Learn To Fly", "My Hero")
add("Red Hot Chili Peppers", "Under The Bridge", "Californication", "Can't Stop", "Scar Tissue", "Otherside")
add("Nirvana", "Smells Like Teen Spirit", "Come As You Are", "Lithium", "Heart-Shaped Box", "All Apologies")
add("Green Day", "Basket Case", "American Idiot", "Boulevard Of Broken Dreams", "Wake Me Up When September Ends")
add("Blink-182", "All The Small Things", "I Miss You", "What's My Age Again")
add("Sum 41", "In Too Deep", "Fat Lip")
add("The Offspring", "Pretty Fly", "Self Esteem")
add("Rage Against The Machine", "Killing In The Name", "Bulls On Parade")
add("Tool", "Schism", "Forty Six and 2", "Vicarious")
add("Nine Inch Nails", "Closer", "Hurt", "Head Like A Hole")
add("Deftones", "Change In The House Of Flies", "My Own Summer")
add("Avenged Sevenfold", "Nightmare", "Hail To The King")
add("Bring Me The Horizon", "Can You Feel My Heart")
add("Ghost", "Square Hammer", "Mary On A Cross")
add("Sabaton", "Primo Victoria")
add("Nightwish", "Nemo")
add("Halestorm", "I Miss The Misery")
add("Paramore", "Misery Business", "Still Into You", "The Only Exception")
add("Fall Out Boy", "Sugar We're Goin Down", "Centuries")
add("My Chemical Romance", "Welcome To The Black Parade", "Helena")
add("Panic At The Disco", "I Write Sins Not Tragedies", "High Hopes")
add("Jimmy Eat World", "The Middle")
add("Yellowcard", "Ocean Avenue")
add("All Time Low", "Dear Maria Count Me In")
add("Neck Deep", "Wish You Were Here")
add("Turnstile", "BLACKOUT")
add("The 1975", "Chocolate", "Somebody Else")
add("Arctic Monkeys", "Do I Wanna Know", "R U Mine", "505")
add("The Strokes", "Last Nite", "Reptilia")
add("The Killers", "Mr Brightside", "Somebody Told Me", "When You Were Young")
add("Muse", "Starlight", "Uprising", "Supermassive Black Hole")
add("Oasis", "Wonderwall", "Don't Look Back In Anger", "Champagne Supernova")
add("Blur", "Song 2", "Parklife")
add("Radiohead", "High and Dry", "Street Spirit")
add("Massive Attack", "Teardrop", "Unfinished Sympathy")
add("Portishead", "Glory Box")
add("Gorillaz", "Feel Good Inc", "Clint Eastwood", "On Melancholy Hill")
add("M.I.A.", "Paper Planes")
add("LCD Soundsystem", "Dance Yrself Clean", "All My Friends")
add("Arcade Fire", "Wake Up", "The Suburbs")
add("Vampire Weekend", "A-Punk", "Harmony Hall")
add("Tame Impala", "The Less I Know The Better", "Let It Happen")
add("Glass Animals", "Heat Waves", "Gooey")
add("Foster The People", "Pumped Up Kicks")
add("MGMT", "Kids", "Electric Feel")
add("Phoenix", "1901", "Lisztomania")
add("Two Door Cinema Club", "What You Know")
add("Bastille", "Pompeii")
add("Imagine Dragons", "Radioactive", "Believer", "Demons")
add("Walk The Moon", "Shut Up And Dance")
add("Of Monsters and Men", "Little Talks")
add("Mumford and Sons", "Little Lion Man", "I Will Wait")
add("The Lumineers", "Ho Hey", "Ophelia")
add("Lord Huron", "The Night We Met")
add("Hozier", "Take Me To Church")
add("Kaleo", "Way Down We Go")
add("Royal Blood", "Figure It Out")
add("Nothing But Thieves", "Amsterdam")

lines: list[str] = []
for artist, titles in BULK.items():
    for title in titles:
        t = title.strip()
        if t:
            lines.append(f"{artist} {t}")

# dedupe preserving order
seen: set[str] = set()
unique: list[str] = []
for s in lines:
    k = s.lower()
    if k in seen:
        continue
    seen.add(k)
    unique.append(s)

OUT.write_text("\n".join(unique) + "\n", encoding="utf-8")
print(f"Wrote {len(unique)} lines to {OUT.name}")
