#!/usr/bin/env python3
"""Generate scripts/famous_hits_fill.py from unparsed bulk/build lines + mega-hit seed list."""
from __future__ import annotations

import importlib.util
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCRIPTS = Path(__file__).resolve().parent

# Hand-formatted from bulk/build lines that resist auto-parse (Title - Artist).
MANUAL_LINES = [
    "Ain't Nobody - Chaka Khan",
    "Tainted Love - Soft Cell",
    "No Rain - Blind Melon",
    "Hunger Strike - Temple Of The Dog",
    "Otro Trago - Sech ft Darell",
    "Slow Dancing - V",
    "Daechwita - SUGA",
    "Somebody Like You - Keith Urban",
    "Heaven - Kane Brown",
    "I Can't Help Myself - Four Tops",
    "Funkytown - Lipps Inc",
    "99 Luftballons - Nena",
    "Take On Me - a-ha",
    "Total Eclipse Of The Heart - Bonnie Tyler",
    "Ace Of Spades - Motörhead",
    "Somebody That I Used To Know - Gotye ft Kimbra",
    "Lifestyles Of The Rich And Famous - Good Charlotte",
    "Screaming Infidelities - Dashboard Confessional",
    "Take Me Out - Franz Ferdinand",
    "Understand - Omah Lay",
    "Joha - Asake",
    "Peru - Fireboy DML",
    "Johnny - Yemi Alade",
    "Girlie O - Patoranking",
    "Djadja - Aya Nakamura",
    "Tout Oublier - Angèle",
    "Love Me Again - V",
    "M - Ayumi Hamasaki",
    "Children - Robert Miles",
    "We Will Rock You - Queen",
    "We Are The Champions - Queen",
    "I Got A Woman - Ray Charles",
    "Just Can't Get Enough - Depeche Mode",
    "Empire State Of Mind - Jay-Z ft Alicia Keys",
    "Run This Town - Jay-Z ft Rihanna",
    "All Of The Lights - Kanye West",
    "Drop It Like It's Hot - Snoop Dogg",
    "Say It Right - Nelly Furtado",
    "Big Girls Don't Cry - Fergie",
    "Buy U A Drank - T-Pain",
    "Good Feeling - Flo Rida",
    "Without You - David Guetta ft Usher",
    "Hips Don't Lie - Shakira ft Wyclef Jean",
    "La Tortura - Shakira ft Alejandro Sanz",
    "Felices Los 4 - Maluma",
    "A Bar Song - Shaboozey",
]

# Global mega-hits likely missing from the main catalog (Title - Artist).
MEGA_HITS = [
    "My Way - Frank Sinatra",
    "What A Wonderful World - Louis Armstrong",
    "Stand By Me - Ben E. King",
    "I Will Survive - Gloria Gaynor",
    "Dancing In The Dark - Bruce Springsteen",
    "Born To Run - Bruce Springsteen",
    "Like A Rolling Stone - Bob Dylan",
    "Blowin' In The Wind - Bob Dylan",
    "Hallelujah - Leonard Cohen",
    "Fast Car - Tracy Chapman",
    "No Scrubs - TLC",
    "Waterfalls - TLC",
    "Say My Name - Destiny's Child",
    "Survivor - Destiny's Child",
    "Independent Women - Destiny's Child",
    "Genie In A Bottle - Christina Aguilera",
    "Complicated - Avril Lavigne",
    "Sk8er Boi - Avril Lavigne",
    "Toxic - Britney Spears",
    "Oops!... I Did It Again - Britney Spears",
    "Baby One More Time - Britney Spears",
    "Wannabe - Spice Girls",
    "Say You'll Be There - Spice Girls",
    "Spice Up Your Life - Spice Girls",
    "I Want It That Way - Backstreet Boys",
    "Everybody - Backstreet Boys",
    "Bye Bye Bye - NSYNC",
    "It's Gonna Be Me - NSYNC",
    "Tearin' Up My Heart - NSYNC",
    "MMMBop - Hanson",
    "All Star - Smash Mouth",
    "I'm A Believer - Smash Mouth",
    "All The Small Things - blink-182",
    "What's My Age Again? - blink-182",
    "In The End - Linkin Park",
    "Numb - Linkin Park",
    "Crawling - Linkin Park",
    "Bring Me To Life - Evanescence",
    "My Immortal - Evanescence",
    "Boulevard Of Broken Dreams - Green Day",
    "Wake Me Up When September Ends - Green Day",
    "Basket Case - Green Day",
    "American Idiot - Green Day",
    "Sex On Fire - Kings of Leon",
    "Use Somebody - Kings of Leon",
    "Pumped Up Kicks - Foster The People",
    "Somebody That I Used To Know - Gotye ft Kimbra",
    "Royals - Lorde",
    "Team - Lorde",
    "Green Light - Lorde",
    "Bad Guy - Billie Eilish",
    "Happier Than Ever - Billie Eilish",
    "Therefore I Am - Billie Eilish",
    "Lovely - Billie Eilish ft Khalid",
    "Sunflower - Post Malone ft Swae Lee",
    "Circles - Post Malone",
    "Rockstar - Post Malone ft 21 Savage",
    "Congratulations - Post Malone",
    "God's Plan - Drake",
    "Hotline Bling - Drake",
    "One Dance - Drake",
    "In My Feelings - Drake",
    "Nice For What - Drake",
    "Sicko Mode - Travis Scott",
    "Goosebumps - Travis Scott",
    "Highest In The Room - Travis Scott",
    "Starboy - The Weeknd ft Daft Punk",
    "Can't Feel My Face - The Weeknd",
    "The Hills - The Weeknd",
    "Save Your Tears - The Weeknd",
    "Blinding Lights - The Weeknd",
    "Levitating - Dua Lipa",
    "Don't Start Now - Dua Lipa",
    "New Rules - Dua Lipa",
    "Shallow - Lady Gaga ft Bradley Cooper",
    "Bad Romance - Lady Gaga",
    "Poker Face - Lady Gaga",
    "Just Dance - Lady Gaga",
    "Rolling In The Deep - Adele",
    "Someone Like You - Adele",
    "Hello - Adele",
    "Set Fire To The Rain - Adele",
    "Easy On Me - Adele",
    "Uptown Funk - Mark Ronson ft Bruno Mars",
    "24K Magic - Bruno Mars",
    "That's What I Like - Bruno Mars",
    "When I Was Your Man - Bruno Mars",
    "Locked Out Of Heaven - Bruno Mars",
    "Treasure - Bruno Mars",
    "Despacito - Luis Fonsi ft Daddy Yankee",
    "Bailando - Enrique Iglesias",
    "El Perdón - Nicky Jam ft Enrique Iglesias",
    "Mi Gente - J Balvin ft Willy William",
    "Ginza - J Balvin",
    "Taki Taki - DJ Snake ft Selena Gomez, Ozuna, Cardi B",
    "Con Calma - Daddy Yankee ft Snow",
    "Dákiti - Bad Bunny ft Jhay Cortez",
    "Tití Me Preguntó - Bad Bunny",
    "Me Porto Bonito - Bad Bunny ft Chencho Corleone",
    "Safaera - Bad Bunny",
    "I Like It - Cardi B, Bad Bunny, J Balvin",
    "WAP - Cardi B ft Megan Thee Stallion",
    "Bodak Yellow - Cardi B",
    "Savage - Megan Thee Stallion",
    "WAP - Cardi B ft Megan Thee Stallion",
    "Industry Baby - Lil Nas X ft Jack Harlow",
    "Old Town Road - Lil Nas X ft Billy Ray Cyrus",
    "MONTERO - Lil Nas X",
    "Peaches - Justin Bieber ft Daniel Caesar, Giveon",
    "Sorry - Justin Bieber",
    "Love Yourself - Justin Bieber",
    "What Do You Mean? - Justin Bieber",
    "Baby - Justin Bieber ft Ludacris",
    "Stay - The Kid LAROI ft Justin Bieber",
    "7 Rings - Ariana Grande",
    "Thank U, Next - Ariana Grande",
    "Positions - Ariana Grande",
    "Problem - Ariana Grande ft Iggy Azalea",
    "Side To Side - Ariana Grande ft Nicki Minaj",
    "Shake It Off - Taylor Swift",
    "Blank Space - Taylor Swift",
    "Anti-Hero - Taylor Swift",
    "Cruel Summer - Taylor Swift",
    "Love Story - Taylor Swift",
    "You Belong With Me - Taylor Swift",
    "Look What You Made Me Do - Taylor Swift",
    "We Are Never Ever Getting Back Together - Taylor Swift",
    "Style - Taylor Swift",
    "All Too Well - Taylor Swift",
    "Flowers - Miley Cyrus",
    "Wrecking Ball - Miley Cyrus",
    "Party In The U.S.A. - Miley Cyrus",
    "Firework - Katy Perry",
    "Roar - Katy Perry",
    "Dark Horse - Katy Perry",
    "Teenage Dream - Katy Perry",
    "California Gurls - Katy Perry ft Snoop Dogg",
    "Hot N Cold - Katy Perry",
    "I Kissed A Girl - Katy Perry",
    "Call Me Maybe - Carly Rae Jepsen",
    "Gangnam Style - PSY",
    "Dynamite - BTS",
    "Butter - BTS",
    "Permission To Dance - BTS",
    "Boy With Luv - BTS ft Halsey",
    "DNA - BTS",
    "Fake Love - BTS",
    "Spring Day - BTS",
    "Kill This Love - BLACKPINK",
    "How You Like That - BLACKPINK",
    "DDU-DU DDU-DU - BLACKPINK",
    "Pink Venom - BLACKPINK",
    "Shut Down - BLACKPINK",
    "As If It's Your Last - BLACKPINK",
    "Next Level - aespa",
    "Super Shy - NewJeans",
    "Ditto - NewJeans",
    "OMG - NewJeans",
    "Attention - NewJeans",
    "Cupid - FIFTY FIFTY",
    "Unholy - Sam Smith ft Kim Petras",
    "Stay With Me - Sam Smith",
    "Too Good At Goodbyes - Sam Smith",
    "About Damn Time - Lizzo",
    "Truth Hurts - Lizzo",
    "Good As Hell - Lizzo",
    "Heat Waves - Glass Animals",
    "As It Was - Harry Styles",
    "Watermelon Sugar - Harry Styles",
    "Sign Of The Times - Harry Styles",
    "Adore You - Harry Styles",
    "drivers license - Olivia Rodrigo",
    "good 4 u - Olivia Rodrigo",
    "vampire - Olivia Rodrigo",
    "deja vu - Olivia Rodrigo",
    "Montero - Lil Nas X",
    "Industry Baby - Lil Nas X ft Jack Harlow",
    "Beautiful Things - Benson Boone",
    "Greedy - Tate McRae",
    "Espresso - Sabrina Carpenter",
    "Please Please Please - Sabrina Carpenter",
    "Birds Of A Feather - Billie Eilish",
    "Beautiful - Christina Aguilera",
    "Hurt - Christina Aguilera",
    "Genie In A Bottle - Christina Aguilera",
    "Say Something - A Great Big World ft Christina Aguilera",
    "Moves Like Jagger - Maroon 5 ft Christina Aguilera",
    "Sugar - Maroon 5",
    "Girls Like You - Maroon 5 ft Cardi B",
    "Memories - Maroon 5",
    "Maps - Maroon 5",
    "Animals - Maroon 5",
    "Payphone - Maroon 5 ft Wiz Khalifa",
    "One More Night - Maroon 5",
    "This Love - Maroon 5",
    "She Will Be Loved - Maroon 5",
    "Sunday Morning - Maroon 5",
    "Harder To Breathe - Maroon 5",
    "Radioactive - Imagine Dragons",
    "Believer - Imagine Dragons",
    "Thunder - Imagine Dragons",
    "Demons - Imagine Dragons",
    "Whatever It Takes - Imagine Dragons",
    "Natural - Imagine Dragons",
    "Bones - Imagine Dragons",
    "Enemy - Imagine Dragons ft JID",
    "Counting Stars - OneRepublic",
    "Apologize - OneRepublic",
    "Secrets - OneRepublic",
    "Good Life - OneRepublic",
    "Stop And Stare - OneRepublic",
    "Hall Of Fame - The Script ft will.i.am",
    "Breakeven - The Script",
    "Superheroes - The Script",
    "The Man Who Can't Be Moved - The Script",
    "Chandelier - Sia",
    "Elastic Heart - Sia",
    "Cheap Thrills - Sia",
    "Unstoppable - Sia",
    "Titanium - David Guetta ft Sia",
    "Wake Me Up - Avicii",
    "Levels - Avicii",
    "Hey Brother - Avicii",
    "Waiting For Love - Avicii",
    "The Nights - Avicii",
    "Without You - Avicii ft Sandro Cavazza",
    "Faded - Alan Walker",
    "Alone - Alan Walker",
    "Darkside - Alan Walker ft Au/Ra, Tomine Harket",
    "Closer - The Chainsmokers ft Halsey",
    "Don't Let Me Down - The Chainsmokers ft Daya",
    "Something Just Like This - The Chainsmokers ft Coldplay",
    "Paris - The Chainsmokers",
    "Roses - The Chainsmokers ft ROZES",
    "Takeaway - The Chainsmokers ft ILLENIUM ft Lennon Stella",
    "Stressed Out - Twenty One Pilots",
    "Heathens - Twenty One Pilots",
    "Ride - Twenty One Pilots",
    "Car Radio - Twenty One Pilots",
    "House Of Gold - Twenty One Pilots",
    "Chlorine - Twenty One Pilots",
    "High Hopes - Panic! At The Disco",
    "I Write Sins Not Tragedies - Panic! At The Disco",
    "Victorious - Panic! At The Disco",
    "Misery Business - Paramore",
    "Still Into You - Paramore",
    "The Only Exception - Paramore",
    "Decode - Paramore",
    "Ain't It Fun - Paramore",
    "The Middle - Jimmy Eat World",
    "Sweetness - Jimmy Eat World",
    "Mr. Brightside - The Killers",
    "Somebody Told Me - The Killers",
    "When You Were Young - The Killers",
    "Human - The Killers",
    "Read My Mind - The Killers",
    "Do I Wanna Know? - Arctic Monkeys",
    "R U Mine? - Arctic Monkeys",
    "505 - Arctic Monkeys",
    "Fluorescent Adolescent - Arctic Monkeys",
    "Why'd You Only Call Me When You're High? - Arctic Monkeys",
    "Last Nite - The Strokes",
    "Reptilia - The Strokes",
    "You Only Live Once - The Strokes",
    "Under Cover Of Darkness - The Strokes",
    "Seven Nation Army - The White Stripes",
    "Fell In Love With A Girl - The White Stripes",
    "Ho Hey - The Lumineers",
    "Ophelia - The Lumineers",
    "Stubborn Love - The Lumineers",
    "Little Talks - Of Monsters and Men",
    "Dirty Paws - Of Monsters and Men",
    "Riptide - Vance Joy",
    "Fire And The Flood - Vance Joy",
    "Take Me To Church - Hozier",
    "Someone New - Hozier",
    "Work Song - Hozier",
    "Let Her Go - Passenger",
    "All Of Me - John Legend",
    "Ordinary People - John Legend",
    "Glory - John Legend ft Common",
    "Thinking Out Loud - Ed Sheeran",
    "Shape Of You - Ed Sheeran",
    "Perfect - Ed Sheeran",
    "Photograph - Ed Sheeran",
    "Castle On The Hill - Ed Sheeran",
    "Bad Habits - Ed Sheeran",
    "Shivers - Ed Sheeran",
    "Galway Girl - Ed Sheeran",
    "The A Team - Ed Sheeran",
    "Lego House - Ed Sheeran",
    "Sing - Ed Sheeran",
    "Don't - Ed Sheeran",
    "Happier - Ed Sheeran",
    "Beautiful People - Ed Sheeran ft Khalid",
    "I Don't Care - Ed Sheeran ft Justin Bieber",
    "South Of The Border - Ed Sheeran ft Camila Cabello, Cardi B",
    "Someone You Loved - Lewis Capaldi",
    "Before You Go - Lewis Capaldi",
    "Hold Me While You Wait - Lewis Capaldi",
    "Dance Monkey - Tones And I",
    "Fly Me To The Moon - Frank Sinatra",
    "New York, New York - Frank Sinatra",
    "The Way You Look Tonight - Frank Sinatra",
    "Unforgettable - Nat King Cole",
    "L-O-V-E - Nat King Cole",
    "At Last - Etta James",
    "Respect - Aretha Franklin",
    "Chain Of Fools - Aretha Franklin",
    "Natural Woman - Aretha Franklin",
    "What's Going On - Marvin Gaye",
    "Let's Get It On - Marvin Gaye",
    "Sexual Healing - Marvin Gaye",
    "Superstition - Stevie Wonder",
    "Isn't She Lovely - Stevie Wonder",
    "Signed, Sealed, Delivered I'm Yours - Stevie Wonder",
    "I Just Called To Say I Love You - Stevie Wonder",
    "Purple Rain - Prince",
    "When Doves Cry - Prince",
    "Kiss - Prince",
    "1999 - Prince",
    "Little Red Corvette - Prince",
    "Raspberry Beret - Prince",
    "Let's Go Crazy - Prince",
    "Cream - Prince",
    "Nothing Compares 2 U - Sinead O'Connor",
    "Losing My Religion - R.E.M.",
    "Everybody Hurts - R.E.M.",
    "Man On The Moon - R.E.M.",
    "It's The End Of The World As We Know It - R.E.M.",
    "Creep - Radiohead",
    "Karma Police - Radiohead",
    "Paranoid Android - Radiohead",
    "No Surprises - Radiohead",
    "Fake Plastic Trees - Radiohead",
    "High And Dry - Radiohead",
    "Street Spirit - Radiohead",
    "Yellow - Coldplay",
    "Fix You - Coldplay",
    "The Scientist - Coldplay",
    "Viva La Vida - Coldplay",
    "Clocks - Coldplay",
    "Paradise - Coldplay",
    "Adventure Of A Lifetime - Coldplay",
    "A Sky Full Of Stars - Coldplay",
    "Hymn For The Weekend - Coldplay",
    "Something Just Like This - Coldplay ft The Chainsmokers",
    "Everlong - Foo Fighters",
    "The Pretender - Foo Fighters",
    "Best Of You - Foo Fighters",
    "Learn To Fly - Foo Fighters",
    "My Hero - Foo Fighters",
    "Times Like These - Foo Fighters",
    "All My Life - Foo Fighters",
    "The Best - Tina Turner",
    "Proud Mary - Tina Turner",
    "Private Dancer - Tina Turner",
    "Total Eclipse Of The Heart - Bonnie Tyler",
    "Holding Out For A Hero - Bonnie Tyler",
    "Eye Of The Tiger - Survivor",
    "Burning Heart - Survivor",
    "Don't Stop Believin' - Journey",
    "Separate Ways - Journey",
    "Any Way You Want It - Journey",
    "Open Arms - Journey",
    "Faithfully - Journey",
    "Livin' On A Prayer - Bon Jovi",
    "It's My Life - Bon Jovi",
    "Always - Bon Jovi",
    "Bed Of Roses - Bon Jovi",
    "You Give Love A Bad Name - Bon Jovi",
    "Wanted Dead Or Alive - Bon Jovi",
    "Sweet Child O' Mine - Guns N' Roses",
    "November Rain - Guns N' Roses",
    "Paradise City - Guns N' Roses",
    "Welcome To The Jungle - Guns N' Roses",
    "Patience - Guns N' Roses",
    "Don't Cry - Guns N' Roses",
    "Enter Sandman - Metallica",
    "Nothing Else Matters - Metallica",
    "One - Metallica",
    "Master Of Puppets - Metallica",
    "Fade To Black - Metallica",
    "The Unforgiven - Metallica",
    "Back In Black - AC/DC",
    "Highway To Hell - AC/DC",
    "Thunderstruck - AC/DC",
    "You Shook Me All Night Long - AC/DC",
    "T.N.T. - AC/DC",
    "For Those About To Rock - AC/DC",
    "Stairway To Heaven - Led Zeppelin",
    "Whole Lotta Love - Led Zeppelin",
    "Black Dog - Led Zeppelin",
    "Immigrant Song - Led Zeppelin",
    "Kashmir - Led Zeppelin",
    "Rock And Roll - Led Zeppelin",
    "Going To California - Led Zeppelin",
    "When The Levee Breaks - Led Zeppelin",
    "Comfortably Numb - Pink Floyd",
    "Wish You Were Here - Pink Floyd",
    "Another Brick In The Wall - Pink Floyd",
    "Money - Pink Floyd",
    "Time - Pink Floyd",
    "Shine On You Crazy Diamond - Pink Floyd",
    "Us And Them - Pink Floyd",
    "Brain Damage - Pink Floyd",
    "Hey Jude - The Beatles",
    "Let It Be - The Beatles",
    "Yesterday - The Beatles",
    "Come Together - The Beatles",
    "Here Comes The Sun - The Beatles",
    "Something - The Beatles",
    "Twist And Shout - The Beatles",
    "I Want To Hold Your Hand - The Beatles",
    "A Day In The Life - The Beatles",
    "Help! - The Beatles",
    "Yellow Submarine - The Beatles",
    "Eleanor Rigby - The Beatles",
    "Blackbird - The Beatles",
    "While My Guitar Gently Weeps - The Beatles",
    "Paint It Black - The Rolling Stones",
    "Gimme Shelter - The Rolling Stones",
    "Sympathy For The Devil - The Rolling Stones",
    "Angie - The Rolling Stones",
    "Wild Horses - The Rolling Stones",
    "Miss You - The Rolling Stones",
    "Start Me Up - The Rolling Stones",
    "Satisfaction - The Rolling Stones",
    "Jumpin' Jack Flash - The Rolling Stones",
    "Brown Sugar - The Rolling Stones",
    "Hotel California - Eagles",
    "Take It Easy - Eagles",
    "Desperado - Eagles",
    "One Of These Nights - Eagles",
    "New Kid In Town - Eagles",
    "Life In The Fast Lane - Eagles",
    "Sweet Home Alabama - Lynyrd Skynyrd",
    "Free Bird - Lynyrd Skynyrd",
    "Simple Man - Lynyrd Skynyrd",
    "More Than A Feeling - Boston",
    "Peace Of Mind - Boston",
    "Carry On Wayward Son - Kansas",
    "Dust In The Wind - Kansas",
    "Africa - Toto",
    "Hold The Line - Toto",
    "Rosanna - Toto",
    "I Love Rock 'N Roll - Joan Jett",
    "Pour Some Sugar On Me - Def Leppard",
    "Love Bites - Def Leppard",
    "Photograph - Def Leppard",
    "Jump - Van Halen",
    "Panama - Van Halen",
    "Hot For Teacher - Van Halen",
    "Don't Stop Me Now - Queen",
    "Another One Bites The Dust - Queen",
    "Somebody To Love - Queen",
    "Under Pressure - Queen ft David Bowie",
    "Crazy Little Thing Called Love - Queen",
    "Killer Queen - Queen",
    "Radio Ga Ga - Queen",
    "I Want To Break Free - Queen",
    "Smells Like Teen Spirit - Nirvana",
    "Come As You Are - Nirvana",
    "Lithium - Nirvana",
    "Heart-Shaped Box - Nirvana",
    "All Apologies - Nirvana",
    "Black Hole Sun - Soundgarden",
    "Spoonman - Soundgarden",
    "Man In The Box - Alice In Chains",
    "Rooster - Alice In Chains",
    "Jeremy - Pearl Jam",
    "Alive - Pearl Jam",
    "Even Flow - Pearl Jam",
    "Yellow Ledbetter - Pearl Jam",
    "Killing In The Name - Rage Against The Machine",
    "Bulls On Parade - Rage Against The Machine",
    "Californication - Red Hot Chili Peppers",
    "Under The Bridge - Red Hot Chili Peppers",
    "Can't Stop - Red Hot Chili Peppers",
    "Scar Tissue - Red Hot Chili Peppers",
    "Otherside - Red Hot Chili Peppers",
    "Dani California - Red Hot Chili Peppers",
    "Snow - Red Hot Chili Peppers",
    "Give It Away - Red Hot Chili Peppers",
    "By The Way - Red Hot Chili Peppers",
    "Wonderwall - Oasis",
    "Don't Look Back In Anger - Oasis",
    "Champagne Supernova - Oasis",
    "Live Forever - Oasis",
    "Song 2 - Blur",
    "Parklife - Blur",
    "Teardrop - Massive Attack",
    "Unfinished Sympathy - Massive Attack",
    "Feel Good Inc. - Gorillaz",
    "Clint Eastwood - Gorillaz",
    "On Melancholy Hill - Gorillaz",
    "Paper Planes - M.I.A.",
    "Bad Romance - Lady Gaga",
    "Poker Face - Lady Gaga",
    "Born This Way - Lady Gaga",
    "Alejandro - Lady Gaga",
    "Paparazzi - Lady Gaga",
    "Telephone - Lady Gaga ft Beyoncé",
    "Million Reasons - Lady Gaga",
    "Rain On Me - Lady Gaga ft Ariana Grande",
    "Single Ladies - Beyoncé",
    "Crazy In Love - Beyoncé ft Jay-Z",
    "Halo - Beyoncé",
    "Irreplaceable - Beyoncé",
    "If I Were A Boy - Beyoncé",
    "Run The World - Beyoncé",
    "Formation - Beyoncé",
    "Break My Soul - Beyoncé",
    "Texas Hold 'Em - Beyoncé",
    "Umbrella - Rihanna ft Jay-Z",
    "We Found Love - Rihanna ft Calvin Harris",
    "Diamonds - Rihanna",
    "Work - Rihanna ft Drake",
    "Only Girl - Rihanna",
    "Stay - Rihanna ft Mikky Ekko",
    "Disturbia - Rihanna",
    "Rude Boy - Rihanna",
    "Needed Me - Rihanna",
    "Yeah! - Usher ft Lil Jon, Ludacris",
    "Burn - Usher",
    "U Got It Bad - Usher",
    "DJ Got Us Fallin' In Love - Usher ft Pitbull",
    "OMG - Usher ft will.i.am",
    "Love In This Club - Usher",
    "Scream - Usher",
    "My Boo - Usher ft Alicia Keys",
    "Fallin' - Alicia Keys",
    "No One - Alicia Keys",
    "Girl On Fire - Alicia Keys",
    "If I Ain't Got You - Alicia Keys",
    "Empire State Of Mind - Alicia Keys ft Jay-Z",
    "Super Bass - Nicki Minaj",
    "Starships - Nicki Minaj",
    "Anaconda - Nicki Minaj",
    "Bang Bang - Jessie J ft Ariana Grande, Nicki Minaj",
    "Pound The Alarm - Nicki Minaj",
    "Moment 4 Life - Nicki Minaj ft Drake",
    "Low - Flo Rida ft T-Pain",
    "Right Round - Flo Rida ft Ke$ha",
    "Club Can't Handle Me - Flo Rida ft David Guetta",
    "Whistle - Flo Rida",
    "My House - Flo Rida",
    "Timber - Pitbull ft Kesha",
    "Give Me Everything - Pitbull ft Ne-Yo, Afrojack, Nayer",
    "International Love - Pitbull ft Chris Brown",
    "Fireball - Pitbull ft John Ryan",
    "I Know You Want Me - Pitbull",
    "Hotel Room Service - Pitbull",
    "Rain Over Me - Pitbull ft Marc Anthony",
    "On The Floor - Jennifer Lopez ft Pitbull",
    "If You Had My Love - Jennifer Lopez",
    "Jenny From The Block - Jennifer Lopez",
    "Let's Get Loud - Jennifer Lopez",
    "Waiting For Tonight - Jennifer Lopez",
    "Ain't Your Mama - Jennifer Lopez",
    "Gasolina - Daddy Yankee",
    "Limbo - Daddy Yankee",
    "Shaky Shaky - Daddy Yankee",
    "Dura - Daddy Yankee",
    "X - Nicky Jam ft J Balvin, Maluma, Ozuna",
    "Te Boté - Casper, Nio García, Darell, Nicky Jam, Bad Bunny, Ozuna",
    "Ella Baila Sola - Eslabon Armado ft Peso Pluma",
    "La Bebé - Yng Lvcas ft Peso Pluma",
    "Bzrp Music Sessions Vol. 53 - Shakira ft Bizarrap",
    "TQG - Karol G ft Shakira",
    "Provenza - Karol G",
    "Tusa - Karol G ft Nicki Minaj",
    "Bichota - Karol G",
    "MAMIII - Becky G ft Karol G",
    "Sin Pijama - Becky G ft Natti Natasha",
    "Mayores - Becky G ft Bad Bunny",
    "Dakiti - Bad Bunny ft Jhay Cortez",
    "Yonaguni - Bad Bunny",
    "Moscow Mule - Bad Bunny",
    "Efecto - Bad Bunny",
    "Volví - Aventura ft Bad Bunny",
    "Obsesión - Aventura",
    "Propuesta Indecente - Romeo Santos",
    "Eres Mía - Romeo Santos",
    "Imitadora - Romeo Santos",
    "Bailamos - Enrique Iglesias",
    "Hero - Enrique Iglesias",
    "Escape - Enrique Iglesias",
    "Subeme La Radio - Enrique Iglesias ft Descemer Bueno, Zion & Lennox",
    "Chantaje - Shakira ft Maluma",
    "Waka Waka - Shakira",
    "Whenever, Wherever - Shakira",
    "Underneath Your Clothes - Shakira",
    "She Wolf - Shakira",
    "Try Everything - Shakira",
    "Garota De Ipanema - Stan Getz ft João Gilberto",
    "Mas Que Nada - Sergio Mendes",
    "Ai Se Eu Te Pego - Michel Teló",
    "Balada - Gusttavo Lima",
    "Evolution - Alok ft The Chainsmokers",
    "Hear Me Now - Alok ft Zeeba",
    "Don't Say Goodbye - Alok ft Ilkay Sencan",
    "Infinity - Jaymes Young",
    "Head & Heart - Joel Corry ft MNEK",
    "Don't Start Now - Dua Lipa",
    "Physical - Dua Lipa",
    "Break My Heart - Dua Lipa",
    "IDGAF - Dua Lipa",
    "Be The One - Dua Lipa",
    "New Love - Dua Lipa",
    "Training Season - Dua Lipa",
    "Houdini - Dua Lipa",
    "Paint The Town Red - Doja Cat",
    "Woman - Doja Cat",
    "Kiss Me More - Doja Cat ft SZA",
    "Say So - Doja Cat",
    "Need To Know - Doja Cat",
    "Streets - Doja Cat",
    "Best Friend - Saweetie ft Doja Cat",
    "My Type - Saweetie",
    "Tap In - Saweetie",
    "Up - Cardi B",
    "I Like It - Cardi B, Bad Bunny, J Balvin",
    "Please Me - Cardi B ft Bruno Mars",
    "Money - Cardi B",
    "Be Careful - Cardi B",
    "Girls Like You - Maroon 5 ft Cardi B",
    "Finesse - Bruno Mars ft Cardi B",
    "That's What I Like - Bruno Mars",
    "24K Magic - Bruno Mars",
    "Uptown Funk - Mark Ronson ft Bruno Mars",
    "Treasure - Bruno Mars",
    "Grenade - Bruno Mars",
    "Just The Way You Are - Bruno Mars",
    "The Lazy Song - Bruno Mars",
    "Marry You - Bruno Mars",
    "Count On Me - Bruno Mars",
    "It Will Rain - Bruno Mars",
    "When I Was Your Man - Bruno Mars",
    "Locked Out Of Heaven - Bruno Mars",
    "Versace On The Floor - Bruno Mars",
    "Leave The Door Open - Silk Sonic",
    "Skate - Silk Sonic",
    "Smokin Out The Window - Silk Sonic",
    "Die With A Smile - Lady Gaga ft Bruno Mars",
    "APT. - ROSÉ ft Bruno Mars",
]

# Second pass: deeper classics and global hits often absent from the main pool.
EXTRA_MEGA_HITS = [
    "Volare - Domenico Modugno",
    "Nel Blu Dipinto Di Blu - Domenico Modugno",
    "La Bamba - Ritchie Valens",
    "Macarena - Los Del Rio",
    "Lambada - Kaoma",
    "Besame Mucho - Consuelo Velázquez",
    "Guantanamera - Celia Cruz",
    "Bamboleo - Gipsy Kings",
    "Gasolina - Daddy Yankee",
    "Danza Kuduro - Don Omar ft Lucenzo",
    "Danza Kuduro - Lucenzo ft Don Omar",
    "Bailando - Enrique Iglesias ft Descemer Bueno, Gente De Zona",
    "El Taxi - Osmani Garcia ft Pitbull, Sensato",
    "Gangsta's Paradise - Coolio ft L.V.",
    "California Love - 2Pac ft Dr. Dre",
    "Changes - 2Pac",
    "Dear Mama - 2Pac",
    "Hit 'Em Up - 2Pac",
    "Juicy - The Notorious B.I.G.",
    "Big Poppa - The Notorious B.I.G.",
    "Hypnotize - The Notorious B.I.G.",
    "Mo Money Mo Problems - The Notorious B.I.G. ft Puff Daddy, Mase",
    "Nuthin' But A G Thang - Dr. Dre ft Snoop Dogg",
    "Still D.R.E. - Dr. Dre ft Snoop Dogg",
    "Forgot About Dre - Dr. Dre ft Eminem",
    "The Next Episode - Dr. Dre ft Snoop Dogg",
    "In Da Club - 50 Cent",
    "Candy Shop - 50 Cent ft Olivia",
    "Many Men - 50 Cent",
    "Lean Back - Terror Squad ft Fat Joe, Remy Ma",
    "What's Luv? - Fat Joe ft Ashanti",
    "All The Way Up - Fat Joe ft Remy Ma, French Montana",
    "Gold Digger - Kanye West ft Jamie Foxx",
    "Stronger - Kanye West",
    "Heartless - Kanye West",
    "Power - Kanye West",
    "Touch The Sky - Kanye West ft Lupe Fiasco",
    "Ni**as In Paris - Jay-Z ft Kanye West",
    "99 Problems - Jay-Z",
    "Hard Knock Life - Jay-Z",
    "Big Pimpin' - Jay-Z ft UGK",
    "Gin And Juice - Snoop Dogg",
    "Who Am I - Snoop Dogg",
    "Drop It Like It's Hot - Snoop Dogg ft Pharrell",
    "Nothin' On You - B.o.B ft Bruno Mars",
    "Airplanes - B.o.B ft Hayley Williams",
    "See You Again - Wiz Khalifa ft Charlie Puth",
    "Black And Yellow - Wiz Khalifa",
    "Love The Way You Lie - Eminem ft Rihanna",
    "Not Afraid - Eminem",
    "The Real Slim Shady - Eminem",
    "Without Me - Eminem",
    "Lose Yourself - Eminem",
    "Stan - Eminem ft Dido",
    "Rap God - Eminem",
    "Mockingbird - Eminem",
    "Till I Collapse - Eminem ft Nate Dogg",
    "Superman - Eminem ft Dina Rae",
    "Cleanin' Out My Closet - Eminem",
    "Forgot About Dre - Dr. Dre ft Eminem",
    "Ms. Jackson - OutKast",
    "Hey Ya! - OutKast",
    "The Way You Move - OutKast ft Sleepy Brown",
    "Roses - OutKast",
    "B.O.B. - OutKast",
    "No Diggity - Blackstreet ft Dr. Dre, Queen Pen",
    "Return Of The Mack - Mark Morrison",
    "This Is How We Do It - Montell Jordan",
    "Regulate - Warren G ft Nate Dogg",
    "Gin And Juice - Warren G",
    "Hypnotize - The Notorious B.I.G.",
    "I Got 5 On It - Luniz ft Michael Marshall",
    "It Was A Good Day - Ice Cube",
    "Today Was A Good Day - Ice Cube",
    "Jump Around - House Of Pain",
    "Insane In The Brain - Cypress Hill",
    "Tequila - The Champs",
    "Rock Around The Clock - Bill Haley & His Comets",
    "Great Balls Of Fire - Jerry Lee Lewis",
    "Johnny B. Goode - Chuck Berry",
    "Hound Dog - Elvis Presley",
    "Jailhouse Rock - Elvis Presley",
    "Can't Help Falling In Love - Elvis Presley",
    "Suspicious Minds - Elvis Presley",
    "Burning Love - Elvis Presley",
    "Blue Suede Shoes - Elvis Presley",
    "Blue Moon - Elvis Presley",
    "Viva Las Vegas - Elvis Presley",
    "I Walk The Line - Johnny Cash",
    "Ring Of Fire - Johnny Cash",
    "Folsom Prison Blues - Johnny Cash",
    "Hurt - Johnny Cash",
    "Man In Black - Johnny Cash",
    "Before He Cheats - Carrie Underwood",
    "Jesus Take The Wheel - Carrie Underwood",
    "The Gambler - Kenny Rogers",
    "Islands In The Stream - Kenny Rogers ft Dolly Parton",
    "Jolene - Dolly Parton",
    "9 To 5 - Dolly Parton",
    "I Will Always Love You - Dolly Parton",
    "Friends In Low Places - Garth Brooks",
    "The Dance - Garth Brooks",
    "Thunder Rolls - Garth Brooks",
    "Live Like You Were Dying - Tim McGraw",
    "Humble And Kind - Tim McGraw",
    "Need You Now - Lady A",
    "Chicken Fried - Zac Brown Band",
    "Wagon Wheel - Darius Rucker",
    "Cruise - Florida Georgia Line ft Nelly",
    "Meant To Be - Bebe Rexha ft Florida Georgia Line",
    "Old Town Road - Lil Nas X ft Billy Ray Cyrus",
    "Amarillo By Morning - George Strait",
    "Check Yes Or No - George Strait",
    "The Git Up - Blanco Brown",
    "Red Solo Cup - Toby Keith",
    "Courtesy Of The Red, White And Blue - Toby Keith",
    "Three Little Birds - Bob Marley",
    "No Woman No Cry - Bob Marley",
    "One Love - Bob Marley",
    "Could You Be Loved - Bob Marley",
    "Is This Love - Bob Marley",
    "Buffalo Soldier - Bob Marley",
    "Redemption Song - Bob Marley",
    "Jamming - Bob Marley",
    "Get Up Stand Up - Bob Marley",
    "I Shot The Sheriff - Bob Marley",
    "Turn Me On - Kevin Lyttle",
    "Temperature - Sean Paul",
    "Get Busy - Sean Paul",
    "We Be Burnin' - Sean Paul",
    "Like Glue - Sean Paul",
    "Gimme The Light - Sean Paul",
    "Rompe - Daddy Yankee ft Lloyd Banks",
    "Rakata - Wisin & Yandel",
    "Abusadora - Wisin & Yandel",
    "Mayor Que Yo - Luny Tunes ft Baby Ranks, Daddy Yankee, Wisin & Yandel",
    "Oye Mi Canto - N.O.R.E. ft Nina Sky, Gem Star, Big Mato",
    "Lean On - Major Lazer ft DJ Snake, MØ",
    "Light It Up - Major Lazer ft Nyla, Fuse ODG",
    "Cold Water - Major Lazer ft Justin Bieber, MØ",
    "Pon De Floor - Major Lazer",
    "Turn Down For What - DJ Snake ft Lil Jon",
    "Let Me Love You - DJ Snake ft Justin Bieber",
    "Middle - DJ Snake ft Bipolar Sunshine",
    "Magenta Riddim - DJ Snake",
    "Animals - Martin Garrix",
    "In The Name Of Love - Martin Garrix ft Bebe Rexha",
    "Scared To Be Lonely - Martin Garrix ft Dua Lipa",
    "Summer - Calvin Harris",
    "Feel So Close - Calvin Harris",
    "Sweet Nothing - Calvin Harris ft Florence Welch",
    "I Need Your Love - Calvin Harris ft Ellie Goulding",
    "This Is What You Came For - Calvin Harris ft Rihanna",
    "One Kiss - Calvin Harris ft Dua Lipa",
    "Promises - Calvin Harris ft Sam Smith",
    "How Deep Is Your Love - Calvin Harris ft Disciples",
    "Outside - Calvin Harris ft Ellie Goulding",
    "Blame - Calvin Harris ft John Newman",
    "Under Control - Calvin Harris ft Hurts, Big Sean",
    "We Found Love - Rihanna ft Calvin Harris",
    "Titanium - David Guetta ft Sia",
    "Memories - David Guetta ft Kid Cudi",
    "Hey Mama - David Guetta ft Nicki Minaj, Bebe Rexha, Afrojack",
    "Turn Me On - David Guetta ft Nicki Minaj",
    "Where Them Girls At - David Guetta ft Flo Rida, Nicki Minaj",
    "Play Hard - David Guetta ft Ne-Yo, Akon",
    "Sexy Bitch - David Guetta ft Akon",
    "When Love Takes Over - David Guetta ft Kelly Rowland",
    "Bangarang - Skrillex ft Sirah",
    "Scary Monsters And Nice Sprites - Skrillex",
    "First Of The Year - Skrillex",
    "Where Are U Now - Jack Ü ft Justin Bieber",
    "Clarity - Zedd ft Foxes",
    "Stay The Night - Zedd ft Hayley Williams",
    "The Middle - Zedd ft Maren Morris, Grey",
    "Break Free - Ariana Grande ft Zedd",
    "Spectrum - Zedd ft Matthew Koma",
    "Beautiful Now - Zedd ft Jon Bellion",
    "Wake Me Up Before You Go-Go - Wham!",
    "Careless Whisper - George Michael",
    "Faith - George Michael",
    "Freedom! '90 - George Michael",
    "Father Figure - George Michael",
    "Every Breath You Take - The Police",
    "Roxanne - The Police",
    "Message In A Bottle - The Police",
    "Don't Stand So Close To Me - The Police",
    "Every Little Thing She Does Is Magic - The Police",
    "With Or Without You - U2",
    "One - U2",
    "Beautiful Day - U2",
    "I Still Haven't Found What I'm Looking For - U2",
    "Where The Streets Have No Name - U2",
    "Sunday Bloody Sunday - U2",
    "Vertigo - U2",
    "Pride - U2",
    "New Year's Day - U2",
    "Under The Bridge - Red Hot Chili Peppers",
    "Losing My Religion - R.E.M.",
    "Man On The Moon - R.E.M.",
    "Everybody Hurts - R.E.M.",
    "It's The End Of The World As We Know It - R.E.M.",
    "Shiny Happy People - R.E.M.",
    "Stand - R.E.M.",
    "Drive - R.E.M.",
    "The One I Love - R.E.M.",
    "Nightswimming - R.E.M.",
    "Closing Time - Semisonic",
    "Flagpole Sitta - Harvey Danger",
    "Sex And Candy - Marcy Playground",
    "One Headlight - The Wallflowers",
    "Torn - Natalie Imbruglia",
    "Kiss Me - Sixpence None The Richer",
    "Unwritten - Natasha Bedingfield",
    "Pocketful Of Sunshine - Natasha Bedingfield",
    "These Words - Natasha Bedingfield",
    "A Thousand Miles - Vanessa Carlton",
    "White Flag - Dido",
    "Thank You - Dido",
    "Complicated - Avril Lavigne",
    "Sk8er Boi - Avril Lavigne",
    "My Happy Ending - Avril Lavigne",
    "Girlfriend - Avril Lavigne",
    "When You're Gone - Avril Lavigne",
    "I'm With You - Avril Lavigne",
    "Complicated - Avril Lavigne",
    "Since U Been Gone - Kelly Clarkson",
    "Because Of You - Kelly Clarkson",
    "Stronger - Kelly Clarkson",
    "Breakaway - Kelly Clarkson",
    "My Life Would Suck Without You - Kelly Clarkson",
    "Behind These Hazel Eyes - Kelly Clarkson",
    "Toxic - Britney Spears",
    "Womanizer - Britney Spears",
    "Circus - Britney Spears",
    "Gimme More - Britney Spears",
    "Till The World Ends - Britney Spears",
    "Hold It Against Me - Britney Spears",
    "Work Bitch - Britney Spears",
    "Scream & Shout - will.i.am ft Britney Spears",
    "Genie In A Bottle - Christina Aguilera",
    "What A Girl Wants - Christina Aguilera",
    "Fighter - Christina Aguilera",
    "Beautiful - Christina Aguilera",
    "Dirrty - Christina Aguilera ft Redman",
    "Candyman - Christina Aguilera",
    "A Thousand Years - Christina Perri",
    "Jar Of Hearts - Christina Perri",
    "Human - Christina Perri",
    "A Sky Full Of Stars - Coldplay",
    "Viva La Vida - Coldplay",
    "Speed Of Sound - Coldplay",
    "In My Place - Coldplay",
    "Trouble - Coldplay",
    "Shiver - Coldplay",
    "Magic - Coldplay",
    "Adventure Of A Lifetime - Coldplay",
    "Hymn For The Weekend - Coldplay",
    "Something Just Like This - The Chainsmokers ft Coldplay",
    "Chandelier - Sia",
    "Elastic Heart - Sia",
    "Cheap Thrills - Sia",
    "Unstoppable - Sia",
    "The Greatest - Sia ft Kendrick Lamar",
    "Alive - Sia",
    "Big Girls Cry - Sia",
    "Bird Set Free - Sia",
    "Snowman - Sia",
    "Flashlight - Jessie J",
    "Price Tag - Jessie J ft B.o.B",
    "Domino - Jessie J",
    "Burnin' Up - Jessie J ft 2 Chainz",
    "Bang Bang - Jessie J ft Ariana Grande, Nicki Minaj",
    "Masterpiece - Jessie J",
    "Who You Are - Jessie J",
    "Wrecking Ball - Miley Cyrus",
    "We Can't Stop - Miley Cyrus",
    "Malibu - Miley Cyrus",
    "Midnight Sky - Miley Cyrus",
    "Used To Be Young - Miley Cyrus",
    "Flowers - Miley Cyrus",
    "7 Things - Miley Cyrus",
    "The Climb - Miley Cyrus",
    "Party In The U.S.A. - Miley Cyrus",
    "Can't Be Tamed - Miley Cyrus",
    "Adore You - Miley Cyrus",
    "See You Again - Miley Cyrus",
    "We Found Love - Rihanna ft Calvin Harris",
    "Only Girl - Rihanna",
    "What's My Name? - Rihanna ft Drake",
    "S&M - Rihanna",
    "Love The Way You Lie - Eminem ft Rihanna",
    "FourFiveSeconds - Rihanna ft Kanye West, Paul McCartney",
    "Wild Thoughts - DJ Khaled ft Rihanna, Bryson Tiller",
    "Lift Me Up - Rihanna",
    "Bitch Better Have My Money - Rihanna",
    "Pour It Up - Rihanna",
    "Birthday Cake - Rihanna",
    "Cheers - Rihanna",
    "Don't Stop The Music - Rihanna",
    "Take A Bow - Rihanna",
    "Unfaithful - Rihanna",
    "Umbrella - Rihanna ft Jay-Z",
    "Pon De Replay - Rihanna",
    "Diamonds - Rihanna",
    "Work - Rihanna ft Drake",
    "Needed Me - Rihanna",
    "Kiss It Better - Rihanna",
    "Consideration - Rihanna ft SZA",
    "Breakin' Dishes - Rihanna",
    "Shut Up And Drive - Rihanna",
    "Man Down - Rihanna",
    "Rude Boy - Rihanna",
    "Te Amo - Rihanna",
    "Where Have You Been - Rihanna",
    "Disturbia - Rihanna",
    "Break My Soul - Beyoncé",
    "Crazy In Love - Beyoncé ft Jay-Z",
    "Single Ladies - Beyoncé",
    "Halo - Beyoncé",
    "Irreplaceable - Beyoncé",
    "Drunk In Love - Beyoncé ft Jay-Z",
    "Formation - Beyoncé",
    "Run The World - Beyoncé",
    "Love On Top - Beyoncé",
    "If I Were A Boy - Beyoncé",
    "Sorry - Beyoncé",
    "Hold Up - Beyoncé",
    "Déjà Vu - Beyoncé ft Jay-Z",
    "Bootylicious - Destiny's Child",
    "Jumpin' Jumpin' - Destiny's Child",
    "Bills Bills Bills - Destiny's Child",
    "No Scrubs - TLC",
    "Waterfalls - TLC",
    "Unpretty - TLC",
    "Creep - TLC",
    "Red Red Wine - UB40",
    "Can't Help Falling In Love - UB40",
    "Kingston Town - UB40",
    "Food For Thought - UB40",
    "I Got You Babe - UB40 ft Chrissie Hynde",
    "Freed From Desire - Gala",
    "Let A Boy Cry - Gala",
    "Come Into My Life - Gala",
    "Rhythm Is A Dancer - Snap!",
    "The Power - Snap!",
    "No Limit - 2 Unlimited",
    "Get Ready For This - 2 Unlimited",
    "Better Off Alone - Alice Deejay",
    "Barbie Girl - Aqua",
    "Doctor Jones - Aqua",
    "My Oh My - Aqua",
    "Lollipop - Aqua",
    "Be My Lover - La Bouche",
    "Sweet Dreams - La Bouche",
    "Rhythm Of The Night - Corona",
    "The Rhythm Of The Night - Corona",
    "What Is Love - Haddaway",
    "Life - Haddaway",
    "Scatman - Scatman John",
    "Gangsta's Paradise - Coolio ft L.V.",
    "C U When U Get There - Coolio ft 40 Thevz",
    "I'll Be Missing You - Puff Daddy ft Faith Evans, 112",
    "Hypnotize - The Notorious B.I.G.",
    "Mo Money Mo Problems - The Notorious B.I.G. ft Puff Daddy, Mase",
    "Juicy - The Notorious B.I.G.",
    "Big Poppa - The Notorious B.I.G.",
    "One More Chance - The Notorious B.I.G.",
    "Sky's The Limit - The Notorious B.I.G. ft 112",
    "N.Y. State Of Mind - Nas",
    "If I Ruled The World - Nas ft Lauryn Hill",
    "The World Is Yours - Nas",
    "Hate Me Now - Nas ft Puff Daddy",
    "Made You Look - Nas",
    "Doo Wop - Lauryn Hill",
    "Ex-Factor - Lauryn Hill",
    "Everything Is Everything - Lauryn Hill",
    "Killing Me Softly - Fugees",
    "Ready Or Not - Fugees",
    "Fu-Gee-La - Fugees",
    "Gin And Juice - Snoop Dogg",
    "Who Am I - Snoop Dogg",
    "Drop It Like It's Hot - Snoop Dogg ft Pharrell",
    "Beautiful - Snoop Dogg ft Pharrell",
    "Young Wild & Free - Snoop Dogg ft Wiz Khalifa, Bruno Mars",
    "Peaches N Cream - Snoop Dogg",
    "Sensual Seduction - Snoop Dogg",
    "Signs - Snoop Dogg ft Justin Timberlake, Charlie Wilson",
    "Nuthin' But A G Thang - Dr. Dre ft Snoop Dogg",
    "Still D.R.E. - Dr. Dre ft Snoop Dogg",
    "The Next Episode - Dr. Dre ft Snoop Dogg",
    "Forgot About Dre - Dr. Dre ft Eminem",
    "California Love - 2Pac ft Dr. Dre",
    "Changes - 2Pac",
    "Dear Mama - 2Pac",
    "Ambitionz Az A Ridah - 2Pac",
    "All Eyez On Me - 2Pac",
    "How Do U Want It - 2Pac",
    "I Get Around - 2Pac",
    "Keep Ya Head Up - 2Pac",
    "Do For Love - 2Pac",
    "Me Against The World - 2Pac",
    "Hit 'Em Up - 2Pac",
    "Smells Like Teen Spirit - Nirvana",
    "Come As You Are - Nirvana",
    "Lithium - Nirvana",
    "Heart-Shaped Box - Nirvana",
    "In Bloom - Nirvana",
]

# Recent chart toppers and global hits to close the gap to 5000.
THIRD_MEGA_HITS = [
    "Despacito - Luis Fonsi ft Daddy Yankee",
    "Die With A Smile - Lady Gaga ft Bruno Mars",
    "APT. - ROSÉ ft Bruno Mars",
    "Fortnight - Taylor Swift ft Post Malone",
    "Texas Hold 'Em - Beyoncé",
    "A Bar Song - Shaboozey",
    "I Had Some Help - Post Malone ft Morgan Wallen",
    "Lose Control - Teddy Swims",
    "Beautiful Things - Benson Boone",
    "Stick Season - Noah Kahan",
    "Greedy - Tate McRae",
    "Espresso - Sabrina Carpenter",
    "Please Please Please - Sabrina Carpenter",
    "Not Like Us - Kendrick Lamar",
    "Paint The Town Red - Doja Cat",
    "Houdini - Dua Lipa",
    "Birds Of A Feather - Billie Eilish",
    "Good Luck Babe - Chappell Roan",
    "Too Sweet - Hozier",
    "Beautiful As You - Thomas Rhett",
    "I Remember Everything - Zach Bryan ft Kacey Musgraves",
    "Something In The Orange - Zach Bryan",
    "Rich Men North Of Richmond - Oliver Anthony Music",
    "Last Night - Morgan Wallen",
    "Wasted On You - Morgan Wallen",
    "You Proof - Morgan Wallen",
    "Thinkin' Bout Me - Morgan Wallen",
    "Fast Car - Luke Combs",
    "Sand In My Boots - Morgan Wallen",
    "Whiskey Glasses - Morgan Wallen",
    "Chasin' You - Morgan Wallen",
    "Cover Me Up - Jason Isbell",
    "Tennessee Whiskey - Chris Stapleton",
    "Broken Halos - Chris Stapleton",
    "Starting Over - Chris Stapleton",
    "Wagon Wheel - Old Crow Medicine Show",
    "Die A Happy Man - Thomas Rhett",
    "Marry Me - Thomas Rhett",
    "Craving You - Thomas Rhett ft Maren Morris",
    "Life Changes - Thomas Rhett",
    "Hurricane - Luke Combs",
    "When It Rains It Pours - Luke Combs",
    "Beautiful Crazy - Luke Combs",
    "Forever After All - Luke Combs",
    "Better Together - Luke Combs",
    "One Number Away - Luke Combs",
    "Beer Never Broke My Heart - Luke Combs",
    "Even Though I'm Leaving - Luke Combs",
    "Does To Me - Luke Combs ft Eric Church",
    "She Got The Best Of Me - Luke Combs",
    "The Kind Of Love We Make - Luke Combs",
    "Going Going Gone - Luke Combs",
    "Love You Anyway - Luke Combs",
    "Where The Wild Things Are - Luke Combs",
    "Old Town Road - Lil Nas X ft Billy Ray Cyrus",
    "Industry Baby - Lil Nas X ft Jack Harlow",
    "Montero - Lil Nas X",
    "Star Walkin' - Lil Nas X",
    "Thats What I Want - Lil Nas X",
    "Unholy - Sam Smith ft Kim Petras",
    "About Damn Time - Lizzo",
    "Break My Soul - Beyoncé",
    "Sweet Child O' Mine - Guns N' Roses",
    "November Rain - Guns N' Roses",
    "Paradise City - Guns N' Roses",
    "Welcome To The Jungle - Guns N' Roses",
    "Patience - Guns N' Roses",
    "Knockin' On Heaven's Door - Guns N' Roses",
    "Live And Let Die - Guns N' Roses",
    "Free Fallin' - Tom Petty",
    "I Won't Back Down - Tom Petty",
    "Learning To Fly - Tom Petty",
    "Into The Great Wide Open - Tom Petty",
    "Mary Jane's Last Dance - Tom Petty",
    "American Girl - Tom Petty",
    "Refugee - Tom Petty",
    "Don't Do Me Like That - Tom Petty",
    "You Don't Know How It Feels - Tom Petty",
    "Running Down A Dream - Tom Petty",
    "Stop Draggin' My Heart Around - Stevie Nicks ft Tom Petty",
    "Edge Of Seventeen - Stevie Nicks",
    "Stand Back - Stevie Nicks",
    "Leather And Lace - Stevie Nicks ft Don Henley",
    "Dreams - Fleetwood Mac",
    "Go Your Own Way - Fleetwood Mac",
    "The Chain - Fleetwood Mac",
    "Rhiannon - Fleetwood Mac",
    "Everywhere - Fleetwood Mac",
    "Little Lies - Fleetwood Mac",
    "Gypsy - Fleetwood Mac",
    "Silver Springs - Fleetwood Mac",
    "Say You Love Me - Fleetwood Mac",
    "Over My Head - Fleetwood Mac",
    "Hold Me - Fleetwood Mac",
    "Tusk - Fleetwood Mac",
    "Sara - Fleetwood Mac",
    "Big Love - Fleetwood Mac",
    "Seven Wonders - Fleetwood Mac",
    "As Long As You Follow - Fleetwood Mac",
    "Skateaway - Dire Straits",
    "Sultans Of Swing - Dire Straits",
    "Money For Nothing - Dire Straits",
    "Walk Of Life - Dire Straits",
    "Brothers In Arms - Dire Straits",
    "Romeo And Juliet - Dire Straits",
    "Tunnel Of Love - Dire Straits",
    "Private Investigations - Dire Straits",
    "So Far Away - Dire Straits",
    "Your Latest Trick - Dire Straits",
    "On Every Street - Dire Straits",
    "Heavy Fuel - Dire Straits",
    "Calling Elvis - Dire Straits",
    "The Bug - Dire Straits",
    "Fade To Black - Metallica",
    "One - Metallica",
    "Master Of Puppets - Metallica",
    "Nothing Else Matters - Metallica",
    "The Unforgiven - Metallica",
    "Sad But True - Metallica",
    "Wherever I May Roam - Metallica",
    "Through The Never - Metallica",
    "Of Wolf And Man - Metallica",
    "The God That Failed - Metallica",
    "My Friend Of Misery - Metallica",
    "The Struggle Within - Metallica",
    "For Whom The Bell Tolls - Metallica",
    "Creeping Death - Metallica",
    "Seek And Destroy - Metallica",
    "Whiplash - Metallica",
    "Battery - Metallica",
    "Damage Inc. - Metallica",
    "Welcome Home - Metallica",
    "Disposable Heroes - Metallica",
    "Leper Messiah - Metallica",
    "Orion - Metallica",
    "Damage Inc. - Metallica",
    "Anarchy In The U.K. - Sex Pistols",
    "God Save The Queen - Sex Pistols",
    "Walk On The Wild Side - Lou Reed",
    "Perfect Day - Lou Reed",
    "Heroes - David Bowie",
    "Space Oddity - David Bowie",
    "Life On Mars? - David Bowie",
    "Starman - David Bowie",
    "Rebel Rebel - David Bowie",
    "Young Americans - David Bowie",
    "Fame - David Bowie",
    "Golden Years - David Bowie",
    "Let's Dance - David Bowie",
    "Modern Love - David Bowie",
    "China Girl - David Bowie",
    "Under Pressure - Queen ft David Bowie",
    "Ziggy Stardust - David Bowie",
    "Suffragette City - David Bowie",
    "Changes - David Bowie",
    "The Jean Genie - David Bowie",
    "Moonage Daydream - David Bowie",
    "Ashes To Ashes - David Bowie",
    "Fashion - David Bowie",
    "Cat People - David Bowie",
    "Blue Jean - David Bowie",
    "Dancing In The Street - David Bowie ft Mick Jagger",
    "Garota De Ipanema - João Gilberto ft Stan Getz",
    "Mas Que Nada - Sergio Mendes",
    "Ai Se Eu Te Pego - Michel Teló",
    "Balada - Gusttavo Lima",
    "Evolution - Alok ft The Chainsmokers",
    "Hear Me Now - Alok ft Zeeba",
    "Infinity - Jaymes Young",
    "Head & Heart - Joel Corry ft MNEK",
    "Baianá - Bakermat",
    "Rampampam - Minelli",
    "Be My Lover - La Bouche",
    "Rhythm Is A Dancer - Snap!",
    "No Limit - 2 Unlimited",
    "Macarena - Los Del Rio",
    "Lambada - Kaoma",
    "Volare - Domenico Modugno",
    "Bamboleo - Gipsy Kings",
    "Bailando - Enrique Iglesias ft Gente De Zona, Descemer Bueno",
    "El Perdón - Nicky Jam ft Enrique Iglesias",
    "Hasta El Amanecer - Nicky Jam",
    "Travesuras - Nicky Jam",
    "X - Nicky Jam ft J Balvin, Maluma, Ozuna",
    "Te Boté - Casper, Nio García, Darell, Nicky Jam, Bad Bunny, Ozuna",
    "Ella Baila Sola - Eslabon Armado ft Peso Pluma",
    "La Bebé - Yng Lvcas ft Peso Pluma",
    "Bzrp Music Sessions Vol. 53 - Shakira ft Bizarrap",
    "TQG - Karol G ft Shakira",
    "Provenza - Karol G",
    "Tusa - Karol G ft Nicki Minaj",
    "Bichota - Karol G",
    "MAMIII - Becky G ft Karol G",
    "Sin Pijama - Becky G ft Natti Natasha",
    "Mayores - Becky G ft Bad Bunny",
    "Dakiti - Bad Bunny ft Jhay Cortez",
    "Yonaguni - Bad Bunny",
    "Moscow Mule - Bad Bunny",
    "Efecto - Bad Bunny",
    "Tití Me Preguntó - Bad Bunny",
    "Me Porto Bonito - Bad Bunny ft Chencho Corleone",
    "Safaera - Bad Bunny",
    "Volví - Aventura ft Bad Bunny",
    "Obsesión - Aventura",
    "Propuesta Indecente - Romeo Santos",
    "Eres Mía - Romeo Santos",
    "Imitadora - Romeo Santos",
    "Bailamos - Enrique Iglesias",
    "Hero - Enrique Iglesias",
    "Escape - Enrique Iglesias",
    "Chantaje - Shakira ft Maluma",
    "Waka Waka - Shakira",
    "Whenever Wherever - Shakira",
    "Underneath Your Clothes - Shakira",
    "She Wolf - Shakira",
    "Try Everything - Shakira",
    "Hips Don't Lie - Shakira ft Wyclef Jean",
    "La Tortura - Shakira ft Alejandro Sanz",
    "Felices Los 4 - Maluma",
    "Hawái - Maluma",
    "Livin' La Vida Loca - Ricky Martin",
    "María - Ricky Martin",
    "She Bangs - Ricky Martin",
    "Shake Your Bon-Bon - Ricky Martin",
    "Nobody Wants To Be Lonely - Ricky Martin ft Christina Aguilera",
    "Gasolina - Daddy Yankee",
    "Con Calma - Daddy Yankee ft Snow",
    "Dura - Daddy Yankee",
    "Shaky Shaky - Daddy Yankee",
    "Limbo - Daddy Yankee",
    "Gangnam Style - PSY",
    "Gentleman - PSY",
    "Daddy - PSY",
    "Fantastic Baby - BIGBANG",
    "Bang Bang Bang - BIGBANG",
    "DDU-DU DDU-DU - BLACKPINK",
    "Kill This Love - BLACKPINK",
    "How You Like That - BLACKPINK",
    "Pink Venom - BLACKPINK",
    "Shut Down - BLACKPINK",
    "Dynamite - BTS",
    "Butter - BTS",
    "Permission To Dance - BTS",
    "Boy With Luv - BTS ft Halsey",
    "Spring Day - BTS",
    "DNA - BTS",
    "Fake Love - BTS",
    "Blood Sweat & Tears - BTS",
    "Super Shy - NewJeans",
    "Ditto - NewJeans",
    "OMG - NewJeans",
    "Attention - NewJeans",
    "Hype Boy - NewJeans",
    "Next Level - aespa",
    "Spicy - aespa",
    "Cupid - FIFTY FIFTY",
    "Unforgiven - LE SSERAFIM ft Nile Rodgers",
    "Queencard - (G)I-DLE",
    "Tomboy - (G)I-DLE",
    "Nxde - (G)I-DLE",
    "WANNABE - ITZY",
    "DALLA DALLA - ITZY",
    "CHEER UP - TWICE",
    "TT - TWICE",
    "Fancy - TWICE",
    "Feel Special - TWICE",
    "I Can't Stop Me - TWICE",
    "Cry For Me - TWICE",
    "Lemon - Kenshi Yonezu",
    "Idol - Yoasobi",
    "Kick Back - Kenshi Yonezu",
    "Pretender - Official HIGE DANdism",
    "Paprika - Foorin",
    "Guren No Yumiya - Linked Horizon",
    "Unravel - TK from Ling Tosite Sigure",
    "A Cruel Angel's Thesis - Yoko Takahashi",
    "The Real Folk Blues - Seatbelts",
    "Tank! - Seatbelts",
    "Again - YUI",
    "Silhouette - KANA-BOON",
    "Blue Bird - Ikimonogakari",
    "We Are! - Hiroshi Kitadani",
    "Ai Se Eu Te Pego - Michel Teló",
    "Balada - Gusttavo Lima",
    "Evolution - Alok ft The Chainsmokers",
    "Baianá - Bakermat",
    "Rampampam - Minelli",
    "Infinity - Jaymes Young",
    "Head & Heart - Joel Corry ft MNEK",
    "Garota De Ipanema - João Gilberto ft Stan Getz",
    "Mas Que Nada - Sergio Mendes",
    "Volare - Domenico Modugno",
    "Bamboleo - Gipsy Kings",
    "La Bamba - Ritchie Valens",
    "Macarena - Los Del Rio",
    "Lambada - Kaoma",
    "99 Luftballons - Nena",
    "Alors On Danse - Stromae",
    "Papaoutai - Stromae",
    "Beggin - Måneskin",
    "I Wanna Be Your Slave - Måneskin",
    "Zitti E Buoni - Måneskin",
    "Seven Nation Army - The White Stripes",
    "Mr. Brightside - The Killers",
    "Somebody That I Used To Know - Gotye ft Kimbra",
    "Pumped Up Kicks - Foster The People",
    "Royals - Lorde",
    "Riptide - Vance Joy",
    "Take Me To Church - Hozier",
    "Shut Up And Dance - Walk The Moon",
    "Cake By The Ocean - DNCE",
    "Can't Stop The Feeling! - Justin Timberlake",
    "Happy - Pharrell Williams",
    "Blurred Lines - Robin Thicke ft T.I., Pharrell",
    "Get Lucky - Daft Punk ft Pharrell Williams",
    "One More Time - Daft Punk",
    "Harder Better Faster Stronger - Daft Punk",
]


def main() -> None:
    spec = importlib.util.spec_from_file_location(
        "rebuild", SCRIPTS / "rebuild_random_songs.py"
    )
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader
    spec.loader.exec_module(mod)

    existing, catalog, supplemental = mod._collect_candidates()
    merged = mod._merge_unique([existing, catalog, supplemental])
    catalog_artists = set(mod._load_catalog_artists().keys())
    seen = {s.lower() for s in merged}

    fill: list[str] = []
    for s in MANUAL_LINES + MEGA_HITS + EXTRA_MEGA_HITS + THIRD_MEGA_HITS:
        k = s.lower()
        if k in seen:
            continue
        seen.add(k)
        fill.append(s)

    out = SCRIPTS / "famous_hits_fill.py"
    lines = [
        '"""Curated mega-hits in Title - Artist format (used by rebuild_random_songs.py)."""\n\n',
        "FAMOUS_HITS: list[str] = [\n",
    ]
    for s in fill:
        lines.append(f'    "{s}",\n')
    lines.append("]\n")
    out.write_text("".join(lines), encoding="utf-8")
    print(f"Merged base: {len(merged)} | Fill adds: {len(fill)} | Total potential: {len(merged)+len(fill)}")


if __name__ == "__main__":
    main()
