"""Extra famous hits to reach exactly 5000 unique canonical entries."""

TOPUP_HITS: list[str] = [
    "Take Five - Dave Brubeck",
    "What A Diff'rence A Day Makes - Dinah Washington",
    "Mona Lisa - Nat King Cole",
    "Black Magic Woman - Santana",
    "Smooth - Santana ft Rob Thomas",
    "Maria Maria - Santana",
    "Knockin' On Heaven's Door - Bob Dylan",
    "The Times They Are A-Changin' - Bob Dylan",
    "Annie's Song - John Denver",
    "Con Te Partirò - Andrea Bocelli",
    "Time To Say Goodbye - Andrea Bocelli",
    "The Prayer - Andrea Bocelli",
    "Ne Me Quitte Pas - Jacques Brel",
    "Pookie - Aya Nakamura",
    "Copines - Aya Nakamura",
    "Bella Ciao - Manu Pilas",
    "Felicità - Al Bano",
    "L'Italiano - Toto Cutugno",
    "Ti Amo - Umberto Tozzi",
    "Vivo Per Lei - Giorgia",
    "La Gasolina - Daddy Yankee",
    "Te Boté - Casper",
    "Ella Quiere Beber - Anuel AA",
    "Te Soñé De Nuevo - Yandel",
    "Dile - Don Omar",
    "La Gozadera - Gente De Zona",
    "Bailando - Gente De Zona",
    "Eres Tu - Jesse y Joy",
    "Lo Que Construimos - Natalia Lafourcade",
    "Hasta La Raiz - Natalia Lafourcade",
    "Bitter Sweet Symphony - The Verve",
    "The Drugs Don't Work - The Verve",
    "I Drove All Night - Cyndi Lauper",
    "Stay - The Kid LAROI",
    "I Knew You Were Trouble - Taylor Swift",
    "Willow - Taylor Swift",
    "Bad Idea Right - Olivia Rodrigo",
    "FE!N - Travis Scott",
    "Sunroof - Nicky Youre",
    "abcdefu - Gayle",
    "Applause - Lady Gaga",
    "Cuff It - Beyonce",
    "Love On The Brain - Rihanna",
    "People - Libianca",
    "Bandana - Fireboy DML",
    "Monalisa - Lojay",
    "Soso - Omah Lay",
    "Queencard - G I-DLE",
    "Magnetic - Illit",
    "Sheesh - Babymonster",
    "Die With A Smile - Bruno Mars",
    "Can't Hold Us - Macklemore",
    "Thrift Shop - Macklemore",
    "Glorious - Macklemore",
    "Same Love - Macklemore",
    "Feel This Moment - Pitbull",
    "U Remind Me - Usher",
]
